### ISSUE TITLE
MailService.DefaultServerCertificateValidationCallback protected in .Net Core 3

### ISSUE THREAD

**Issue by AndrewZenith** [jstedfast/MailKit#1008]
Using this code in .Net 4.6.1:

outputAccount.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => {
                                        bool res = MailService.DefaultServerCertificateValidationCallback(sender, certificate, chain, sslPolicyErrors);
                                        if (res)
                                            return true;
                                        if (draft.EmailServerIDXpo.IgnoreCertificateErrors)
                                            return true;
                                        if (certificate is X509Certificate2 cert && thumbs.Contains(cert.Thumbprint))
                                            return true;
                                        return false;
                                    };

public static bool DefaultServerCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors);

In a .Net Core 3.1 project, same code fails to compile.

protected bool DefaultServerCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors);

How do I go about doing the same in .Net Core 3?

**Comment by jstedfast** [comment]
I had to break API because I had to change the way this was done so that I could report more informative errors.

Also, the old DefaultServerCertificateValidationCallback() was technically insecure because it accepted self-signed certificates, so you really shouldn't be using it in production code.

See https://github.com/jstedfast/MailKit/issues/1002 for why this was changed.
