### ISSUE TITLE
Var Query doesn't work properly

### ISSUE THREAD

**Issue by MisterCookie1234** [jstedfast/MailKit#1011]
Good afternoon good Sir..
Sorry to bother you again, i fixed my code completly but can't get the hang upon one small error.
I am trying to fetch every message containing a subject and a specific E-Mail.

```
var query = SearchQuery.SubjectContains(subject).And(SearchQuery.FromContains(emailfrom));
                var uids = client.Inbox.Search(query);
```

As far as i see it, this should be the correct way of doing it.
Unfortunately - The Program doesn't find any Emails if i do it like that.
When i try "Or" instead of "And" it finds emails containing the subject and dozens of emails from the email i told him, but not when i combine it with And. 

Is there a mistake in my thinking? 
I tried to come up with a solution myself and asked some good friends, but everyone told me this looks right so far. Do i need to change something to let it work properly?

Sorry for bothering you again
Greetings

**Comment by jstedfast** [comment]
What does your `emailfrom` string look like? Does it contain the person's name? Or just their email address? Does it contain the `<>`'s?

The problem with IMAP SEARCH is that it is implementation-specific, meaning that each server implements string matching differently (this is especially noticeable with email address queries).

Some servers will match the string you provide in the search query with the decoded header, some will compare with the raw (encoded) header.

Some servers will match email addresses with the name(s) & address(es) in the From/To/Cc header, some will match only against the addresses and not use the names at all.

Some servers will match against the name, and if that fails, try matching against the address. This obviously means that if you search for `"LastName <alias@"` (because maybe this person uses the same alias across multiple mail servers - gmail.com, yahoo.com, employer.com, etc), it will fail because that string requires being matched against the name & address combined.

**Comment by MisterCookie1234** [comment]
The emailfrom string looks like this:
`<add key="emailfrom" value="emailadress@email.net" />`

I tried it with the persons name aswell, but switched it back to their email since the name didn't work either. The strange thing occuring is, that it works well with .Or - The program finds every email containing the subject1 and every email from the given emailadress. But whenever i change it to .And - Nothing.

**Comment by jstedfast** [comment]
You could try `SearchQuery.HeaderContains ("From", "emailaddress@email.net")`

**Comment by MisterCookie1234** [comment]
Good Morning,

unfortunately, using HeaderContains, he does not find anything. 
However tho, i figured out that FromContains only reacts to the Name of the sender 
(For Example: IT-as-a-Service, but not for the Email Adresss) but still, 
whenever i change

`var query = SearchQuery.SubjectContains("Test").Or(SearchQuery.FromContains(IT-as-a-Service));`

to

`var query = SearchQuery.SubjectContains("Test").And(SearchQuery.FromContains(IT-as-a-Service));`

with the only significant change being replacing the .Or with .And, forcing him to look at FromContains and SubjectContains, he doesn't find any mails, even tho there are lots of Test Mails featuring the right sender and right subject name.
