### ISSUE TITLE
Timeout on sending emails after upgrading to 2.6

### ISSUE THREAD

**Issue by kurucz09** [jstedfast/MailKit#1023]
**Description**
Yesterday, the 13-th of May we upraded our Mimekit+MailKit from 2.0.1 to 2.6. Since then we started experiencing failures in email sending, we had six failures out of 11.000 mails. The size of the failed emails varied from 9Kb to 1.5 MB. We do not explicitly set a timout on the Smtpclient, as we saw in the code the default 2 second timeout was used. 
In our effort to reproduce the issue we set a timeout of 1 second and deployed the application to our test environment. We sent two emails:
First email with smaller image attachments, around 500 KB, this failed and we got the same exception as in production, however the interesting part was that the mail also got delivered, despite the failure. In our code we don't have retry logic for sending
Second email, much larger with 27 MB of attachment succeeded without issues.
**Exception**
This is the exception we receive:
System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at async Task<int> MailKit.Net.NetworkStream.ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
   at TResult System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
   at async ValueTask<int> System.Net.Security.SslStream.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at TResult System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
   at async ValueTask<int> System.Net.Security.SslStream.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   --- End of inner exception stack trace ---
   at async ValueTask<int> System.Net.Security.SslStream.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task<int> MailKit.Net.Smtp.SmtpStream.ReadAheadAsync(bool doAsync, CancellationToken cancellationToken)
   at async Task<SmtpResponse> MailKit.Net.Smtp.SmtpStream.ReadResponseAsync(bool doAsync, CancellationToken cancellationToken)
   at async Task MailKit.Net.Smtp.SmtpClient.DataAsync(FormatOptions options, MimeMessage message, long size, bool doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at async Task MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList<MailboxAddress> recipients, bool doAsync, CancellationToken cancellationToken, ITransferProgress progress)

What might be important to mention is that we create a new SmtpClient on each new session and dispose of it in the OnSessionCompleted or OnSessionFaulted events. As I read this might not be the best practice, however this is how it was implemented a while ago.

We also saw that the latest release include changes related to read/write stream timeouts:
https://github.com/jstedfast/MailKit/commit/382c1b7f685006ec29e870a1ef7155a8be176bdf
And that there were some recent discussion related to it:
https://github.com/jstedfast/MailKit/issues/827

Since this is a production issue a fix for this is quite a high priority for us. Thanks :).

The application is running in .Net Core 3.1 hosted in a docker container.

**Comment by jstedfast** [comment]
The default timeout is 2 minutes, not 2 seconds:

```csharp
int timeout = 2 * 60 * 1000;
```

The message probably arrived at the destination because the cancel exception probably happened *after* MailKit sent all of the data in the DATA command, while it was waiting for the server to respond. That's what it looks like from the stack trace.

The fix for issue #827 only added logic for auto-cancelling a socket read/write if the normal TCP/IP socket timeout duration expired. Normally, with System.Net.Sockets, the read/write timeouts are ONLY used in the synchronous I/O APIs while the async I/O APIs ignore them. This just added support for socket timeouts for the async methods.

Maybe you could try to find the last released version of MailKit that works for you and use that? You could try 2.5.x, 2.4.x, 2.3.x, etc. That might be useful information.

I'm not sure what I can do to fix this since I can't reproduce your issue in any way that demonstrates a bug in MailKit.

**Comment by kurucz09** [comment]
Thanks you for the fast reply. 
Yes, it was a typo I wanted to write 2 minutes.
We will repeat our test with version 2.5.x tomorrow and see if it makes a difference.

**Comment by jstedfast** [comment]
> So if I understand correctly this change means that until now we were using SendAsync without a timeout and now that also has a timeout of 2 minutes?

Let me just clarify this a bit just in case there is any confusion.

SmtpClient.SendAsync() itself doesn't have a 2-minute timeout. The timeout is per I/O call on a socket. So, for example, anytime MailKit goes to read or write a buffer to the underlying socket, there is a 2 minute timeout. But sending the message itself could exceed an hour long operation if that's what it needed in order to send all of the data *as long as* each individual low-level socket write call doesn't exceed the 2 minute timeout.

Does that make sense?

A few more thoughts that may help you debug this...

It looks like you are using SSL, so that makes this more complicated because SslStream buffers socket data internally because it needs to encrypt/decrypt packets and each higher-level Stream.Read() or Stream.ReadAsync() call, for example, might not read the full (decrypted) packet of data that arrived.

SmtpStream.cs has a method called [ReadAheadAsync](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpStream.cs#L220) that buffers data for the higher-level SMTP reader methods such as [ReadResponseAsync](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpStream.cs#L443) (which was one of the frames in your stack trace).

What ReadResponseAsync() attempts to do is to read only 1 response (and only 1 response) from the SMTP server.

Originally, an SMTP response would be a single line like this:

```
250 Message accepted.
```

Where the first token is a number indicating a response code (250) and everything after it is free-flow text.

But things got more complicated with SMTP:

```
250-First line of free-flow text
250-Second line of free-flow text
250 Last line of free-flow text
```

If the numeric token is followed by a `-` character, then it means there is at least 1 more line of the response, so the reader needs to keep reading.

If there is a bug in MailKit, it will probably either be in ReadResponseAsync() or it will be somewhere lower level and possibly due to some sort of interaction with SslStream.

Question for you:

Does your application *always* send via the same SMTP server? Or does it use a variety of SMTP servers?

Something else you might be able to look into is whether or not the SMTP server(s) that you are getting timeouts from support the `PIPELINING` extension.

If they do, that could be another source of a possible bug (in MailKit or in the server - there's been at least 1 bug reported to me related to PIPELINING that turned out to be a bug in an SMTP server).

You can check this by using the following code snippet (after Authenticate (or after Connect if you don't Authenticate)):

```csharp
if (client.Capabilities.HasFlag (SmtpCapabilities.Pipelining))
    Console.WriteLine ("This server supports PIPELINING!");
```

What you can try (to see if it fixes things), is to do:

```csharp
client.Capabilities &= ~SmtpCapabilities.Pipelining;
```

This will disable PIPELINING support in the SmtpClient (effectively it makes SmtpClient forget that the SMTP server reported supporting the PIPELINING extension, the result being that MailKit won't try to use it).

Hope that helps.

**Comment by kurucz09** [comment]
Hi,

Thanks for the detailed answer.

Our component operates as a smart host for Exchange Online, so Exchange Online is the only SMTP server that we communicate with.

I checked pipelining and indeed it is enabled. Turning it off seems to help, meaning that if I get and NDR then the mail is trully not set. Would it have some performance penalties if I turn this off?

Also one pattern that I managed to reproduce this is if I send an email right after our instance (pod) is started.

If all that changed in the last release is that the smtpclient timeout was applied also to the read and write sockets then theoretically the solution would be that I set the timeout value to a big enough value. Although the 2 minutes at a first look seems to be a big enough one, as I see it here the stream time out is infinite by default, so I guess that was the value that was used before.
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.readtimeout?view=netcore-3.1

**Comment by jstedfast** [comment]
> Would it have some performance penalties if I turn this off?

Yes, but I suspect it would be negligible unless you've got a lot of recipients. The commands that get pipelined are just the `MAIL FROM` and `RCPT TO` commands. Even if you do have a lot, if you have low latency, then it may not be all that noticeable.

> theoretically the solution would be that I set the timeout value to a big enough value

Perhaps, but as you mentioned, 2 minutes is a fairly sizable timeout but as the documentation link you pasted above notes, by default, it seems NetworkStream uses an infinite timeout.

(which is confirmed here: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.readtimeout?view=netcore-3.1#System_Net_Sockets_NetworkStream_ReadTimeout )

You could try setting the timeout on SmtpClient to `Timeout.Infinite`.

**Comment by jstedfast** [comment]
Did setting the timeout to `infinite` work for you?

**Comment by kurucz09** [comment]
We just finished our load testing and it seems it works. We are going to release it to production today and keep monitoring it, but we expect this to be ok now.
Thanks for your help.

About pipelining, since performance is crucial for us, our component being responsible for real time email processing (receiving it and sending back to exchange online via outbound and inbound connectors), we decided to not modify it for now.

**Comment by jstedfast** [comment]
Okay. Keep me updated. My gut instinct tells me it's not really a PIPELINING issue anyway.

**Comment by kurucz09** [comment]
We release the fix on Tuesday, since then there has been no issue, however the mail sending rate has been lower then usual due to holiday.
We will monitor it next week to be sure, but so far it seems it is the right fix.
Thanks again for your help.

**Comment by jstedfast** [comment]
No problem :-)

**Comment by kurucz09** [comment]
The new version still runs fine, we had two full days without issues so I think we can consider it fixed.
