### ISSUE TITLE
DeliveryStatusNotification for SMTP MailKit.Net.Smtp.SmtpClient

### ISSUE THREAD

**Issue by PrzemyslawKlys** [jstedfast/MailKit#1038]
Hi,

I'm trying to build a PowerShell module that uses MailKit/MimeKit to deliver full functionality to PowerShell users. 

The original command for PowerShell syntax:

```
    Send-MailMessage [-To] <string[]> [-Subject] <string> [[-Body] <string>] [[-SmtpServer] <string>] -From <string>
    [-Attachments <string[]>] [-Bcc <string[]>] [-BodyAsHtml] [-Encoding <Encoding>] [-Cc <string[]>]
    [-DeliveryNotificationOption {None | OnSuccess | OnFailure | Delay | Never}] [-Priority {Normal | Low | High}]
    [-Credential <pscredential>] [-UseSsl] [-Port <innt>]  [<CommonParameters>]
```

I want to try to mimic it for easy use and then expand with the cool features of Mailkit/Mimekit.

One of the features missing from "default" implementation is DeliveryStatusNotification. I saw some of your tips all over the place:
- https://stackoverflow.com/questions/31220468/how-to-check-e-mail-status-is-delievered-or-not-in-c-sharp
- https://github.com/jstedfast/MailKit/issues/602
- https://stackoverflow.com/questions/52216356/how-get-email-sent-status-in-mailkit-with-asp-net-core
-http://www.mimekit.net/docs/html/M_MailKit_Net_Smtp_SmtpClient_GetDeliveryStatusNotifications.htm

But implementing this in PowerShell seems to be complicated enough that I wanted to ask whether maybe there's some easier way for you to deliver this functionality then me trying to rewrite your class in PowerShell classes which probably will slow thing down?

Is there any reason you're not "natively" adding this? 

I'm sorry if this is noobish, but I have some basic c# skills, and just trying to make useful PowerShell community modules but some stuff requires significant work that is not easily achievable.

**Comment by PrzemyslawKlys** [comment]
I was able to figure it out - but still would be nice having this native.
```powershell
    class MySmtpClient : MailKit.Net.Smtp.SmtpClient {
        MySmtpClient() : base() {}

        [string] $DeliveryNotificationOption = @()
        [Nullable[MailKit.DeliveryStatusNotification]] GetDeliveryStatusNotifications([MimeKit.MimeMessage]$message, [MimeKit.MailboxAddress]$mailbox) {
            $Output = @(
                if ($this.DeliveryNotificationOption -contains 'OnSuccess') {
                    [MailKit.DeliveryStatusNotification]::Success
                } elseif ($this.DeliveryNotificationOption -contains 'Delay') {
                    [MailKit.DeliveryStatusNotification]::Delay
                } elseif ($this.DeliveryNotificationOption -contains 'OnFailure') {
                    [MailKit.DeliveryStatusNotification]::Failure
                } elseif ($this.DeliveryNotificationOption -contains 'Never') {
                    [MailKit.DeliveryStatusNotification]::Never
                }
            )
            if ($Output.Count -gt 0) {
                return $Output
            }
            return $null
        }
    }
```

**Comment by jstedfast** [comment]
> trying to rewrite your class in PowerShell classes which probably will slow thing down?

It shouldn't since all you would need to do is subclass what is already there. Of course, I have no idea if that's even possible in PowerShell because I'm kind of a PowerShell noob. But assuming you can subclass C# classes, then it'll have no significant impact on performance.

> Is there any reason you're not "natively" adding this?

You may have noticed the split between MimeKit (a library for creating and parsing MIME messages) and MailKit (which does the sending and receiving of messages).

MIME doesn't have a notion of Delivery Status Notification, really. There's no MIME headers for this, for example. It's something that is specific to the SMTP protocol and is separate from the message itself.

One option I *could* have done to support this natively in MailKit is to allow passing a DeliveryStatusNotificationInfo object to the Send() method that specifies what the envelope-id and what events you want to be notified about, but every time you add a parameter to a method, you explode the number of overloads that it has and that gets gross.

So, for better or worse, what I did was to provide hooks for the functionality if you subclass the SmtpClient and override a few simple methods/properties.

**Comment by PrzemyslawKlys** [comment]
I see. Oh well. I managed to figure it out in PowerShell, it works and I guess I can live with it. 

Your idea with Send seems like a cool thing. Or maybe the property of: `[MimeKit.MimeMessage]`

This way I could simply do:
```powershell
$Message = [MimeKit.MimeMessage]::new()
$Message.DeliveryNotificationOption = [MailKit.DeliveryStatusNotification]::Success
```

**Comment by jstedfast** [comment]
That would be a gross hack ;-)
