### ISSUE TITLE
FolderAttributes issue after Important value is added

### ISSUE THREAD

**Issue by Nevca** [jstedfast/MailKit#1063]
We just updated MailKit's codebase to latest and saw that the FolderAttributes assigned were wrong (specifically Inbox, Junk, Sent, and Trash),

The breaking change comes from this commit: https://github.com/jstedfast/MailKit/commit/5d98210a971ca636e64c8bb360bf36f6b53083e0

Most email client implementations have some sort of local cache and they have already stored FolderAttributes in it. So after they update their MailKit, they will have issues with all of the enum values after `Important     = (1 << 13)`

Isn't it better to add Important as `(1 << 17)` without changing the other values?

**Comment by jstedfast** [comment]
Probably, so how do you propose changing it now w/o breaking anyone?

Now that I know people are caching this enum as an integer, I won't make similar changes in the future, but I think it's too late to undo this change.

**Comment by jstedfast** [comment]
I'm marking this as wontfix because even though you are correct that it is a bug, I can't undo it without causing another break.

I'll be more careful about this in the future. Thanks for bringing this to my attention.

I reordered the enum because of my OCD and I wrongly assumed no one was caching these values.
