### ISSUE TITLE
SMTP email box pinging

### ISSUE THREAD

**Issue by Voileexperiments** [jstedfast/MailKit#1075]
Email box pinging is a common technique to check if SMTP connection with a target server can be made, client is authenticated and authorized to send/relay emails, the recipient(s) mail boxes exist, and the sender/recipient(s) are allowed by the server, all without sending actual emails. It's commonly used by automatic systems which checks if it's *very probable* that target recipient's email address exists.

Ref: https://blog.mailtrap.io/verify-email-address-without-sending/#Email_box_pinging

Currently this is not supposed by MailKit.

Note that just authenticating is **not enough**: the authenticated user might not have relaying right, and `SEND FROM` or `RCPT TO` can be rejected by the server. They are only validated after `SEND FROM` and `RCPT TO` is sent, but before `DATA`. These authorization checking are just as important as authentication.

The email can still be blocked after `DATA END`, but once that happens either the email is sent or it fails, so an email *will* be sent in most cases. Besides, most of the cases where this happens are due to outside factors, which is much rarer than the cases where email box pinging fails.

The process details to bailing out of the process before `DATA` is sent, then possibly sending a `RSET` to clear `SEND FROM` and `RCPT TO` data. It shouldn't affect anything else, and the client can start from `MAIL FROM` after a `RSET`.

**Comment by jstedfast** [comment]
I'm not really interested in implementing this. Going forward, you'll find that this technique works less and less reliably. You'll already find that this technique doesn't work on any of the big email providers like GMail.

The only reliable way to know if an email address works is to send a message to that address and get the user to either reply or click a link or something.

Another option is to use [delivery status notification](https://tools.ietf.org/html/rfc3464) and/or [message disposition notification](https://tools.ietf.org/html/rfc3798).

To check if the SMTP server supports delivery status notification, you can check `client.Capabilities.HasFlag (SmtpCapabilities.Dsn)`.

For more about how to request delivery status notifications using MailKit, check the following docs: http://www.mimekit.net/docs/html/M_MailKit_Net_Smtp_SmtpClient_GetDeliveryStatusNotifications.htm

**Comment by Voileexperiments** [comment]
> Going forward, you'll find that this technique works less and less reliably. You'll already find that this technique doesn't work on any of the big email providers like GMail.
> 
> The only reliable way to know if an email address works is to send a message to that address and get the user to either reply or click a link or something.

This only answer part of the question. What about email functionality health-checking for back-end, which would be run routinely? In this case we don't really need to know if the sender/recipient email address exist (since it's typically a hard-coded one known to work), but we do want to verify that we're *almost certain* we can send a email, without actually sending emails since that'd generate lots of spam with no good reasons. As mentioned above, passing the authentication alone is far away from being very certain the email sending function is working.

> Another option is to use delivery status notification and/or message disposition notification.

Again, these only work after the email is actually sent. It doesn't do a dry run, aka not actually sending the emails.

**Comment by jstedfast** [comment]
What happens when you send a `RCPT TO` command to a GMail SMTP server with completely made-up addresses?

**Comment by Voileexperiments** [comment]
> What happens when you send a `RCPT TO` command to a GMail SMTP server with a completely made-up address?

I don't see how this is relevant to my previous post at all:

1. I don't see why we should assume GMail SMTP server in this scenario. There are other SMTP servers widely used, like Amazon SES and Office 365. And in general, most SMTP servers (including corporate ones) are configured like normal SMTP servers, while GMail SMTP server is a massive outlier out of the field.

2. I also don't see why we're restricting the use case model to be validating unknown email address. Email box pinging is useful to confirming SMTP configuration works after authorization and sender/receiver check. Pretty much every hardened SMTP server will check this. I don't just want to know if I can be authenticated; I want to know if I'm actually *allowed* to send email, without actually sending one out.

**Comment by jstedfast** [comment]
Walk me through your real-world use-case.

**Comment by jstedfast** [comment]
Are you aware of the VRFY command and did you know that MailKit implements support for this command?

**Comment by Voileexperiments** [comment]
> Are you aware of the VRFY command and did you know that MailKit implements support for this command?

VRFY is disabled in every hardened SMTP server for spam protection. Besides, it only covers the use case of verifying if an email address exist. It doesn't cover other use cases of email box pinging.

**Comment by Voileexperiments** [comment]
> Walk me through your real-world use-case.

Routine health-checking for SMTP server connection to a private SMTP server. Said SMTP connection are not used frequently (a few mails every few days) so a bad connection can go unnoticed for days. Authentication alone doesn't work because the server has additional hardening (e.g checking sending whitelist against the *machine* that the client is from), and we definitely don't want to actually send a email after every health-check; that'd drown the actual signal and cause more problems for what it's worth.

The SMTP server is managed by a different team so we cannot touch that ourselves.

**Comment by jstedfast** [comment]
> VRFY is disabled in every hardened SMTP server for spam protection.

I know, which is also why at least some SMTP servers will not reject an address used with a `RCPT TO` command. Same principle. I just figured that it sounded like all you needed to do was to verify an address and if you only care about private SMTP servers, then VRFY might be enabled (or you might be able to ask for it to be enabled).

> Routine health-checking for SMTP server connection to a private SMTP server. Said SMTP connection are not used frequently (a few mails every few days) so a bad connection can go unnoticed for days. Authentication alone doesn't work because the server has additional hardening (e.g checking sending whitelist against the machine that the client is from), and we definitely don't want to actually send a email after every health-check; that'd drown the actual signal and cause more problems for what it's worth.
> 
> The SMTP server is managed by a different team so we cannot touch that ourselves.

So this isn't about verifying that a mailbox (aka email address) can receive mail, it's about checking if an SMTP server is operational?

Now I'm even more confused, to be honest...

You've got a privately configured SMTP server at your company that you want to do a periodic "health check" on to see if it will allow you to relay mail, but you don't actually want to relay mail at that point in time.

Let's say your "health check" is successful. Then what?

My point is that by the time you *do* need to use the SMTP server to relay a message, it might not allow you to do so and this "health check" that you are trying to implement is proven to be completely worthless.

If the point is to warn you if/when the SMTP server goes down so that the SMTP server admins can fix it before your service needs to relay a message, then wtf? Why is the team at your company that is managing said SMTP server not doing this instead? They aren't very good at managing the SMTP server if it is going down so often that you feel the need to implement this "health check".

Seems like you've got a very, very, very unique problem that you are trying to work around.

Good luck, I guess.

I would just recommend forking MailKit and making the custom changes you need to send MAIL FROM and RCPT TO commands w/o sending a message. I just don't see how this would be generically useful.

**Comment by Voileexperiments** [comment]
>  I just figured that it sounded like all you needed to do was to verify an address and if you only care about private SMTP servers, then VRFY might be enabled (or you might be able to ask for it to be enabled).

The use of `VRFY` is mostly irrelevant in this scenario (and mostly a bad idea):
1. `VRFY` is not mandatory to be enabled (in fact it's usually disabled), are often configured to lie, and aren't even implemented in some SMTP servers.
2. Logically `VRFY` has nothing to do with checking: it only checks if a mailbox exist. Please be reminded again that we're not focusing on *verifying the recipient address*. We're interested in seeing if we're authorized to send email from the address, which is a valid concern since being authenticated doesn't mean being authorized.
3. The one who manages the server can always reject it on the grounds that it's against hardening rules, not to mention that most vulnerability scanners will yell at it. It's causing way more problems than what it's worth. You're also assuming the ones managing the SMTP server *can* be contacted.

> So this isn't about verifying that a mailbox (aka email address) can receive mail, it's about checking if an SMTP server is operational?

No. Let me re-iterate again: *Being successfully authenticated doesn't mean much during the process of sending email through SMTP*. There are many reasons `MAIL FROM` and `RCPT TO` can fail (just Google for "(in reply to MAIL FROM command)"/"(in reply to RCPT TO command)" and see for yourself), which can be trivially avoided if the SMTP client just send them too, which is also trivial for the client.

> My point is that by the time you do need to use the SMTP server to relay a message, it might not allow you to do so and this "health check" that you are trying to implement is proven to be completely worthless.

??? I don't understand your logic. So by the same analogy, by the time you need to fetch some resources over HTTP, it might be down and so it'd be proven to be worthless to check if the resource exists? That's what `HEAD` is for? So you're saying `HEAD` is not worth implemented because it doesn't 100% equate to being able to actually fetch the resource?

> If the point is to warn you if/when the SMTP server goes down so that the SMTP server admins can fix it before your service needs to relay a message, then wtf?

??? That's literally the point of health-checking. If for some reasons emails can't be sent the relevant people should be notified as soon as possible. Knowing this right after it failed instead of when it's actually used again is faster, and so it's worth doing.

**Comment by jstedfast** [comment]
Trust me, I know all about VRFY. You don't need to lecture me about it because I've been doing mail for 20+ years. I offered it merely as a suggestion because my understanding was that this was a private SMTP server that your company owned and you just needed to verify if some mailboxes existed.

> No. Let me re-iterate again: Being successfully authenticated doesn't mean much during the process of sending email through SMTP. There are many reasons MAIL FROM and RCPT TO can fail (just Google for "(in reply to MAIL FROM command)"/"(in reply to RCPT TO command)" and see for yourself), which can be trivially avoided if the SMTP client just send them too, which is also trivial for the client.

Yes, I know all about SMTP errors to `MAIL FROM` and `RCPT TO` commands. I read the specifications for the SMTP protocol dozens of times spanning back from the late 90's to today.

> which can be trivially avoided if the SMTP client just send them too, which is also trivial for the client.

Huh? Are you thinking that MailKit *doesn't* send the `MAIL FROM` or `RCPT TO` commands?

> ??? I don't understand your logic. So by the same analogy, by the time you need to fetch some resources over HTTP, it might be down and so it'd be proven to be worthless to check if the resource exists? That's what HEAD is for? So you're saying HEAD is not worth implemented because it doesn't 100% equate to being able to actually fetch the resource?

That's not at all my argument.

It sounded to me (correct me if I'm wrong, because your explanations have been very poor so far) that you are running some sort of periodic check to see if you can send mail from A to B where A and B are constants.

If you need to do a periodic check to see if you can send mail from A to B, then it suggests to me that sending mail from A to B is unreliable and that the SMTP server's configuration is constantly changing.

If that is the case, then checking on Monday to see if you can send from A to B will provide you with a completely useless piece of information because by Tuesday, that might not be the case any longer.

If B is not a constant mailbox address (meaning it's checking if it can send mail to an address that was input by a user on a web form, for example), then you shouldn't call it a "health check" because that's not at all what it is that you are trying to do. You are trying to determine if the user-input mailbox address is valid.

That's different.

It's also ill advised because you can't rely on the `RCPT TO` command to return an error code indicating that the mailbox doesn't exist even if it truly doesn't exist. The SMTP server may be configured to return `250 mailbox accepted` for every mailbox you provide and then turn around and send you a bounce message if the address doesn't exist.

This is why most websites if they ask you for an email address when you create an account, they will often send you an email and have you click a link in the body of said message to validate that your email address exists.
