### ISSUE TITLE
HighestModSeq Outlook

### ISSUE THREAD

**Issue by MauricioCodeguez** [jstedfast/MailKit#1081]
Is it possible to get the HighestModSeq using Outlook? If not, do I really need to go through all the emails in the folder to find which ones have some kind of change?

**Comment by jstedfast** [comment]
I'm not sure I understand your question. Outlook is an email client so I'm not sure how you'd even be able to get the HighestModSeq value from it as it probably won't show it to you (if it even supports it).

As far as MailKit goes, the whole point of mod-sequence values is so that you don't *have* to go through each message to see if it has a change or not because you can query changes since a particular mod-sequence version.
