### ISSUE TITLE
GnuPG Decrypted message seems to be empty, when it's supposed to have content in it.

### ISSUE THREAD

**Issue by EoflaOE** [jstedfast/MailKit#1087]
**Describe the bug**
I've implemented the GnuPG encrypt/decrypt mail sending/receiving functions to the mail client as part of my application. It seems that it sends encrypted mail to my account successfully, but whenever I try to get the body of the message using the WriteTo() method in the decrypted MimeEntity for body, it returns nothing in the buffer. However, when I looked at the [Text] property in the debugger, it returns the decrypted message, as expected.

ToString() also contains the decrypted message, but as it's discouraged to use ToString(), I would like to get the decrypted body using WriteTo(). When doing more research about the [Text] property, it came from directly casting MimeEntity to TextPart and then using the Text property, so `CType(DecryptedEntity, TextPart).Text` gave me the body.

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Runtime: .NET Framework
 - .NET Framework: .NET Framework 4.8
 - MailKit Version: 2.9.0

**To Reproduce**
1. Send an encrypted message to an account that you have imported its public and secret keys
2. Decrypt using the methods that I've written below
3. Using WriteTo(), you'll get nothing in the buffer.

**Expected behavior**
Using WriteTo() should return the decrypted body.

**Screenshots**
![image](https://user-images.githubusercontent.com/15963131/95578069-ec601480-0a3b-11eb-9930-9c2760872210.png)
![image](https://user-images.githubusercontent.com/15963131/95578260-44971680-0a3c-11eb-8886-d81b9ff7c1c7.png)

**Additional context**
Here's how I've decrypted the messages:
```vb
If Decrypt Then
    Dim DecryptedEntity As MimeEntity = DecryptMessage(Msg)
    Dim DecryptedStream As New MemoryStream
    DecryptedEntity.WriteTo(DecryptedStream, True)
    Dim DecryptedByte(DecryptedStream.Length) As Byte
    DecryptedStream.Read(DecryptedByte, 0, DecryptedStream.Length)
    W(Encoding.Default.GetString(DecryptedByte), True, ColTypes.HelpDef)
End If
```
Here's how I've implemented DecryptMessage(MimeMessage):
```vb
Public Function DecryptMessage(ByVal Text As MimeMessage) As MimeEntity
    If TypeOf Text.Body Is MultipartEncrypted Then
        Dim Encrypted = CType(Text.Body, MultipartEncrypted)
        Return Encrypted.Decrypt(New PGPContext)
    Else
        Return Text.Body
    End If
    Return Nothing
End Function
```

**Comment by jstedfast** [comment]
1. The reason that `DecryptedByte` is empty is because you didn't rewind the `DecryptedStream` before trying to read from it. In other words, the `DecryptedStream.Position` was at the end of the stream and then you tried to read `Length` bytes starting at the end of the stream (which means you'll read `0` bytes).
2. `DecryptedEntity.WriteTo()` where `contentOnly` is set to `true` is just not the right way to do what you want anyway. What if the `DecryptedEntity` is a multipart with attachments? What if it's base64 encoded? `contentOnly: true` won't decode it - all it does is strip away the leading headers - this API is really meant for use with HTTP PUT requests and other hacks like that.

You need to treat the decrypted entity as if it could be anything. It could even be another encrypted part.

I would recommend taking a look at the MimeVisitor class and my write-up on how messages are often structured: https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#MessageBody

I realize that you might just be writing a proof-of-concept right now and that the way you are handling things currently is just to get a feel for how things will work and that you'll flush out your logic later. I just want to make sure you understand that if you are going to handle real-world messages, your DecryptedEntity won't always be a simple TextPart that isn't encoded (either via base64 or quoted-printable).
