### ISSUE TITLE
InReplyTo does not differ if mail was forwarded/replied

### ISSUE THREAD

**Issue by danexis-szu** [jstedfast/MailKit#1096]
Problem:
- How can i find out if a mail was forwarded?

Currently i detect if a mail is a reply by checking String.IsNullOrEmpty(InReplyTo). This is also true, if the mail is not a reply but forwarded. How can i detect only replies? Do i need to apply Regex and check for own mail-address in the mail-text?

**Comment by jstedfast** [comment]
There's no simple way to check if a message is a reply or a forward.

Some mail clients set Resent-From/Resent-To/etc headers if they are forwarding a message, but often that is not done.

Many mail clients will prefix the Subject header with "Re:" if it is a reply and "FW:" or "FWD:" if it is a forwarded message. But again, this is not 100% reliable because it is not required (and on top of that, what if someone forwards a reply?).

If you have the message referenced by the In-Reply-To header (or in the References header - should be identical), you can try and use the From/To/Cc headers of each message to try and deduce if it looks like a reply.

Why do you care if a message is a reply or a forward?
