### ISSUE TITLE
mcr.microsoft.com/dotnet/aspnet:5.0-alpine3.12  An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by xiatiandegaga** [jstedfast/MailKit#1102]
**Describe the bug**
when run on aspnet:3.1.3-alpine3.11，it‘s correct，but run on aspnet:5.0-alpine3.12，An error occurred while attempting to establish an SSL or TLS connection，i doubt alpine3.12

**Platform (please complete the following information):**
 - OS: aspnet:5.0-alpine3.12
 - .NET Runtime: net-5.0
 - MailKit Version: 2.9.0

 using var client = new SmtpClient
            {
                ServerCertificateValidationCallback = (s, c, h, e) => true,
                CheckCertificateRevocation = false
            };
            await client.ConnectAsync(”smtp.exmail.qq.com“,465, SecureSocketOptions.Auto);
            await client.AuthenticateAsync(_configuration["Mail:userName"], _configuration["Mail:fromToken"]);
            await client.SendAsync(message);
            await client.DisconnectAsync(true);

**Comment by xiatiandegaga** [comment]
![微信图片_20201119153705](https://user-images.githubusercontent.com/47713355/99635575-2251d900-2a7d-11eb-98ff-a391d8f83d3e.png)

**Comment by xiatiandegaga** [comment]
i run on  aspnet:5.0-debian10 it‘s correct，so alpine3.12 is the reason

**Comment by jstedfast** [comment]
I can't help you if the problem is in the runtime.

**Comment by jstedfast** [comment]
There are realistically 2 possible causes of your problem:

1. The runtime is broken (maybe because it doesn't have the right version of OpenSSL installed or who knows what else it could be)
2. The Root certificates used to verify the authenticity of the certificates being used by whatever IMAP, POP3 or SMTP server you are trying to connect to are not installed on your system.
