### ISSUE TITLE
I'm unable to build from source using dotnet core 5 (on Ubuntu 20.04)

### ISSUE THREAD

**Issue by ctrager** [jstedfast/MailKit#1112]
This might be more of my beginner's mistake, more of a question, than a bug.
I cloned, fetched the submodules and then tried build. The only .NET stuff on my machine is the dotnet core sdk 5. I am able to *USE* Mailkit in one of my dotnet core 5 projects by doing "dotnet add package mailkit". It's so essential I thought it would be prudent to save a snapshot of it, try to build it. 

My output:
```
dotnet build MailKit.sln
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/corey/github/MailKit/UnitTests/UnitTests.csproj (in 28.54 sec).
  Restored /home/corey/github/MailKit/MailKit/MailKit.csproj (in 30.33 sec).
  Restored /home/corey/github/MailKit/submodules/MimeKit/MimeKit/MimeKit.csproj (in 30.33 sec).
/usr/share/dotnet/sdk/5.0.100/Microsoft.Common.CurrentVersion.targets(1180,5): error MSB3644: 
The reference assemblies for .NETFramework,Version=v4.5 were not found. 
To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. 
You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/corey/github/MailKit/submodules/MimeKit/Mono.Data.Sqlite/Mono.Data.Sqlite.csproj]
  MimeKit -> /home/corey/github/MailKit/submodules/MimeKit/MimeKit/bin/Debug/net46/MimeKit.dll
  MimeKit -> /home/corey/github/MailKit/submodules/MimeKit/MimeKit/bin/Debug/net45/MimeKit.dll
  MimeKit -> /home/corey/github/MailKit/submodules/MimeKit/MimeKit/bin/Debug/net47/MimeKit.dll
  MimeKit -> /home/corey/github/MailKit/submodules/MimeKit/MimeKit/bin/Debug/netstandard2.0/MimeKit.dll
  MimeKit -> /home/corey/github/MailKit/submodules/MimeKit/MimeKit/bin/Debug/net48/MimeKit.dll
```

**Comment by jstedfast** [comment]
You'll need the targetting packs for older versions of .NET that the multitargeted MailKit csproj file targets. Another option might be to edit the MailKit.csproj and change the <TargetFrameworks> value to be `net50` or something (or `netstandard2.0`?)

**Comment by ctrager** [comment]
I'm new to this environment. There are basic concepts I don't know: When in my dotnet core 5 project I do "dotnet add package mailkit", and that works fine, what is actually happening? Am I fetching mailkit source and building it locally, or am I fetching a prebuilt mailkit. And if prebuilt, did somebody other than you build it, and where is THAT project?

**Comment by ctrager** [comment]
Okay I can build. instead of 
```
dotnet build Mailkin.sln
```
I did
```
cd Mailkit
```
dotnet build
```
and it worked. 

With regards to me understanding how something that targets framework 4.8 can work with me and 5.0, I think it's related to specifying "netstandard2.0", according to my understanding of this: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by jstedfast** [comment]
> When in my dotnet core 5 project I do "dotnet add package mailkit", and that works fine, what is actually happening?

When you add a nuget package from nuget.org (or any other nuget package source), VS is essentially downloading a zip file that contains prebuilt assemblies for that library, unpacking the zip file and adding references to those prebuilt assemblies.

> And if prebuilt, did somebody other than you build it, and where is THAT project?

I built it and uploaded the package to nuget.org.

I've got all of the .NET frameworks and targeting packs installed so that I can build for any version of .NET and .NET Core.

If you've got VS 2019 installed, you probably have at least .NET 4.7.2, .NET 4.8 and .NET Core 3.1 (which means you can build for at least .netstandard2.0).

The .NET 4.x's are more-or-less all compatible, so if you can build for 4.8, you can pretty much build for 4.6 through 4.8. I think 4.5 was a different runtime version, that's why it probably failed.

Anyway, glad you got it building!

And yes, if you are targeting .NET 5.0, that'll use MailKit's netstandard2.0 build and not the net48 build.
