### ISSUE TITLE
Email received date is different in object received

### ISSUE THREAD

**Issue by atirnaveed** [jstedfast/MailKit#1113]
**Describe the bug**
Getting different datetime in the object on some of the emails but outlook showing it differently (please see the attachment)

**Platform (please complete the following information):**
 - OS: [Windows]
 - .NET Runtime: [CoreCLR]
 - .NET Framework: [.Net Core]
 - MailKit Version: 2.0.2

**To Reproduce**
Random emails.

**Expected behavior**
It should be same as email time.

**Screenshots**
![image](https://user-images.githubusercontent.com/17332223/101157592-4804e380-3622-11eb-94ae-68b0d1577e8b.png)
![image](https://user-images.githubusercontent.com/17332223/101157660-5f43d100-3622-11eb-8b97-cd0d0124a33f.png)

**Comment by jstedfast** [comment]
What are you comparing? The `Date:` header values? Or the `INTERNALDATE` value returned in the IMAP FETCH request?

They can be (and often are) different values and you need to make sure that you are comparing apples to apples. Outlook might be showing you the `INTERNALDATE` value while you are getting the `Date:` header value from MimeKit and thinking "there must be a bug because they don't match!"... except that they often don't match because they are timestamps for different things.

You also need to provide me with either the `Date:` header or the `INTERNALDATE` value (by using the [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) so that I can determine for myself if MimeKit/MailKit are incorrectly parsing a date.
