### ISSUE TITLE
Server and port autodetect

### ISSUE THREAD

**Issue by RomanSoloweow** [jstedfast/MailKit#1154]
We know servers and ports for many of the underlying providers: Gmail, iCloud, Yahoo, etc. It would be cool to autodetect the server by Email

**Comment by jstedfast** [comment]
Generally the way to do this is to do DNS lookups of MX records.

Since .NET doesn't provide a usable DNS client API to do this, I'd have to take a new dependency on some 3rd party .NET library to implement this feature which seems "heavy". If a DNS client was useful for more than this 1 feature, it might make sense to include in MailKit, but I don't really see it as valuable for anything other than that so I *think* it would make more sense to provide that functionality in a separate library.

**Comment by RomanSoloweow** [comment]
Can you tell me if there is such a library?

**Comment by jstedfast** [comment]
I'm not aware of one, but that doesn't mean there aren't (I've never bothered to look).
