### ISSUE TITLE
Question: SmtpClient.SendAsync - why doesn't return SmtpResponse?

### ISSUE THREAD

**Issue by kislovs** [jstedfast/MailKit#1161]
Currently, `SmtpClient` entity has [following method](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/AsyncSmtpClient.cs#L510):
```csharp
Task SendAsync(
      FormatOptions options,
      MimeMessage message,
      CancellationToken cancellationToken = default (CancellationToken),
      ITransferProgress progress = null
)
```

This method doesn't return low-level SMTP response. To actually process SMTP responses, I use `MessageSent` event. Usage of event handling to process SMTP responses required me to have some state, because I want to return response (after some processing) from my method.

I look for implementation of `SendAsync` method and found calling of [`DataAsync`](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L2154) method. It's the one method which [really works with SMTP response](https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L1978) (same for `BdatAsync`). And even if such method has SMTP response at the end, it doesn't return it. And if that method not return response, `SendAsync` can't return it as well.

So, my question is pretty straitght-forward: why don't `DataAsync` / `BdatAsync` (and therefore `SendAsync`) methods return `SmtpResponse`?

**Comment by jstedfast** [comment]
A few reasons:

1. The IMailTransport API is meant to be generic, so returning `Task<SmtpResponse>` wouldn't make a whole lot of sense.
2. SmtpResponse was an internal class until much more recently when I exposed it in order to expose the SendCommand/Async methods as `protected`.
3. When I first designed the API, there did not seem to be a valid reason to care about the SMTP response to the DATA command other than pass/fail (which exceptions can express to the caller).

The text after the return code of the DATA response is not defined by the SMTP protocol. It is considered free-form text.

What exactly do you expect to do with the SmtpResponse if you had access to it?

Also, an API that returns SmtpResponse would indicate, to me at least, that the method did not throw SmtpCommandExceptions (which it does). Because otherwise the only SmtpResponse you could ever get returned is the "success" response.

It would be a bad API, imho, to return SmtpResponse if the method throws exceptions on error.

**Comment by nitinag** [comment]
FWIW, we also use the `MessageSent` event to get a copy of the response from the server on `SendAsync` success for logging. Many receiving smtp servers provide useful diagnostic information such as a transaction/reference id, stats, and other information about the submission inside of the success (and error) free-form text response, which is useful to correlate in logs and to provide when troubleshooting with the receiving mail server's team. Thus, for our logic, we log the full reply code + message returned by the server on errors (via exceptions), and on success (via the `MessageSent` event). It'd be nice to get the response directly from `SendAsync` (on success only, since for errors it's provided with the exception) rather than using `MessageSent`, but we're able to get it that way currently.

**Comment by kislovs** [comment]
> What exactly do you expect to do with the SmtpResponse if you had access to it?

Same as @nitinag case. We use Postfix for message sending. On success Postfix return response like: `message queued as <postfix-queue-id>`. Pair of `host-name` (where `postfix` is running) + `postfix-queue-id` is unique. Also Postfix use that identifier for any further logs. So, we use that pair to filter logs for troubleshooting or if external team request that (for their side troubleshooting).

**Comment by kislovs** [comment]
> Also, an API that returns SmtpResponse would indicate, to me at least, that the method did not throw SmtpCommandExceptions (which it does). Because otherwise the only SmtpResponse you could ever get returned is the "success" response. It would be a bad API, imho, to return SmtpResponse if the method throws exceptions on error.

To be honest, I'm not sure how it should looks from API perspective, because one send message call transforms into set of SMTP commands internally. I just bring the case where response information is useful and the fact that currently it's not so easy to access that.

In our case we have to use `ConcurrentDictionary<string, TaskCompletionSource<string>>` as state, to wait inside our internal Send method untill we get that `postfix-queue-id`. With timeout / error handling logic code looks pretty tricky. And if we have `SmtpClient.SendAsync` method that return `SmtpResponse` (even only for success, exceptions is processing as well) - our code will be x10 simpler. :smile:

**Comment by nitinag** [comment]
Hi @jstedfast, since you're working on vnext, just wanted to make sure you've seen the rest of this thread in case you wanted to incorporate any changes related to this issue so that the smtp response is returned with the SendAsync method.

**Comment by jstedfast** [comment]
Yep, it's on my radar, but thanks for poking me about it.

**Comment by jstedfast** [comment]
I've been pushing pretty hard toward a v3.0. You can find the project board at https://github.com/jstedfast/MailKit/projects/1

I'm getting there...

**Comment by kislovs** [comment]
That's really nice to hear! Thanks  👍🏻

Will wait for v3.0 release, and already created ticket for update & refactor in our internal system :)

**Comment by jstedfast** [comment]
MailKit v3.0.0 has been released with this feature.
