### ISSUE TITLE
.MessageFlagsChanged not working as expected when mail was marked as 'Unread'

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1163]
I see these event args as I marked a mail in my IMAP INBOX folder as 'Unread'
`{MailKit.MessageFlagsChangedEventArgs}
    Flags: None
    Index: 266
    Keywords: Count = 0
    ModSeq: 539
    UniqueId: null
    UserFlags: Count = 0`
    
Unfortunately .UniqueId is not set which makes it impossible to find the matching mail in the local cache. Hence, I could not update the Read/Unread status of that mail in the local cache.

What am I missing?

**Comment by jstedfast** [comment]
In general, MessageFlagsChangedEventArgs will not have a UID because the IMAP protocol does not require it and most IMAP servers only send the sequence number of the message.

If you are in the process of doing a UID FETCH request, then the UID will be set.

You need to have a way of mapping the index of the message to a UID, unfortunately.
