### ISSUE TITLE
Need Information - How to force SMTP client to use higher TLS version (TLS1.2 or higher)

### ISSUE THREAD

**Issue by yogirp** [jstedfast/MailKit#1167]
MailKit: 1.18.0
.Net Core 2.1
SMTP: smtp.office365.com
Port: 587

I am using MailKit SMTP client to connect to SMTP.Office365.com server. The issue that I am facing is it connects with the SMTP server using TLS1.0. As TLS versions (TLS1.0, TLS1.1) are deprecated, the SMTP client should use the TLS1.2 or higher version.
I tried setting SSL protocols attribute before "connect" method as follows but it connects using the TLS1.0 only. It doesn't override the default supported protocols.

client.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;

I then upgraded the MailKit version to latest one "2.10.1" and it connects using the TLS1.2.

The issue here is I can't modify the code to upgrade the MailKit library now as the code is already deployed at customer location. 
How can I force SMTP client to connect using TLS1.2 (assuming MailKit 1.18.0 supports TLS1.2 version)? Also could anyone please answer who decides (SMTP server or client) which SSL protocol to use?

**Comment by jstedfast** [comment]
Different versions of the .NET runtime (and class libraries) support different versions of TLS.

The solution you came up with (setting the `client.SslProtocols` property to `Tls12`) should have theoretically worked if the target runtime supported it.

Since it is not working, I'm not sure what the cause could be (other than the runtime or class libraries not supporting it).

MailKit itself just passes the SslProtocols value to the underlying System.Net.Security.SslStream and doesn't do anything with it itself.

> Also could anyone please answer who decides (SMTP server or client) which SSL protocol to use?

This StackExchange question seems to answer this: https://security.stackexchange.com/questions/168390/how-is-the-tls-version-selected-between-client-and-server

What .NET Framework is your app build against? Do you know what runtime is being used to run your app?

When you upgraded to MailKit 2.10.1, did the runtime used change?

**Comment by yogirp** [comment]
@jstedfast Thank you for the information.
We have used .Net Core Runtime 2.1 to build and run the application.

> When you upgraded to MailKit 2.10.1, did the runtime used change?
No. Everything was same.
