### ISSUE TITLE
No account was found in the token cache having this login hint.

### ISSUE THREAD

**Issue by gowtham4gs** [jstedfast/MailKit#1169]
Hi,
An unhandled exception of type 'Microsoft.Identity.Client.MsalUiRequiredException' occurred in mscorlib.dll

Additional information: You are trying to acquire a token silently using a login hint. No account was found in the token cache having this login hint.

kindly help me out with the below parameters.
account ? 
CancellationToken?

**var authToken = await publicClientApplication.AcquireTokenSilent(scopes, account).ExecuteAsync(cancellationToken);**

Thanks

**Comment by jstedfast** [comment]
The error has nothing to do with the CancellationToken.

It's a problem with your account variable. Beyond that, I have no idea because you're asking for help with a library that I'm not really that familiar with.

You might try asking for help here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
