### ISSUE TITLE
SmtpClient.NoOp throwing an error “An established connection was aborted by the software in your host machine”, although IsConnected=true

### ISSUE THREAD

**Issue by JahangirSheikh** [jstedfast/MailKit#1196]
Hi,

We are using MailKit SmtpClient (ver: 2.11.1) from NuGet package manager. To keep the connections in the pool alive, we keep calling NoOp at every 2 minutes of interval. While mailing is working properly but the NoOp call throws the below mentioned errors intermittently. Have shared the code snippet too.

**Error messages encountered:** 
Error message 1: “Error: too many errors”, currently being observed roughly at intervals of 4-6 hrs.

Followed by this error in the very next KeepAlive call, that runs every 2 mins -
Error message 2: “An established connection was aborted by the software in your host machine”

**Keep alive method code snippet:**
![keepalivecodesnippet](https://user-images.githubusercontent.com/83006378/115706406-3c287c80-a38b-11eb-8d15-5fffd5c4e0de.JPG)

We have been looking into this issue but didn’t find any apparent reason for this error though NoOp is being called for the connected client only. It would really help if you could throw some light on it.

**Comment by jstedfast** [comment]
FWIW, it's generally best to include the type of exception as well rather than just the message because that can often provide helpful hints.

e.g.

`IOException: An established connection was aborted by the software in your host machine`

This would tell us that it is some sort of I/O error and *likely* thrown in a low-level API like `System.IO.Stream`.

And then, if you dive into the `InnerException`, you'd probably find that it was a `SocketException` that got wrapped by an `IOException` which means that it was some sort of TCP/IP socket error at the kernel level that bubbled up.

The `StackTrace` property of an exception is also valuable because it provides you with information about where exactly it was thrown. For example, it might reveal if it was thrown while writing to the socket or reading from it (or doing some other operation).

To get back to your question, though:

1. `Error: too many errors` - I have never seen this and without googling for this error string, I have no idea where it would be coming from. I can only imagine it is a socket-level error, but I don't really know. It seems odd.
2. `An established connection was aborted by the software in your host machine` - this is *definitely* a socket-level error that means that something terminated the TCP/IP network connection for some reason.

There is a question about this on StackOverflow: https://stackoverflow.com/questions/14304658/c-sharp-an-established-connection-was-aborted-by-the-software-in-your-host-machi

There's a lot of other discussions about this error message. Some seem to indicate that virus scanners, firewalls, etc can all contribute to the cause of this problem.

**Comment by JahangirSheikh** [comment]
Hi,

Appreciate your quick & detailed response.

Following are the error details that we missed sharing earlier. As you had mentioned, it was a “SocketException” wrapped up by “IOException” -

Error message 1: “Error: too many errors”, currently being observed roughly at intervals of 4-6 hrs.
```
Exception: SmtpCommandException
Message:  4.7.0 <Smtp Host Name> Error: too many errors
StackTrace: at MailKit.Net.Smtp.SmtpClient.<NoOpAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.NoOp(CancellationToken cancellationToken)
ErrorCode: UnexpectedStatusCode 
StatusCode: ServiceNotAvailable
```
Error message 2: “An established connection was aborted by the software in your host machine”
```
Exception: IOException
Message: An established connection was aborted by the software in your host machine 
StackTrace: at MailKit.Net.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MailKit.Net.Smtp.SmtpStream.<FlushAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpStream.Flush(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.<SendCommandAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.<NoOpAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.NoOp(CancellationToken cancellationToken)
InnerException: System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at MailKit.Net.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
ExceptionType: SocketException
```

To reiterate, we keep getting these errors on NoOp call (snippet below), that runs every 2 minutes for keepalive of active conns. The errors come up after an interval of 4-6 hours on the alive connections and leads to disconnection of SMTP client. We then have to connect it back again before using, so mail sending isn't facing any issues however the SMTP conn pool doesn't work as it's supposed to.

```
lock (smtpClient.SyncRoot)
{
       if (smtpClient.IsConnected)
       {
	        try
		{
			smtpClient.NoOp();
		}
		catch (SmtpCommandException scex)
		{                                    
		}
		catch (IOException ioex)
		{
		}
		catch (Exception ex)
		{                                  
		}

      }
}
```

We tried to figure out this problem by digging into more sources, but nothing concrete has come out of it as yet. Please do convey if you might require any further details from us.

**Comment by jstedfast** [comment]
The first exception is actually an `SmtpCommandException` which is not a TCP/IP `SocketException`:
```
Exception: SmtpCommandException
Message:  4.7.0 <Smtp Host Name> Error: too many errors
StackTrace: at MailKit.Net.Smtp.SmtpClient.<NoOpAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.NoOp(CancellationToken cancellationToken)
ErrorCode: UnexpectedStatusCode 
StatusCode: ServiceNotAvailable
```

The second exception, however, *is* an `IOException` caused by a lower-level `SocketException`.

So let's first start with the `SmtpCommandException` because most likely the `IOException`/`SocketException` is the result of a server dropping the connection after the `SmtpCommandException`.

What we can learn from the `SmtpCommandException` is that the server is responding with the `ServiceNotAvailable` status code (which aligns well with the assumption that the server is dropping the connection thereby causing the `SocketException`).

If you then search the web for SMTP error codes "smtp 421 4.7.0 too many errors", we discover that some SMTP servers will disconnect you after a "too many" NOOP commands. This is likely to free itself up for other incoming connections. In other words, it is attempting to prevent itself from getting tied up with clients that insist on keeping the connection open indefinitely.

My recommendation would be to change your pooling logic to keep the connection alive for only a few NOOP iterations. If you find yourself waiting more than, say, 10 minutes w/o sending a new email, then it's probably best to close the connection and re-connect later when you actually need to send a new message.

**Comment by JahangirSheikh** [comment]
Thanks for the support. we made the recommended changes in our pooling logic and it's working fine now.

**Comment by jstedfast** [comment]
@JahangirSheikh awesome, I'm glad I was able to help!
