### ISSUE TITLE
TLS versions supported

### ISSUE THREAD

**Issue by Liviu-Ionel-Anton** [jstedfast/MailKit#1202]
I have an application using MailKit version 0.15.0 and MimeKit version 0.36.0. How can I find out which TLS versions are supported by these libraries?

Thanks in advance!

**Comment by jstedfast** [comment]
They support whatever versions of SSL/TLS that are supported by your version of the .NET class libs/runtime.

For example, if you are using .NET 4.5, it looks like TLS <= v1.2 is supported: https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.5 but if you are using .NET 4.0, then only TLS <= v1.0 is supported: https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.0

In order to support TLS v1.3, you would need to use .NET 4.8, .NET 5.0, or .NET Core 3.0+

All that said... why are you using MimeKit 0.15 and MailKit 0.36? Those versions are ancient. Even if you need to stick with .NET 4.0, you should at least upgrade to something like MimeKit/MailKit 1.22.0

**Comment by Liviu-Ionel-Anton** [comment]
Thank you for your fast answer!

The reason for using these ancient libraries: I've currently inherit this application and also the question regarding TLS.
I'll update it the the near future to use the latest libraries and also .NET framework.

**Comment by jstedfast** [comment]
That will depend on the TargetFramework/TargetFrameworkVersion values in the *.csproj file.

**Comment by Liviu-Ionel-Anton** [comment]
Than it's for sure TLS 1.0.
I have to update the app to 4.8 and library to the latest supported.
Thanks a lot!
