### ISSUE TITLE
SSL or TLS connection issue after upgrading MailKit library

### ISSUE THREAD

**Issue by yogirp** [jstedfast/MailKit#1207]
We have upgraded MailKit  library from version 1.18.0 to 2.10.1 and made the necessary changes. 
After upgrading we are getting below error message which otherwise working fine for v1.18.0.

_"Something went wrong while sending Mail. An error occurred while attempting to establish an SSL or TLS connection.
The host name did not match the name given in the server's SSL certificate."_

```
using (var client = new SmtpClient ()) {
        client.Connect ("smtp.xxxxx.org", 25, false);

    // ...
}

```
No other code change but just upgrade to v2.10.1 and started getting the above issue.
Any help would be appreciated.

**Comment by jstedfast** [comment]
You'll need to provide a ServerCertificateValidationCallback to handle this.

As the error message mentions, the host name does not match the name in the SSL certificate and so System.Security's SslStream is throwing an error.

In older versions of MailKit, MailKit overwrote this behavior to try and get around a lot of the common issues that mail devs hit (like this one) with the expectation that anyone serious about security would provide their own ServerCertificateValidationCallback method to provide a more secure default than MailKit's default.

These days, MailKit had-codes the server certificate details for a handful of common mail servers (like gmail, office365, yahoo, etc) but does not attempt to override other errors that are thrown by SslStream.

Check out item 2 in https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException (it's the section titled "2. The mail server that you are connecting to is using an expired (or otherwise untrusted) SSL certificate.").
