### ISSUE TITLE
Limitation for connection when sync email 

### ISSUE THREAD

**Issue by suphamba2401** [jstedfast/MailKit#1229]
**Describe the bug**
When I synced email from mail server and got the problem with connection.
Let's say I head around 1000 email folder and after that i got a lot of error related to connection. It seems like that one is a limitionation of mailkit, pls investigate and could you tell me how many email folder that mailkit can work fine?
Thanks!

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
 - .NET Runtime: [e.g. CoreCLR, Mono]
 - .NET Framework: [e.g. .Net Core, .NET 4.5, UWP, etc.]
 - MailKit Version: 

**Exception**
If you got an exception, please include the exception Message *and* StackTrace.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

```csharp
// log to a file called 'imap.log'
var client = new ImapClient (new ProtocolLogger ("imap.log"));
```

```csharp
// log to a file called 'pop3.log'
var client = new Pop3Client (new ProtocolLogger ("pop3.log"));
```

```csharp
// log to a file called 'smtp.log'
var client = new SmtpClient (new ProtocolLogger ("smtp.log"));
```

Note: if the protocol log contains sensitive information, feel free to email it to me at
jestedfa@microsoft.com instead of including it in the GitHub issue.

**Additional context**

**Comment by jstedfast** [comment]
Seems more like a server issue. MailKit does not have any limitation with the number of folders.

Post your code and try getting some protocol logs and maybe I can help you diagnose any issues.

**Comment by jstedfast** [comment]
Are you using ImapClient.GetFolders()?

When you use ImapClient.GetFolders(), it will list ALL folders and if you have tons of folders, that could cause the IMAP server to drop the connection (which is what it sounds like is happening to you).

This problem is made even worse with IMAP servers such as UW.IMAPd if some folders are symlinks that link back to other folders within the same folder structure because it creates an infinite loop of folders.

The way to get around this is to get 1 level of folders at a time like this:

var toplevel = client.GetFolder (client.PersonalNamespaces[0]);
var firstLevel = toplevel.GetSubfolders (...);
foreach (var folder in firstLevel) {
    var secondLevel = folder.GetSubfolders (...);
}

And just recursively list the folders like that as far as you want to go.

If you aren't using ImapClient.GetFolders() or need further assistance, let me know.
