### ISSUE TITLE
Sender Address and Sender Alias

### ISSUE THREAD

**Issue by CSharpSeraph** [jstedfast/MailKit#1237]
Hi, 

I am sure I'm doing something wrong but I don't know what. As far as I know, the "From" header is the alias whereas the "Sender" is the email address. 

I have tried some different things but these two lines seem to be the most correct: 

                message.Headers.Add(new MimeKit.Header( MimeKit.HeaderId.From, FromAlias));
                message.Headers.Add(new MimeKit.Header(MimeKit.HeaderId.Sender, FromAddress));

Anyway, every time I get an "unknown address" or I simply see the email address when I check the recipient's email. I can't find a way to make the alias show. 

Thank you in advance!

**Comment by jstedfast** [comment]
I'm not sure what you mean by "alias", but let me try to explain the difference between the Sender header and the From header.

The Sender header is meant to be the email name & address of the person who physically typed the message and hit "Send".

The From header can actually be a group of names & addresses of the people (plural) who the message is "from".

This was deemed as important back in the early days of email because often secretaries would type and send a message on behalf of their boss or on behalf of, say, some shareholders.

These days, the From header is assumed by most email software to be 1 name & address and it is assumed to be identical to the Sender and so the Sender header is often unused.

The email specifications specify that if the Sender header is missing, then the From header should only have 1 address and that address should be the person who is sending the message.

I think that it is extremely rare to find a From header with multiple addresses in it and this feature was not very widely used even back in the early days of email, but it's there to allow the possibility.

Realistically, you should probably not be setting a Sender header and instead just setting the From header.

Does that help?

**Comment by CSharpSeraph** [comment]
It helps a lot sir, thank you so much. I have tried now setting only the From header with this syntax

 message.Headers.Add(new MimeKit.Header( MimeKit.HeaderId.From, "\"" + FromAlias + "\" <" + FromAddress + ">"));

in order to get something like that: 

"Verbose FirstName & LastName - HR Office" <my.address@server.com>

but still the recipient (in this case he's using a Zimbra webmail client) still sees "Unknown" in his List View, instead of "Verbose FirstName & LastName - HR Office", please let me know if I didn't explain  well.

thank you again!

**Comment by CSharpSeraph** [comment]
I see the html parser here has hidden my "major" and "minor" tags and so on, but I'm sure you got my point

**Comment by CSharpSeraph** [comment]
Just to explain a little more what I mean with "Alias", here's an example using the (less rich than yours) System.Net.Mail: 

mail.From = new MailAddress(FromAddress, FromAlias);

where "Alias" is the display name. And the way they do it (I don't know the black magic behind it) works just right.

**Comment by jstedfast** [comment]
GitHub's textboxes parse what they call "markdown" and not html.

As a quick & dirty guide to the syntax:

If you want bold, you can use \*\*bold\*\*
If you want italics, you can use \*italics\*
If you want to make a link, you can do: \[title\]\(http://www.link.com) (or you can just paste the raw http link and it will linkify the url for you)
To escape a \<, you can put a backslash (\\) in front of it

**Comment by jstedfast** [comment]
Okay, now I know what you mean by "alias". What you want to do is this:

```csharp
message.From.Add (new MailboxAddress (FromAlias, FromAddress));
```

(it's backwards compared to MailAddress from System.Net.Mail)

**Comment by CSharpSeraph** [comment]
Perfect! you're great. Thanks a lot.
