### ISSUE TITLE
Mailkit TLS/SSL in aspnet:5.0 docker fails with '[PartialChain]: unable to get local issuer certificate'

### ISSUE THREAD

**Issue by Nightreaver** [jstedfast/MailKit#1243]
**Describe the bug**
We are running an app that was ported from windows service to a docker container.
With the windows service running, everything is working well. After we moved the app to latest `mcr.microsoft.com/dotnet/aspnet:5.0-focal` or `mcr.microsoft.com/dotnet/aspnet:5.0` the service cannot connect to smtp server when using socketOptions `starttls` or `ssl` on the corresponding ports.

When I check the certificate with openssl from inside the container, the certification is valig for both ports (25/starttls or 465/ssl)
Oeerall, the services work well except when running inside the container.

The question is, how can I make Mailkit to accept the proper SSL Certs that are store in the linux/debian docker images?

I have found this https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#x509-certificates but it doesnt tell me anything how to use it with mailkit.

**Platform (please complete the following information):**
 - Microsoft Docker Image `aspnet:5.0` or `aspnet:5.0-focal`
 - .NET core 5
 - `Include="MailKit" Version="2.10.1"`

**Exception**
`[PartialChain]: unable to get local issuer certificate`

**To Reproduce**
1. Create simple mailkit app
2. move it over to aspnet docker container
3. connect to smtp with mailkit via `starttls` or `ssl`

**Expected behavior**
Mailkit should use the linux certificate store where all offical ROOT CA's are stored as verified with ie `openssl s_client -connect smtp.mailserver.XX:465`
As a note, we use a payed certificate for our webserver that is valid, not expired and has not CLR issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/3270156/129612960-509ca8db-6073-44c1-bcbe-eec2dce61fcc.png)
Was the first notice, after checking deeper into the `RemoteCertificateValidationCallback` we got the certificate response.

openssl output:
```
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = AlphaSSL CA - SHA256 - G2
verify return:1
depth=0 CN = *.mailserver.XX
verify return:1
```

**Additional context**
I've checked the URL in the notice, but it doesnt mention anything about "partial chain" or "ssl cert stores"

Any idea how to implement the proper certificate store for Mailkit? I've been browsing the web for hours and can find the certificate-store only related to self-signed certificates or aspnet https servers

**Comment by jstedfast** [comment]
MailKit doesn't have any logic for storing or retrieving X509 SSL certificates from anywhere on the hard-drive. This is expected to be handled by the System.Security's SslStream implementation which is supposed to do that.

On Linux, as you probably know, SslStream uses OpenSSL under the hood so I'm not sure why it isn't finding OpenSSL's certificate store.

This would be an issue you would need to take up with the dotnet core team.

That being said, what you can do is to implement a custom ServerCertificateValidationCallback function and maybe you can do some callouts to openssl or something to validate the certificate.

Another option (and maybe better?) is explained here: https://stackoverflow.com/a/57466119/87117

Apparently you might need to add the full chain of certs to the cacert.pem file on your mail server so that it can send the full chain of certificates to the client when it connects via SSL/TLS.
