### ISSUE TITLE
MailFolder.FetchAsync no longer working. 

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1258]
Hi,

Sorry for not being more specific. This is a customer's email account which was working no problem and suddenly stopped working. I'm not aware of any changes on my end which might have caused the issue.

Here is how I'm fetching UniqueIds since months no problem:
```cs
foreach (UniqueId uniqueId in((ulong) MailAccount.HighestModSeq > 0
    ? await MailFolder.FetchAsync(0, -1, (ulong) MailAccount.HighestModSeq, MessageSummaryItems.UniqueId, cts.Token)
    : await MailFolder.FetchAsync(0, -1, MessageSummaryItems.UniqueId, cts.Token)).Select(m => m.UniqueId))
{
```

... which now throws this exception:

MailKit.Net.Imap.ImapCommandException
  HResult=0x80131500
  Message=The IMAP server replied to the 'FETCH' command with a 'BAD' response: Error in IMAP command FETCH: Invalid messageset (0.001 + 0.000 secs).
  Source=MailKit
  StackTrace:
   at MailKit.Net.Imap.ImapFolder.<FetchAsync>d__233.MoveNext()

Here is the trace file:
[trace.zip](https://github.com/jstedfast/MailKit/files/7162437/trace.zip)

Would you have any idea what's going wrong?

**Comment by jstedfast** [comment]
The problem seems to be that the folder has no messages in it (e.g. MailFolder.Count will return 0). I could add logic to MailKit to check that and, if Count == 0, return `Array.Empty<IMessageSummary>()`, but you can also do a manual check in the meantime.

I could have sworn I already had code to do that... I'll have to check.

**Comment by DierkDroth** [comment]
@jstedfast excellent! That resolved the issue. Thanks
