### ISSUE TITLE
MimePart.Content.Open() stream length

### ISSUE THREAD

**Issue by Budsy** [jstedfast/MailKit#1291]
**Describe the bug**
I don't think this is a bug really, maybe just a feature. It is simply that I have found that the Length property of the MimePart.Content stream is not representative of the actual bytes count that may be read in.  

**Platform (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS, iOS, Android, Windows Phone, etc.]
 - .NET Framework: .NET 6
 - MailKit Version: 2.15.0

**Code Snippets**

I have found that the stream read lengths are limited to around 4075 bytes. To prevent issues when the buffer is written, formed into a string, and parsed as XML, I need to pad the buffer with space characters. Actually, I just prime the read buffer with spaces. Here's my solution. The question is, is the .Length property of the stream guaranteed to be bigger than the total bytes read? I don't want to have a buffer overrun.

```csharp
using Stream stream = ((MimePart)xmlEntity).Content.Open();
        int len = (int) ((IMimeContent) ((MimePart) xmlEntity).Content).Stream.Length;
        byte[] buffer = new byte[len];
        for (int i=0; i<buffer.Length; i++)
        {
            buffer[i] = 32;
        }
        int offset = 0;
        int bytesRead = 0;
        do
        {
           bytesRead =  await stream.ReadAsync(buffer, offset, len).ConfigureAwait(false);
           offset += bytesRead;
           len -= bytesRead;
        } while (bytesRead > 0);
        string xml = System.Text.Encoding.UTF8.GetString(buffer);
```

**Comment by jstedfast** [comment]
Let me try to explain how this all works.

When the MimeParser parses the message (either via MimeMessage.Load() or MimeParser.ParseMessage()), it constructs a [MimeContent](http://www.mimekit.net/docs/html/T_MimeKit_MimeContent.htm) which gets set as the MimeParser.Content property.

This raw stream created by the MimeParser is not decoded. If the MIME content that was fed to the parser was base64 encoded, for example, then the raw MimeContent.Stream is that encoded data.

The `MimeContent.Stream` property is never meant to be used directly (at least not for data retrieval) precisely for this reason.

Instead, the System.IO.Stream you get a reference to from the MimeContent.Open() method is all you should be using because that will decode the content as you read it from the returned Stream. The other option is to use MimeContent.DecodeTo(). Either works.

> The question is, is the .Length property of the stream guaranteed to be bigger than the total bytes read? I don't want to have a buffer overrun.

You are using the .Length property incorrectly. The Open() method does not return the MimeContent.Stream and so using the MimeContent.Stream.Length is not going to give you the correct length for the *decoded* content.

This is why your current code needs to fill your buffer with spaces.

Change your code to this:

```csharp
using MemoryStream memory = new MemoryStream();
((MimePart)xmlEntity).Content.DecodeToAsync(memory).ConfigureAwait(false);
byte[] buffer = memory.GetBuffer();
int length = (int)memory.Length;
string xml = System.Text.Encoding.UTF8.GetString(buffer, 0, length);
```

**Comment by Budsy** [comment]
Jeffrey,

 

Thank you very much for your explanation and for setting me straight on my code. I had it working, but it sure did smell funny.

 

Bob Dickow (Budsy)
