### ISSUE TITLE
dont see MessageSummaryItems.Annotations

### ISSUE THREAD

**Issue by eugenestepanyuk** [jstedfast/MailKit#1295]
I use MailKit v. 1.22, it has the ability to use MessageSummaryItems.Annotations? If not, how can I get attachments from the messages, my code:

```
var query = SearchQuery.All;
var uids = inbox.Search(query);
var items = inbox.Fetch(uids, MessageSummaryItems.Full).Reverse();
foreach (var item in items)
{
    foreach (var attachment in item.Attachments)
    {
        //exits the loop because it does not see attachments
    }
}
```

**Comment by jstedfast** [comment]
In order to get the attachments, you need to use `MessageSummaryItems.BodyStructure`

FWIW, I've tried to add a statement to every MessageSummary (and IMessageSUmmary) property that denotes which MessageSummaryItems enum value needs to be included in order to populate the IMessageSummary/MessageSummary property.

For example, if you look at http://www.mimekit.net/docs/html/P_MailKit_MessageSummary_Attachments.htm - you'll notice that it says, "This property will only be usable if the BodyStructure flag is passed to one of the Fetch or FetchAsync methods."

Hope that helps.
