### ISSUE TITLE
Looking for examples to send SMTP emails from an account that will not be monitored, to management

### ISSUE THREAD

**Issue by rfalanga** [jstedfast/MailKit#1315]
**Question**
I'm trying to use MailKit in a new application I'm writing at work. I must use .NET Framework 4.6.2. This is for an internal app where emails will be sent to other employees. The intent is to send them anonymously, so the sender isn't identified to the recipient. The recipients are upper management. (They'll receive emails from employees who wish to remain anonymous, so they can ask management questions.)

The problem is my lack of experience with SMTP. I was trying to use the SmtpClient that comes with .NET Framework but ran into issues when I tried to use .NET 4.6.2. MailKit was recommended as a better alternative. In my testing I could make it work fine, but that is when I used my own work email address and password. Something I do _not_ want to do in the app. I'm sure there are ways of doing this. I've spoken with people in Operations and an Exchange Server administrator. He said I should use SMTP Relay. I've been looking for examples of how to send an email using MailKit to a distribution list using I think a new email address for this purpose (I've yet to get it) in such a way that I don't need to provide a password. I just can't find any examples. I searched on Stack Overflow without success.

So, I'm asking for help by being pointed to some examples to do what I'm trying to do.

**Platform (please complete the following information):**
 - OS: Windows. I think it is Windows Server 2016
 - .NET Runtime: .NET 4.6.2
 - .NET Framework: .NET Framework 4.6.2
 - MailKit Version: (whatever version it is that comes from Nuget)

**Exception**
(No exception)

**To Reproduce**
(not relevant)

**Expected behavior**
I would like some examples showing me how to send emails from an account that I don't have to log into, to people within the company

**Code Snippets**
If applicable, add code snippets to help explain your problem.
N/A

**Protocol Logs**
Please include a protocol log (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.

To get a protocol log, follow one of the following code snippets:

**Additional context**

**Comment by jstedfast** [comment]
You're not really asking a code question, you're asking SMTP server configuration question(s) which I can't really help with.

If your Admins can provide you with an SMTP server/port where you don't need to authenticate in order to send mail, then you would just avoid the use of the `Authenticate()` method (the `Authenticate()` method is optional for MailKit's SmtpClient):

```csharp
using (var client = new SmtpClient ()) {
    client.Connect ("internal.smtp-relay.mycompany.com", 587, SecureSocketOptions.StartTls);
    client.Send (message);
    client.Disconnect (true);
}
```

Was that your question?

**Comment by jstedfast** [comment]
I'd mention that most likely, you'll want your Admins to also create a dummy email account for your app to use (e.g. `mgmt-questions@mycompany.com`) so that you have a valid sender address which will be needed to use for the SMTP `MAIL FROM` command as well as a valid address to put in the MIME message's `From:` header.

Once you have that email account, there's really no point in avoiding authentication because now your app would have a way to authenticate using said account information.

**Comment by rfalanga** [comment]
@jstedfast I have requested the Admins to issue a distribution list to which the application I've written can send email messages to management anonymously. Waiting for that request to be fulfilled.

So far, I've been unsuccessful in getting from the Admins an email address from which I can send the SMTP messages from, as you've described. They seem to think that it is possible to send an email from an account that is either invalid or doesn't exist. They tell me, "Just use SMTP Relay", as if that explains it all. I am ignorant enough of SMTP and especially SmtpClient, whether it's from .NET Framework's System.Net.Mail or MailKit to not understand what they're talking about. I conclude that what they're saying I should do is just specify the To email distribution list, the subject line and body of the email, then call Send.

**Comment by jstedfast** [comment]
> I conclude that what they're saying I should do is just specify the To email distribution list, the subject line and body of the email, then call Send.

You need to specify a sending mailbox address, whether you put it in the `From:` header of the message or just use the [SmtpClient.Send (MimeMessage message, MailboxAddress sender, IEnumerable<MailboxAddress> recipients, CancellationToken cancellationToken)](http://www.mimekit.net/docs/html/M_MailKit_MailTransport_SendAsync_2.htm) method.

You *might* be able to get away with using a sending mailbox address that doesn't actually exist, but that depends on the configuration of the SMTP server and whether it will allow it or not.

Let me clarify some things:

1. MailKit's `SmtpClient.Send(MimeMessage, CancellationToken)` method will attempt to extract the sender/recipient addresses from the `Sender:`/`From:`/`To:`/`Cc:`/`Bcc:` headers and use those addresses in the appropriate `MAIL FROM` and `RCPT TO` SMTP commands.
2. The Send() method I linked to in the docs above that takes a sender and recipients essentially overrides the default Send() method's logic for figuring out who to send *from* and who to send *to*. The sender and recipients specified do *not* need to match. For example, in the `MimeMessage.From` property, I can specify `joe@sixpack.org`, but I can use `bob@spoofer.net` as the `sender` argument in the `Send()` method and the SMTP server.

**Comment by rfalanga** [comment]
Thank you. I'm going to have to wait until tomorrow before I get more clarifications from the Admins what and how they intend me to utilize the SMTP server.

**Comment by jstedfast** [comment]
FWIW, if you decide to end up using the Send() method that takes a sender and list of recipients (in addition to the message), you *could* set the `From` property of the message to `undisclosed-sender:;` (aka an empty rfc822 group address):

```csharp
var message = new MimeMessage ();
message.From.Add (new GroupAddress ("undisclosed-sender"));
```

Strictly speaking, in the real world if you set the From address to something like that, you're *supposed* to set the `Sender:` header to a valid email address that is the one used to actually send the message, but since this is internal, it'll be fine.

I would also recommend setting the `MimeMessage.ReplyTo` property to the distribution list so that your managers can reply to the message and have it go to your distribution list.

**Comment by rfalanga** [comment]
Interesting. I did not know about the `undisclosed-sender`. But I won't have to use it. I was given an email address to use for sending from which doesn't have a mailbox. I've got the host name, port and am specifying `SecureSocketOptions.StartTls` in the Connect call. Now I'm just waiting for a DNS record to be created to associate with the web app.
