### ISSUE TITLE
Idle example might miss some messages

### ISSUE THREAD

**Issue by vkovalcik** [jstedfast/MailKit#1362]
**Describe the bug**
There were some missing e-mail notifications, so I was trying to analyze the code and the idle mail example checks periodically for new and deleted messages an updates its own "previous state" to compare with in the future. However, there is an issue when the client is unexpectedly disconnected (you put computer into sleep or there is a connection error) in this scenario:
- it now remembers the last message count (ex: 15)
- you may delete some message on another device in the meantime (ex: 3 delete, so there are 12 messages)
- when the connection is on again the client doesn't update its message count (so it still thinks there are 15 messages)
- when new message arrives it compares the message count and if it is lower, only then will fire the new message event (but it won't since 12+1 < 15)

I guess in WaitForNewMessagesAsync() after "await ReconnectAsync();" it needs something like "await FetchMessageSummariesAsync();" and some other code adjustments.

**Platform (please complete the following information):**
 - MailKit Version: 3.2.0

**Comment by jstedfast** [comment]
Yes, I left a lot of logic out with the assumption that the system wouldn't be suspended or have network connection problems in order to keep the sample as small as possible. Even so, I've had people get upset with me that even this sample was way too complicated.

The proper thing to do would be to resynchronize the folder (especially after a disconnect) which requires maintaining a cache based on UIDs.

As it so happens, one of the other currently open issues is asking how to do that. You might want to watch that for more info when I get around to it.

**Comment by vkovalcik** [comment]
I see, thank you for very fast reply! And yes, I am trying to implement something like the UID cache too, but I have changed the underlying code, so now it is not easy to use in the original example. (Also, I seem to have introduced some new bugs, which I didn't resolve yet :) )
