### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [jstedfast/MailKit#1411]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266 

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3 

Thanks in advance.

**Comment by jstedfast** [comment]
I can't implement add support for this until System.Security implements [ChannelBindingKind.TlsExporter](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.extendedprotection.channelbindingkind?view=net-6.0)

Note in that link there is no support even in net6.0.

**Comment by jstedfast** [comment]
Based on [discussion for dotnet](https://github.com/dotnet/runtime/issues/73118), it won't be supported until at least .NET 8.0, so we're a few years away from that.

**Comment by bgenidy** [comment]
@jstedfast wondering if this can be brought under consideration again now that .net officially supports TLS 1.3

**Comment by jstedfast** [comment]
Doesn't look like it's there to me: https://learn.microsoft.com/en-us/dotnet/api/system.security.authentication.extendedprotection.channelbindingkind?view=net-8.0

I think I do recall seeing underlying support for it was added, but the necessary API to actually use it from the application-layer is not there.

**Comment by jstedfast** [comment]
Just verified using MailKit net8.0 project that ChannelBindingKind still only supports Unique, EndPoint, and Unknown.

**Comment by jstedfast** [comment]
Looks like they are considering adding TlsExport for net9.0 depending on whether or not schannel provides an API for them to use. In other words, it's still not supported.

https://github.com/dotnet/runtime/issues/73118#issuecomment-1869886046

**Comment by Neustradamus** [comment]
@jstedfast: Can you done a comment too?

**Comment by Neustradamus** [comment]
@jstedfast: Can you publish a comment on this specified ticket?

**Comment by jstedfast** [comment]
@Neustradamus if you can provide me with a compelling reason to care about implementing this feature, sure.

So far, it seems like no one has even bothered to use the previous generations of this protocol/authentication mechanism so I'm a bit skeptical that anyone *really* cares about this latest version when they clearly didn't care about or use the previous ones.

It seems this tactic of begging everyone (from jabber clients to sql servers to mail servers to mail clients) to all implement this functionality that you are hoping to solve the world's security issues through the idea of thinking "if only everyone implemented this latest crypto protocol", but then we all waste a ton of time chasing a dead end.

I see more servers that support DIGEST-MD5 than I do SCRAM-SHA-*anything*, never mind the -PLUS variants that support SSL channel bindings.

Just because an IETF spec exists doesn't mean anyone actually bothers to implement it.

What I need from you is a list of mail servers that support this feature. Without that list, it's pointless to waste more of my time on this.

**Comment by Neustradamus** [comment]
@jstedfast: SCRAM-SHA-1, SCRAM-SHA-1-PLUS, SCRAM-SHA-256, SCRAM-SHA-256-PLUS have been added in GNU SASL by @jas4711, the author of your latest link.

You can see a lot of information about SCRAM and Channel Binding and a list of supported projects:
- https://github.com/scram-sasl/info/issues/1

Old and unsecure mechanisms like CRAM-MD5 and DIGEST-MD5 have been removed from Cyrus SASL and Cyrus IMAP in master code.

You can see that Cyrus SASL/IMAP, Dovecot, Exim support SCRAM-SHA-*-PLUS and several other softwares, look the uncomplete list.

**Comment by bgenidy** [comment]
@jstedfast yes sure. I think the following NIST mandate is helping drive a lot of adoption and we are seeing that adoption has signficantly increased in the last 3 month.

Ref: https://www.packetmania.net/en/2023/08/21/TLS1-3-intro/#nist-mandate

**Comment by jstedfast** [comment]
@bgenidy The NIST link only refers to TLS v1.3 which MailKit already supports. There's no mention of channel bindings in that link at all.

**Comment by bgenidy** [comment]
@jstedfast thanks for clarifying, much appreciated! I read the shared RFC along with prototyped a connection to TLS 1.3 and confirmed its working as expected.
