### ISSUE TITLE
Constructor of ImapFolderConstructorArgs is not correct described in the documentation.

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1429]
I'm trying to use `ImapFolder`. To do this, I have to create use `ImapFolderConstrutorArgs`, if I'm right.

In the documentation, I can't find how to use the constructor of it. In the [documentation](http://www.mimekit.net/docs/html/T_MailKit_Net_Imap_ImapFolderConstructorArgs.htm), I can't find the needed parameter to create a new instance of it.

If I decompile it in VS2022, I have to use a `ImapEngine` object. But this is completely described in your documentation.

Ok, I understood: You are ignorant and not interested to improve your documentation. Maybe the right point not to go ahead using MailKit. So if you don't change your way of answering my bug reports, I will no longer report that one, I found.

**Comment by jstedfast** [comment]
That's because the `ImapFolderConstrutorArgs` .ctor is internal to MailKit. You do not need to instantiate any `ImapFolderConstrutorArgs`. You also are not meant to instantiate your own ImapFolder instances, either.

`ImapFolderConstrutorArgs` exists ONLY so that you can subclass ImapFolder and override [ImapClient.CreateImapFolder(ImapFolderConstrutorArgs)](http://www.mimekit.net/docs/html/M_MailKit_Net_Imap_ImapClient_CreateImapFolder.htm)

> So if you don't change your way of answering my bug reports, I will no longer report that one, I found.

You haven't found any bugs. All you've done is illustrate your own ignorance and inability to apply critical thinking.

**Comment by jstedfast** [comment]
You should be asking yourself an obvious question:

Why are YOU the ONLY person who can't figure this stuff out?

MailKit has 50 MILLION downloads on nuget.org *alone* and not one person has been unable to figure this out until you came along.

Think about that before you call *me* "ignorant".
