### ISSUE TITLE
How long is an Index valid in a ImapClient connection?

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1433]
I'm trying to use IDLE notifications with the following code:

```
imapClient.Idle(new CancellationTokenSource(new TimeSpan(0, 29, 0)).Token, _idleCancelSource.Token);

mailFolder.MessageFlagsChanged -= FolderMessageFlags_ChangedEvent;

```

I receive notifications, if the "seen" ("read") flag has been changed. But I get only the `Index`, but not the `UniqueId`.

Is this a further bug of my mail server?

How long can I use the `Index`, until it's invalid? I ask, since I'm developing an app with multiple simultaneous `ImapClient` connections. So is `Index` valid between the different connection?

**Comment by jstedfast** [comment]
> I receive notifications, if the "seen" ("read") flag has been changed. But I get only the Index, but not the UniqueId.
> Is this a further bug of my mail server?

That's expected, so not a bug in your IMAP server.

The index is valid until any client connects to the IMAP server and deletes a message with an index lower than (or equal to) the index you have.

In other words, if you are notified that message 100's flags just changed, then that index will point to the correct message until your client or any other client deletes/expunges a message with an index <= 100.

> So is Index valid between the different connection?

Depends on what happens between sessions. The messages in an IMAP folder will never be re-ordered by the server, so if your client is the *only* client that ever connects to that server/account, then yes, the index will be the same between sessions. But if there are any other clients, especially ones that you do not control, you best not assume you can rely on that index for very long. The very next IMAP command sent to the server by any client that is connected could cause that index to point to a different message.

The way you are expected to deal with this situation is to have a locally cached mapping of indexes to messages and just update the flags in your local cache based on the index at that exact moment in time. It sucks, but it is what it is.

My recommendation is that when you receive a MessageFlagsChanged event, your event handler should immediately update your local cache with those flag changes.

When you get a MessageFlagsChanged event, the event args will always contain the `Index` and the new `Flags` & `Keywords`. Those are the only properties that you can depend on being set but they are also all you need (technically).

I should note that if you subscribe to the MessageExpunged event, you'll get notified when a message is removed from the folder (as long as you remain connected to the IMAP server and that folder is the one selected) which will tell you the index of any message that gets removed.

So for example, if we go back to that message index 100 example, if you next get a MessageExpunged event with an index of 50, then it means you'll need to use index 99 instead of index 100 to refer to the message that received the MessageFlagsChanged event.

Hope that helps clarify things.

**Comment by NilsHoyer** [comment]
So, if I receive a `MailFolder.MessageFlagsChanged` event without a `UniueId`, I have to stop the `ImapClient.Idle` to use that client to use `uniqueIds = MailFolder.Search(SearchQuery.All)` and  `MailFolder.Fetch(uniqueIds, MessageSummaryItems.Headers | MessageSummaryItems.Flags)` to identify the correct message with the `UniqueId`.

After this, I have to restart the `ImapClient.Idle`.

And if in the meantime a flag will be changed, I don't have a chance to get that information.

Right?

The live is not easy…

**Comment by jstedfast** [comment]
Why would you need to do all of that?

You should already have a list of messages and the message who's should already be in that list. There should be no reason to have to go out and query for the message and its headers/flags/etc.

Consider this:

* var messages = folder.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.Flags)
* client.Idle()
* MessageFlagsChanged event fires
* messages[index].Flags = args.Flags; messages[index].Keywords = args.Keywords

I think that Fetch() actually returns `IList<IMessageSummary>` and IMessageSummary I think only has getters for all of the fields, but you can either cast to MessageSummary to allow you to set fields or you can copy the data into your own data structure to keep in your cache (e.g. a sqlite database), but the idea is the same.

Also FWIW, I would not recommend using MessageSummaryItems.Headers as that is a lot more expensive than MessageSummaryItems.Envelope and Envelope usually contains all of the (pre-parsed!) info that you care about. The only header that I feel it is missing is the `References` header (hence why I have a `MessageSummaryItems.References` enum).

**Comment by NilsHoyer** [comment]
Indeed, I have a list of the messages. But the `Index` inside `MessageFlagsChanged event` maybe is different from the index of my list, since the list was fetched by a different `ImapClient` connection.

So I need a `UniqueId` (or maybe a `MessageId`), to identify the correct message inside my list.

Thank you for your hint about `Envelope`!

**Comment by NilsHoyer** [comment]
> The only header that I feel it is missing is the References header

What about `Priority`?

**Comment by NilsHoyer** [comment]
`IMessageSummary.Envelope` is `null` on my end.

I have the following code:

```
IList<UniqueId> uniqueIds = mailFolder.Search(SearchQuery.All);
IList<IMessageSummary> messageSummaries = mailFolder.Fetch(uniqueIds, MessageSummaryItems.Headers | MessageSummaryItems.Flags);
foreach (MessageSummary messageSummary in messageSummaries)
    messageSummary.Envelope....
```

`messageSummary.Headers[HeaderId.From]` shows me the the correct value.

**Comment by jstedfast** [comment]
The MessageSummary.Envelope property only gets populated if you specify MessageSummaryItems.Envelope.

> What about Priority?

Yea, I guess I can see that as being a valuable header to have. When I originally added the `MessageSummaryItems.References` enum, I did not have an `IFetchRequest` and so there was no way to specify what headers you wanted (hence also why there is a `MessageSummaryItems.Headers`).

A better way to specify which headers you want would be to do something like this:

```csharp
// Fetch *ALL* headers (instead of Envelope, maybe because we don't trust the IMAP server's parsing and we want to do our own):
var fetchRequest = new FetchRequest (MessageSummaryItems.UniqueId | MessageSummaryItems.Flags) {
    Headers = HeaderSet.All
};
```

```csharp
// Fetch Envelope and References:
var fetchRequest = new FetchRequest (MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.Flags) {
    Headers = HeaderSet.References
};
```

```csharp
// Fetch Envelope, References, Importance, and *Priority:
var fetchRequest = new FetchRequest (MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.Flags) {
    Headers = new HeaderSet (new HeaderId[] {
        HeaderId.References,
        HeaderId.Importance,
        HeaderId.Priority,
        HeaderId.XPriority,
        HeaderId.XMSMailPriority
    })
};
```

The added bonus of the IFetchRequest is that you can also fetch the inverse of the headers you specify (e.g. `FETCH BODY[HEADERS.NOT (<list>)]`):

```csharp
// Fetch all of the headers except the Received headers
var fetchRequest = new FetchRequest (MessageSummaryItems.UniqueId | MessageSummaryItems.Envelope | MessageSummaryItems.Flags) {
    Headers = new HeaderSet (new HeaderId[] {
        HeaderId.Received
    }) {
        Exclude = true
    }
};
```

**Comment by NilsHoyer** [comment]
Now, I can terminate the `ImapClient.Idle`.

But after this, it's disconnected. Why?

**Comment by NilsHoyer** [comment]
Since you close the connection, there is no save way to get the `UniqueId` from the `MailFolder.MessageFlagsChanged` event.

> A better way to specify which headers you want would be to do something like this:

Ok, with this, I can reduce the network traffic.

**Comment by NilsHoyer** [comment]
Back to the `Index`: If I use multiple `MailFolders`, is the `Index` only valid for one folder, or is it valid over all folders?

**Comment by NilsHoyer** [comment]
So, to be sure of having the correct `Index`, I have to stop the `ImapClient.Idle` after receiving a `MailFolder.CountChanged` and get the updated List of `Index` <-> `UniqueId`. After that, I can restart the `ImapClient.Idle`.

**Comment by jstedfast** [comment]
That sounds correct, yes.

**Comment by NilsHoyer** [comment]
But it's easier, to update all messages, by using only `MessageSummaryItems.UniqueId | MessageSummaryItems.Flags` for the folder of the `MailFolder.MessageFlagsChanged` event.

With this, I don't need to get the `UniqueId` from the `Index`.

But sometimes, the `MailFolder.MessageFlagsChanged` event reports the `UniqueId` too. Right?

**Comment by jstedfast** [comment]
Rarely (as in 99% of servers won't), but it's possible.

**Comment by NilsHoyer** [comment]
Thanks a lot for you knowledge!
