### ISSUE TITLE
Changing of enum values is pretty dangerous to do

### ISSUE THREAD

**Issue by des2k7** [jstedfast/MailKit#1439]
In this commit, you guys implicitly changed the enum values of the SpecialFolder enum.
Concretely, you added Important somewhere in the middle, instead of at the end.

https://github.com/jstedfast/MailKit/commit/5d98210a971ca636e64c8bb360bf36f6b53083e0

Yes, we shouldnt use the int values, but some of us devs have to work with legacy code, created by lesser creatures :-)

Anyway, long story short, i now have DB values which no longer match the SpecialFolder.CS enum values.
I am now saving sent mails in the junk/spam box.

Perhaps mention this in your upgrade documentation (which i have not found)?
Changing this again, now, to support v1 -> v3 upgrade would be unwise

**Comment by ekalchev** [comment]
We had the same issues with stored integers in DB. It was huge mess.

**Comment by jstedfast** [comment]
Sorry about that. I've been avoiding making those enum changes again.

**Comment by des2k7** [comment]
> Sorry about that. I've been avoiding making those enum changes again.

lol dont worry, you're absolutely not the first :D

**Comment by des2k7** [comment]
one question i still have; i couldnt find any migration guides. Do they exist?

**Comment by jstedfast** [comment]
There aren't any. Closest thing there is would be the ReleaseNotes.md file in the repository.

I try not to remove APIs without first marking the old API as [Obsolete] with a mention of the replacement method/property and keep that around at least until the next major version bump.

With 3.x, I even went so far as to write extension methods to maintain compatibility with 2.x since I had to completely redesign the IMAP API due to an exploding number of method overloads to keep up with new IMAP extensions.
