### ISSUE TITLE
Cannot get message by UniqueId from Starred folder (gmail)

### ISSUE THREAD

**Issue by vzhusel** [jstedfast/MailKit#145]
It seems something wrong with working with Starred folder on gmail server. The using
FetchAsync, it is returning empty collection, when passing UniqueId and use "[Gmail]/Starred" as current folder.

var messages = await currentFolder.FetchAsync(uniqueIds, MessageSummaryItems.BodyStructure | MessageSummaryItems.All | MessageSummaryItems.UniqueId, cancellationToken).ConfigureAwait(false);

**Comment by jstedfast** [comment]
1. Are you sure you have the correct UIDs?
2. Are you sure those UIDs exist in that folder?
3. Did you Open() the folder before calling FetchAsync()?

Try passing a `ProtocolLogger` to the ImapClient constructor (e.g. `client = new ImapClient (new ProtocolLogger ("imap.log"));` so that you can get a log of the interaction with the IMAP server to see what might be going wrong.

**Comment by vzhusel** [comment]
Jeffrey,

1. Yes
2. Yes
3. Yes

The problem is that folder Starred is like aggregate folder at Gmail it shows all emails which are marked as flagged from other folders. But there's no way to determine from which folder they are, right now. I can get emails using FetchAsync and pass indexes, but cannot get single email using Starred folder and UniqueId

**Comment by jstedfast** [comment]
How are you getting the UIDs? It doesn't matter that the Starred folder is an aggregate because IMAP has no such concept and so GMail will reassign new UIDs to those messages that are unique to that folder.

For example, a message might have a UID of 710 in the Inbox, be starred, and so will show up in the Starred folder... but it's UID in the Starred folder might be 5.

My guess is that you are using the wrong UIDs.

**Comment by jstedfast** [comment]
In other words: UIDs are not unique across the account, they are unique per folder.

**Comment by vzhusel** [comment]
I get UIDs using FetchAsync and passing indexes. Thank you, for the explanation, let me double check everything.

**Comment by vzhusel** [comment]
I have found a problem, then  I tried to open email, I marked as read using SetFlagsAsync and this method was removing Flagged flag, if only Read was passed. Issue resolved. Thank you, for you help.

**Comment by jstedfast** [comment]
Ah, yea, you probably wanted to use AddFlagsAsync() instead.

**Comment by truane** [comment]
can you explain when we should use SetFlags and when we should use  AddFlags? Do we need to check if the flag already exists exist first?

or is the the first time you call it you use set after that you use add?

**Comment by jstedfast** [comment]
SetFlags() is an absolute thing. When you set the flags to X, they become X... not X + whatever was already set before.

AddFlags() adds the flags to the existing flags. So if the flags are X and you call AddFlags(Y), then the result will be X+Y.

RemoveFlags() is the opposite of AddFlags().
