### ISSUE TITLE
Version change from 3.3.0 to 3.4.0 breaks build on ASP.NET Core 2.1

### ISSUE THREAD

**Issue by neman** [jstedfast/MailKit#1466]
**Describe the bug**
I added reference for MailKit version 3.4.0 to project. This project is referenced from ASP.NET MVC Core project 2.1
When I try to build solution I got following error:

>System.Runtime.CompilerServices.Unsafe doesn't support netcoreapp2.1. Consider updating your TargetFramework to netcoreapp3.1 or later.

When I downgrade package to 3.3.0 I can build entire solution.

I know I have to migrate from 2.1, it is some legacy project, but I'm curious what might be the issue.

**Comment by jstedfast** [comment]
I bumped some of MimeKit's System.* dependencies between v3.3.0 and v3.4.0, which probably brought in a version of System.Runtime.CompilerServices.Unsafe that wasn't supported on netcoreapp2.1

**Comment by jstedfast** [comment]
FWIW, I would recommend sticking with v3.3.0 unless you need one of the IMAP fixes. The Socket Connect fix I wrote for v3.4.0 had to be reverted (hence v3.4.1) and the SMTP PIPELINING fix I wrote for v3.4.2 had to be reverted as well (and I need to make a v3.4.3 release).

Other than some IMAP fixes, most everything else is just some slight micro-optimizations which you probably don't care about.

IIRC, the only reason that I bumped the dependencies in the first place was because of some TypeLoadException bug reports that I was getting for both System.Text.Encoding.CodePages and (funnily enough) System.Runtime.CompilerServices.Unsafe where their apps were trying to load a conflicting version of one of those 2 libraries because MimeKit was depending on an older version.

I just discovered last night that this is a known issue with the MSBuild targets that shipped with some versions of Visual Studio. MimeKit depends on a version >= to the one it links against, but because of the MSBuild target bug, it got linked to an *exact* version. This became a problem because some nugets out there that some people are using in conjunction with MimeKit/MailKit depend on newer versions of those libraries, and so MimeKit/MailKit were failing to be able to load the exact version of the assembly.

**Comment by jstedfast** [comment]
I don't think I can "fix" this because it seems that I need to require v6.0.0 just to avoid issue like this: https://github.com/jstedfast/MailKit/issues/1462
