### ISSUE TITLE
Get UID from MimeMessage

### ISSUE THREAD

**Issue by crm76** [jstedfast/MailKit#147]
First.. thank you, Jeffrey, for your efforts in this project.

I want to delete an email (Pop3Client), and to do that I need the UID. However when I have a MimeMessage instance, the UID doesn't seem to be anywhere in that object. How do I get the UID from MimeMessage?

**Comment by jstedfast** [comment]
You can't. The MimeMessage is *only* the MIME message data which does not have any UID metadata on it.

If you need to keep track of UIDs, then you'll need to do that separately.

For example, you might do this:

```csharp
var uids = client.GetMessageUids ();
for (int i = 0; i < client.GetMessageCount (); i++) {
    var message = client.GetMessage (i);
    var uid = uids[i];

    // ...
}
```

**Comment by crm76** [comment]
Thanks. I simply created a class with a message property and a Uid property and just pass an instance of that around so I have both together.

On a related note, why doesn't this work?

        public static void Delete(string uid)
        {
            using (var client = new MailKit.Net.Pop3.Pop3Client())
            {
                client.Connect("server", 110, false);
                client.AuthenticationMechanisms.Remove("XOAUTH2");
                client.Authenticate("user", "password");

                client.DeleteMessage(uid);

                client.Disconnect(true);
            }
        }

For it to work, I have to call client.GetMessageUids() prior to the delete call. Doesn't seem very discover-able. I imagine that it would seem to many that if they have an Uid and they call a method that accepts a Uid it shouldn't throw an exception but rather should perform the indicated action.

**Comment by jstedfast** [comment]
The problem is that the POP3 server does not allow operations on UIDs, all POP3 commands take indexes, and so `client.DeleteMessage(string uid)` needs to know the UID-to-index mapping which it only gets when you call `GetMessageUids()`.

I could probably make each of those commands prep themselves with a call to GetMessageUids() internally if the internal uid-to-index mapping is empty, but honestly I regret adding methods overrides that take uids because it's very inefficient to have to manage that mapping behind the scenes (it means the Pop3Client has to have a duplicate mapping from what higher-level code is probably already maintaining anyway).
