### ISSUE TITLE
API around sending email with DkimSigning and FormatOptions

### ISSUE THREAD

**Issue by marklagendijk** [jstedfast/MailKit#1484]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when adding a nice feature, such as DkimSigning, causes hidden problems down the road.

Note: I understand how incredibly hard it can be to make a perfect API for a library that needs to respect so many RFCs. Thank you for your incredible work on this!

Let's consider this code in SmtpClient:
```c#
protected virtual void Prepare(
    FormatOptions options,
    MimeMessage message,
    EncodingConstraint constraint,
    int maxLineLength)
{
    if (!message.Headers.Contains(HeaderId.DomainKeySignature) && !message.Headers.Contains(HeaderId.DkimSignature) && !message.Headers.Contains(HeaderId.ArcSeal))
        message.Prepare(constraint, maxLineLength);
    else
        options.International = false;
}
```
This has two problems:
1. `message.Prepare` is only called when the message isn't signed. 
2. `options.International` is disabled when the message is signed.

#### Problem 1: message.Prepare is only called when the message isn't signed.
The solution to this [is shown in the example](https://github.com/jstedfast/MailKit/blob/9f31a9c670d105b87f8903061dc88616aef75cdf/Documentation/Examples/DkimExamples.cs#L24). However, in the example the `EncodingConstraint` is set to a static value, while in SmtpClient it is set automatically based on the Capabilities of the client.
So to replicate this we need to copy the logic from the SmtpClient:
```c#
message.Prepare(smtpClient.GetEncodingConstraint());

public static class SmtpClientExtensions
{
    public static EncodingConstraint GetEncodingConstraint(this SmtpClient smtpClient)
    {
        return (smtpClient.Capabilities & SmtpCapabilities.BinaryMime) == SmtpCapabilities.None
            ? (smtpClient.Capabilities & SmtpCapabilities.EightBitMime) == SmtpCapabilities.None
                ? EncodingConstraint.SevenBit
                : EncodingConstraint.EightBit
            : EncodingConstraint.None;
    }
}
```

#### Problem 2:  options.International is disabled when the message is signed
The solution is not shown in the example. I just found out that one can pass `FormatOptions` to the `sign` method. To make this automatic based on the `Capabilities` you need to write:
```c#
message.Prepare(smtpClient.GetEncodingConstraint());
signer.Sign(smtpClient.GetFormatOptions(), message, _dkimSigningOptions.Headers);

public static class SmtpClientExtensions
{
    public static FormatOptions GetFormatOptions(this SmtpClient smtpClient)
    {
        var options = FormatOptions.Default.Clone();
        options.International =
            smtpClient.Capabilities.HasFlag(SmtpCapabilities.EightBitMime) &&
            smtpClient.Capabilities.HasFlag(SmtpCapabilities.UTF8);
        return options;
    }
}
```

**Describe the solution you'd like**
For problem 1 it might be nice to expose a method like the one I showed, and use that in the example.
For problem 2 it would be nice to show the `sign` overload that uses `FormatOptions` in the example. Also it would be nice to expose something like a `SmtpClient.SupportsInternational` method that checks those `Capabilities` flags.

**Comment by jstedfast** [comment]
> Problem 1: message.Prepare is only called when the message isn't signed.

```csharp
protected virtual void Prepare(
    FormatOptions options,
    MimeMessage message,
    EncodingConstraint constraint,
    int maxLineLength)
{
    if (!message.Headers.Contains(HeaderId.DomainKeySignature) && !message.Headers.Contains(HeaderId.DkimSignature) && !message.Headers.Contains(HeaderId.ArcSeal))
        message.Prepare(constraint, maxLineLength);
    else
        options.International = false;
}
```

The above method is only there because so many developers forget to prepare the message for transport and so SmtpClient does it for them out of convenience.

It is expected that anyone doing DKIM signing will be disciplined enough to call `MimeMessage.Prepare()` with the appropriate `EncodingConstraint` before calling `SmtpClient.Send*()`.

> The solution to this [is shown in the example](https://github.com/jstedfast/MailKit/blob/9f31a9c670d105b87f8903061dc88616aef75cdf/Documentation/Examples/DkimExamples.cs#L24). However, in the example the EncodingConstraint is set to a static value, while in SmtpClient it is set automatically based on the Capabilities of the client.
So to replicate this we need to copy the logic from the SmtpClient:

I get what you're saying, but I'm not sure I want to encourage the idea of mimicking the SmtpClient logic *exactly* because if an SMTP server supports BINARYMIME, for example, that doesn't mean the client *should* send BINARYMIME. The SmtpClient logic does that only because it is trying to prevent itself from overriding the user's preferences any more than it absolutely needs to.

In other words, SmtpClient's behavior is only the ideal behavior if/when the user forgets to prepare their message *and* where SmtpClient doesn't want to restrict things more than it has to.

If the user is sending a DKIM-signed message (for example), then it's possible that an SMTP relay along the way might not support BINARYMIME even if *your* SMTP server does, and so even though your SMTP server supports BINARYMIME, you might want to prepare using `SevenBit` because you don't want to risk an SMTP relay between your SMTP server and the destination re-encoding the message and breaking the DKIM-signature as a result.

This is a problem for S/MIME and PGP/MIME as well.

I would personally encourage `EncodingConstraint.SevenBit` if you really want to be sure digital signatures will verify at the receiving end and `EightBit` if you want to be a little bit looser with your expectations and/or *know* that all of the SMTP servers involved support 8BITMIME.

When not sending any digital signatures, going with whatever the SMTP server supports is fine.

> Problem 2: options.International is disabled when the message is signed

See above explanation about digital signature verification issues.

> Update: I have not yet been able to get the combination of DkimSigning and FormatOptions.International to work. Whatever I do, email addresses with UTF-8 are always converted to punycode.
> @jstedfast do you know whether this at all possible, or whether there is a limitation in either the library or the standards that make it impossible?

SmtpClient disables FormatOptions.International if the server does not support the SMTPUTF8 extension and also in the `virtual Prepare()` method.

You would need to subclass SmtpClient and override that virtual Prepare() method to be a no-op.

**Comment by marklagendijk** [comment]
Only when reading your response I am starting to realize how hard a problem domain this is:
* There are all these standards + extensions
* In most cases you are dealing with a chain of SMTP-servers, and you can only know what the first one supports
* Which may or may not matter, depending on the Capability and on things like DKIM.

## EncodingConstraint
Do you know how common lack of `8BITMIME` support is? Our scenario is:
* We daily sent a large number of newsletter emails (over 500k).
* A .NET application distributes the emails over a number of mail servers (SmarterMail) that sent them.
* In the past the .NET application sent to a single server, that would do the DKIM-signing and distribution.

Now reading more on the subject I feel like I am only getting more confused. I assumed that using `EncodingConstraint.SevenBit` meant: only supports ASCII-characters, if your email contains UTF-8 characters you have a problem.
The description of `EncodingConstraint.SevenBit` seems to support this: "The content may only contain bytes within the 7-bit ASCII range.".
However, in [this Wikipedia section](https://en.wikipedia.org/wiki/Unicode_and_email) it says two things:

> [UTF-7](https://en.wikipedia.org/wiki/UTF-7), an obsolete encoding, had an advantage over Unicode encodings, on obsolete non-8bit-clean networks, in that it does not require a transfer encoding to fit within the seven-bit limits of legacy Internet mail servers.

And:
> Some document formats, such as [HTML](https://en.wikipedia.org/wiki/HTML), [PostScript](https://en.wikipedia.org/wiki/PostScript) and [Rich Text Format](https://en.wikipedia.org/wiki/Rich_Text_Format) have their own 7-bit encoding schemes for non-ASCII characters and can thus be sent without using any special email encodings. E.g. [HTML email](https://en.wikipedia.org/wiki/HTML_email) can use [HTML entities](https://en.wikipedia.org/wiki/HTML_entities) to use characters from anywhere in Unicode even if the HTML source text for the email is in a legacy encoding (e.g. 7-bit ASCII).

Question: Does MailKit automatically use either UTF-7 or HTML entities to overcome the ASCII-limitation?

## International Email
> SmtpClient disables FormatOptions.International if the server does not support the SMTPUTF8 extension and also in the virtual Prepare() method.
That makes sense. 

> You would need to subclass SmtpClient and override that virtual Prepare() method to be a no-op.
Question: Are you saying that the only way to combine DKIM with `FormatOptions.International` is to subclass SmtpClient? Is there a reason why combining these two is not recommended?

**Comment by jstedfast** [comment]
> Do you know how common lack of 8BITMIME support is? Our scenario is:

I don't have stats on this, but I *suspect* that by now, most servers support at least 8BITMIME. The 8BITMIME extension specification was published decades ago and is a simple enough extension to support that it would be silly not to.

> The description of EncodingConstraint.SevenBit seems to support this: "The content may only contain bytes within the 7-bit ASCII range.".
> ...
> Question: Does MailKit automatically use either UTF-7 or HTML entities to overcome the ASCII-limitation?

If/when you do `message.Prepare (EncodingConstraint.SevenBit)`, what ends up happening is that if you have non-ASCII text in any of the MimeParts, those MimeParts get encoded to either quoted-printable or base64 (MimeKit uses an algorithm to determine the most space-efficient encoding to use if the content is text or base64 if it is binary content). UTF-7 and HTML entities are not used. I would discourage the use of UTF-7 in general and HTML entities can only be used in HTML content (i.e. text/html parts).

> Question: Are you saying that the only way to combine DKIM with FormatOptions.International is to subclass SmtpClient?  Is there a reason why combining these two is not recommended?

Effectively, yes, I believe so.

It's not that it's not recommended, it's just that the default SmtpClient Prepare() implementation can't deal with that scenario because it doesn't know if that is safe or not.

**Comment by marklagendijk** [comment]
@jstedfast thank you for taking the time to write such comprehensive replies.

>If/when you do message.Prepare (EncodingConstraint.SevenBit), what ends up happening is that if you have non-ASCII text in any of the MimeParts, those MimeParts get encoded to either quoted-printable or base64 (MimeKit uses an algorithm to determine the most space-efficient encoding to use if the content is text or base64 if it is binary content)

Ooh, that is a really neat solution. Good job!

> I don't have stats on this, but I suspect that by now, most servers support at least 8BITMIME. The 8BITMIME extension specification was published decades ago and is a simple enough extension to support that it would be silly not to.

That makes sense. In that case I prefer going for 8BITMIME.
When trying to do this, I got an unexpected result.

```c#
message.Prepare(EncodingConstraint.EightBit);
signer.Sign(FormatOptions.Default, message, _dkimSigningOptions.Headers);
smtpClient.SendAsync(message);
```
I would expect this code to send with the `Content-Transfer-Encoding` `8BIT` , but it is sent with (even though the server has the `EightBitMime` capability):
```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```
I must be missing something, but I can't see what it is.

**Comment by jstedfast** [comment]
This can happen for text/* MimeParts if the content is either too long (off the top of my head, I think it checks <= 78 bytes per line) or if a line would start with `"From "` because it needs to armor that line to preserve digital signatures in case the message goes through a UNIX system that stores messages in mbox format (which would cause munging of that line to `">From ..."`).

**Comment by marklagendijk** [comment]
Using the debugger I saw that the line length is indeed the culprit. I also found that the base reason is the max line length restriction that the standard allows for. 
It's 'funny' how `8BITMIME` is newer than `quoted-printable` but still is worse than it in terms of content it supports.

I must say that SMTP + extensions is the trickiest set of standards I encountered, so far. 

I suppose all of this knowledge has limited practical use for my use case, but I like finding out how stuff works in case there are relevant considerations to be made.
