### ISSUE TITLE
IMAP idle problem with events

### ISSUE THREAD

**Issue by m1adow** [jstedfast/MailKit#1488]
Hi there. I am writing app on UWP. Currently I am trying to know if new messages arrived into inbox. In my Account class I have two IMAPS one for fetching messages and acts with them and second for idling. There is my code snippet:

``` C#
private async Task RunIdleImapsAsync()
{           
    foreach (var account in Accounts ?? new ObservableCollection<Account?>())
    {
        if (account != null && account.IdleImapClient != null && account.IdleImapClient.IsAuthenticated && !account.IdleImapClient.IsIdle)
        {
            var inbox = account.IdleImapClient.Inbox;
            await inbox.OpenAsync(FolderAccess.ReadOnly);

            inbox.MessageExpunged += OnInboxMessageExpunged;
            var doneToken = new CancellationTokenSource();
            await account.IdleImapClient.IdleAsync(doneToken.Token);
            inbox.MessageExpunged -= OnInboxMessageExpunged;
         }
     }
}
```

What am I doing wrong? My event handler method does not execute

**Comment by jstedfast** [comment]
Whenever you are trying to debug one of these types of issues, it is best to log the IMAP commands/responses to a log file for diagnosis.

You can ask MailKit to log these commands/responses by doing this:

```csharp
var client = new ImapClient (new ProtocolLogger ("idle-client.log"))
```

Then, once you have that, you need to look at those logs and ask:

*Did the IMAP server send an `EXPUNGE` notification?*

If not, that is your answer.

100% of the time, the problem is that the IMAP server is not sending an event notification to MailKit's ImapClient and so MailKit obviously can't raise an event that it doesn't know about.
