### ISSUE TITLE
How to filter on exceptions?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1515]
This is not a bug/issue report but rather an inquiry (sorry, did not know where else to put it...):

How could I filter in exception? I e.g. have this exception
```
MailKit.Net.Imap.ImapCommandException: The IMAP server replied to the 'UNSELECT' command with a 'NO' response: Server Unavailable. 15
   at MailKit.Net.Imap.ImapFolder.CloseAsync(Boolean expunge, Boolean doAsync, CancellationToken cancellationToken)
   at Unusual.Mail.MailClient.<StartAsync>b__52_0() in C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs:line 1557
```
... and liked to apply a filter.

Is there some 'best practice' which could be applied across IMAP/SMTP implementation?
- is the value '15' an error code which I could filter on? How?
- would I need to some text message parsing?
- else?

Thanks in advance

**Comment by jstedfast** [comment]
I guess it depends on what pieces of information you want to filter on.

The "Server unavailable. 15" is, I think, an Exchange error message and I have no idea what the 15 code is or if it is documented anywhere (it's not specified by the IMAP protocol because that text is free-form text that servers can do anything they want with).

Just keep in mind that if you decide to write some sort of string parser, it will need different handlers for each server (software) and possibly each version of said server software.

For `SmtpCommandException`s, I would probably recommend using the `StatusCode` and `ErrorCode` properties.

For `ImapCommandException`, you can look at the `Response` property to get the `NO` or `BAD` value an the `ResponseText` to get just the server response text (before it gets combined with some other text in the `Exception.Message` property).

**Comment by DierkDroth** [comment]
Thanks for your feedback @jstedfast
