### ISSUE TITLE
Add an Example for IMailFolder.Thread(IList<UniqueId>, ThreadingAlgorithm, SearchQuery, CancellationToken) Method

### ISSUE THREAD

**Issue by Shimata7** [jstedfast/MailKit#1564]
Please add an example for IMailFolder.Thread(IList<UniqueId>, ThreadingAlgorithm, SearchQuery, CancellationToken) Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://www.mimekit.com/docs/html/M_MailKit_IMailFolder_Thread_1.htm

**Comment by jstedfast** [comment]
@Shimata7 are you still looking for an example of this in use?

The issue with writing an example for this is that 95% of the code in such an example will be UI framework code (e.g. WPF or Windows.Forms, etc etc).

The point of the Thread() method is to return a tree of messages organized in the way that a mail client would group conversations in the UI.

I'm not a UI developer, so I'd kinda struggle with writing an example for this.

Maybe if you tell me what you don't understand, I can help explain how you might want to use it.

That said, what makes this even more awkward is that not all IMAP servers support the [THREAD](https://www.rfc-editor.org/rfc/rfc5256.html) extension, which is why the [MessageThreader](http://www.mimekit.net/docs/html/T_MailKit_MessageThreader.htm) class exists.

**Comment by jstedfast** [comment]
I'm going to close this as WONTFIX because it'd be a ton of work and I just don't think it'd increase the value of MailKit enough to justify the time & effort I'd need to put into writing an example for this particular API.
