### ISSUE TITLE
Get email From Message.From

### ISSUE THREAD

**Issue by MaximKiselev** [jstedfast/MailKit#157]
Why these properties are't public?

**Comment by jstedfast** [comment]
What do you mean it isn't public? Of course it's public...

```csharp
		/// <summary>
		/// Gets the list of addresses in the From header.
		/// </summary>
		/// <remarks>
		/// <para>The "From" header specifies the author(s) of the message.</para>
		/// <para>If more than one <see cref="MailboxAddress"/> is added to the
		/// list of "From" addresses, the <see cref="Sender"/> should be set to the
		/// single <see cref="MailboxAddress"/> of the personal actually sending
		/// the message.</para>
		/// </remarks>
		/// <value>The list of addresses in the From header.</value>
		public InternetAddressList From {
			get { return addresses["From"]; }
		}
```

**Comment by MaximKiselev** [comment]
InternetAddress represent email? I dont find property to get native email.

**Comment by jstedfast** [comment]
Correct, an InternetAddress is an email address with a Name property for the person's name and an Address property for the address (e.g. username@domain.com).

**Comment by jstedfast** [comment]
I should explain my last comment better. An [InternetAddressList(http://jstedfast.github.io/MimeKit/docs/MimeKit/InternetAddressList.html) is a list of [InternetAddress](http://jstedfast.github.io/MimeKit/docs/MimeKit/InternetAddress.html) items. An `InternetAddress` is an abstract class with 2 subclasses: [GroupAddress](http://jstedfast.github.io/MimeKit/docs/MimeKit/GroupAddress.html) and [MailboxAddress](http://jstedfast.github.io/MimeKit/docs/MimeKit/MailboxAddress.html).

A `MailboxAddress` is what you probably consider an "email address" that comes in the form `"John Smith" <john@smith-plumbing.com>`. The `Name` property on the `MailboxAddress` contains the string `John Smith` while the `Address` property contains the string `john@smith-plumbing.com`.

A `GroupAddress` is something that is rarely used these days. It is a named list of addresses that might look something like this if you ever find an example of one in a message's To or Cc header: `Friends: Joey <joey@friends.com>, Monica <monica@friends.com>, "Mrs. Chanandler Bong" <chandler@friends.com>, Ross <ross@firnds.com>, Rachel <rachel@friends.com>;`

Since you probably only care about the individual email addresses on the From header of the message, you could just use this:

```csharp
foreach (var mailbox in message.From.Mailboxes)
    Console.WriteLine ("{0}'s email address is {1}", mailbox.Name, mailbox.Address);
```

Hope that helps.

**Comment by MaximKiselev** [comment]
jstedfast, thanks for help.

**Comment by jstedfast** [comment]
you're welcome

**Comment by f1f9f11** [comment]
hey i think MailKit library is more difficult  that  Imap4Client library or is my idea
