### ISSUE TITLE
OnMessageExpunged MessageEventArgs returning UniqueId null

### ISSUE THREAD

**Issue by usamasarfraz** [jstedfast/MailKit#1592]
![IMG_20230615_135203](https://github.com/jstedfast/MailKit/assets/42145696/4cab9b52-0a48-4836-904c-eb1e508c7f7c)

**Comment by jstedfast** [comment]
The expunged event will never get a UID.

**Comment by jstedfast** [comment]
To add a little more background (was on my phone earlier):

MessageEventArgs is used as args for many of the message-related events emitted by ImapFolder where the UID is often available and that's why it has the UniqueId property.

Perhaps, in hindsight, I should have used a special MessageExpungedEventArgs which only had an int Index property for this event, but it seemed overkill at the time.

**Comment by usamasarfraz** [comment]
Thanks for your consideration.
