### ISSUE TITLE
Problem when applying an OrderBy to a SearchQuery on an IMAP  Folder

### ISSUE THREAD

**Issue by silaing** [jstedfast/MailKit#164]
Hi
I have been trying to apply a number of OrderBy arguments to a SearchQuery on an open IMAP mail folder as per some of the examples you provide. If I run the Search without the orderBy argument it works fine and returns all the UniqueIds. Applying an OrderBy, however, throws an exception 

"The IMAP server replied to the 'SORT' command with a 'NO' response.". 

Is there anything I'm missing out?

var orderBy = new[] { OrderBy.From };
var query = SearchQuery.All;
var resul  = folder.Search(query, orderBy);

thank you for any help.

**Comment by jstedfast** [comment]
It probably means your server does not support sorting. Does client.Capabilities contain the ImapCapabilities.Sort bit?

**Comment by jstedfast** [comment]
never mind about my previous question, if your server didn't advertize the SORT extension, then MailKit would throw a NotSupportedException when you tried to search with an OrderBy list.

The reasons your IMAP server might respond with a "NO" are that it just refuses to sort by the criteria you provided for whatever reason *or* the charset used in the search criteria is not supported. MailKit will use US-ASCII as the search charset if all of your search strings are US-ASCII (in your case, this would hold true), otherwise it falls back to UTF-8.

Try following the directions at https://github.com/jstedfast/MailKit/blob/master/FAQ.md#how-can-i-get-a-protocol-log-for-imappop3smtp-to-see-what-is-going-wrong to get a protocol log to reveal what the problem is (perhaps the server explains the problem).

**Comment by silaing** [comment]
Thanks for your speedy replies, I will investigate the information you provided to further identify the problem as soon as I can.

**Comment by silaing** [comment]
Hi
It appears the charset is the problem as the log returns:
S: B00000008 NO [BADCHARSET] parse error: unknown charset: RETURN

The Mail Server runs on a Ubuntu box with the Language set thus:
LANG="en_GB.UTF-8"
LANGUAGE="en_GB:en"

If it falls back to UTF-8 should that not be happening as set above?

thanks

**Comment by jstedfast** [comment]
Can you get me the full logs of the SORT command? The error above indicates that it's not a charset bug, actually, but rather that it thought the RETURN statement was the charset.

**Comment by jstedfast** [comment]
The problem is not the charset or even the charset param, the problem is that MailKit was sending a command like this:

```
C: B00000008 UID SORT (FROM) RETURN () US-ASCII ALL
```

When it *should* have been sending:

```
C: B00000008 UID SORT RETURN () (FROM) US-ASCII ALL
```

In other words, the IMAP server was expecting a charset name after the sort-order parameter but instead found the "RETURN" token, hence the error message being "NO [BADCHARSET] parse error: unknown charset: RETURN".

So this is a bug in MailKit, not the IMAP server.

It would be nice if you could confirm my diagnosis with the actual command from the log to make sure I'm  correct.

**Comment by silaing** [comment]
Hi
I have included the log text for the method - the code producing the error is:
var orderBy = new[] { OrderBy.ReverseDate }; //error with any OrderBy
var query = SearchQuery.All;
var fullResul = folder.Search(query);
var resul = folder.Search(query, orderBy);

Connected to imaps://192.168.2.3/
S: * OK IMAP4 ready
C: B00000000 CAPABILITY
S: * CAPABILITY ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE IMAP4rev1 LIST-EXTENDED LIST-STATUS LITERAL+ MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST AUTH=PLAIN
S: B00000000 OK completed
C: B00000001 AUTHENTICATE PLAIN AGFuZHJldy5tdXJyYXkAU29mdCN3YXJl
S: B00000001 OK [CAPABILITY IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST] AUTHENTICATE completed
C: B00000002 NAMESPACE
S: * NAMESPACE (("" "/")) (("/home/" "/")) NIL
S: B00000002 OK NAMESPACE completed
C: B00000003 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: B00000003 OK LIST completed
C: B00000004 XLIST "" "*"
S: * XLIST (\HasNoChildren) "/" "Chats"
S: * XLIST (\HasNoChildren) "/" "Contacts"
S: * XLIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * XLIST (\HasNoChildren) "/" "Emailed Contacts"
S: * XLIST (\HasNoChildren \Inbox) "/" "INBOX"
S: * XLIST (\NoInferiors \Spam) "/" "Junk"
S: * XLIST (\HasNoChildren \Sent) "/" "Sent"
S: * XLIST (\HasNoChildren \Trash) "/" "Trash"
S: B00000004 OK XLIST completed
C: B00000005 LIST "" "%"
S: * LIST (\HasNoChildren) "/" "Chats"
S: * LIST (\HasNoChildren) "/" "Contacts"
S: * LIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * LIST (\HasNoChildren) "/" "Emailed Contacts"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: * LIST (\NoInferiors \Junk) "/" "Junk"
S: * LIST (\HasNoChildren \Sent) "/" "Sent"
S: * LIST (\HasNoChildren \Trash) "/" "Trash"
S: B00000005 OK LIST completed
C: B00000006 EXAMINE INBOX (CONDSTORE)
S: * 1 EXISTS
S: * 1 RECENT
S: * OK [UIDVALIDITY 1] UIDs are valid for this mailbox
S: * OK [UIDNEXT 258] next expected UID is 258
S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $MDNSent Forwarded $Junk $NotJunk Junk JunkRecorded NonJunk NotJunk)
S: * OK [PERMANENTFLAGS ()] junk-related flags are not permanent
S: * OK [HIGHESTMODSEQ 1806] modseq tracked on this mailbox
S: B00000006 OK [READ-ONLY] EXAMINE completed
C: B00000007 UID SEARCH RETURN () ALL
S: * ESEARCH (TAG "B00000007") UID ALL 257
S: B00000007 OK UID SEARCH completed
C: B00000008 UID SORT (REVERSE DATE) RETURN () US-ASCII ALL
S: B00000008 NO [BADCHARSET] parse error: unknown charset: RETURN

**Comment by jstedfast** [comment]
Okay, looks like my diagnosis was correct. My patch above fixes this issue. Thanks for getting me the log.

I'll be making a new MailKit release this weekend with the fix.

**Comment by silaing** [comment]
Okay, thanks, I look forward to your update.
