### ISSUE TITLE
Does ImapFolder.MessageFlagsChanged report the UniqueId constantly?

### ISSUE THREAD

**Issue by AdvancedNotifier** [jstedfast/MailKit#1649]
I'm using `ImapFolder.Idle` and `ImapFolder.MessageFlagsChanged`.

One year before, you told me, not to use the given `UniqueId`, because a lot of servers does not report them.

Does this problem still exists, or did you found a way to get it constantly?

**Comment by jstedfast** [comment]
I doubt that I told you *not* to use it, I likely told you that it wouldn't generally be set because the vast majority of servers do not provide that information in most cases.

What I said a year ago is still true today and will be true for eternity because the IMAP v4 specification does not require that a server provide that info.

From what I remember having seen a preview of v5 of the IMAP protocol, it is the same for that as well.

You can check this by checking MessageFlagsEventArgs.UniqueId.IsValid.
