### ISSUE TITLE
Please, could you provide examples for using ProxyClient, also how/when to use Sockets?

### ISSUE THREAD

**Issue by eitanbehar** [jstedfast/MailKit#1684]
There is no clear documentation on how to use ProxyClient. The same refers to when/how Sockets are to be used.
A simple example on how to use ProxyClient would be very useful.
Currently we are relaying on Stackoverflow errors to understand the correct behavior.
Some common questions?
* Is it required to set a proxy before connect?
* Can the proxy be changed after connect?
* How is the proper use of sockets4/5, etc?
Thanks,
Eitan

**Comment by jstedfast** [comment]
> * Is it required to set a proxy before connect?

Yes. Honestly, it wouldn't really make sense to set the proxy after connect since the whole point of a proxy is that it is used to establish a connection and to then act as a middle-man for the client and server to talk to each other after that.

> * Can the proxy be changed after connect?

I don't remember off-hand if setting the ImapClient.Proxy property (for example) will throw an exception if you try to set it to a new value after connecting, but setting it to a new value wouldn't do anything until you tried to establish a new connection, so it would be pointless to set it to a different proxy mid-session.

> * How is the proper use of sockets4/5, etc?

I'm guessing you mean SOCKS4 (and SOCKS4A) and SOCKS5? Those are proxy protocols and you'd need to find out which version of the SOCKS protocol that your proxy server uses in order to decide which one to use.

The way that you'd typically use a proxy in MailKit is very simple:

```csharp
using (var client = new SmtpClient ()) {
    client.Proxy = new Socks5Proxy ("socks5.proxy.com", 1080, new NetworkCredentials ("proxyUserName", "proxyPassword"));
    client.Connect ("mail.google.com", 465, SecureSOcketOptions.SslOnConnect);
    client.Authenticate ("username@gmail.com", "password");
    client.Send (message);
    client.Disconnect (true);
}
```
