### ISSUE TITLE
Please document/explain removal of "XOAUTH2"

### ISSUE THREAD

**Issue by migig** [jstedfast/MailKit#175]
When sending mail using SMTP and SSL, examples always show this block:

    // Note: since we don't have an OAuth2 token, disable
    // the XOAUTH2 authentication mechanism.
    client.AuthenticationMechanisms.Remove ("XOAUTH2");

I'm not a SMTP protocol expert, so I don't understand what it's for?

**Comment by jstedfast** [comment]
It's exactly what the comment says. When connecting to gmail.com (and I think yahoo.com) which supports the OAuth 2.0 SASL mechanism, unless you are specifically going to use an OAuth 2.0 auth token instead of a password, the XOAUTH2 SASL mechanism will always fail, so I remove it if it's there.

You don't have to remove it, it's just that it will attempt to authenticate using it if you don't, which wastes time.

**Comment by migig** [comment]
I don't connect to gmail/yahoo/etc.

So are you saying that the library will *always* try connect using that authentication protocol (regardless of which SMTP server I connect to), unless I disable it? Or that it only tries it when you connect to those *specific* servers?

Out of curiosity, would it not have been better then to make that optional, rather than default?

Out of curiosity, are there any other auth protocols (or whatever else is under the hood) that we could disable to speed up connections?

Love the library by the way, blows `System.Net.Mail` out of the water!

**Comment by jstedfast** [comment]
It will only try to use that authentication mechanism *if* the server supports it, otherwise it won't.

The way MailKit works is that it if one authentication mechanism fails, it will fall back to the next authentication mechanism in the list and so on until it authenticates or runs out of auth mechanisms.

It *possibly* would have been better to have an API where the developer passes in a single auth mechanism to try, but in my experience most developers have no idea what auth mechanism to use, so I solved that problem by making MailKit try them in order of most secure to least secure.

If the developer doesn't want the client to try a certain auth mechanism, they can just remove it from the list of mechanisms.

The client.AuthenticationMechanisms hashset contains a list of all mechanisms that the server supports. You can remove any (or all) of them. If you remove all of them, it will try the standard clear-text username and password login mechanism for POP3 and IMAP (SMTP doesn't have a default user/pass login mechanism).

To see the mechanism rank, you can check https://github.com/jstedfast/MailKit/blob/master/MailKit/Security/SaslMechanism.cs#L51

DIGEST-MD5 is considered deprecated these days, but it's still more secure that PLAIN and LOGIN which both send your user name and password in the clear (well, almost, they base64 encode them... but that's easily decoded back to clear text).

The other mechanisms do not send the password at all. Instead, they send a cryptographic hash of the password using the initialization vectors provided by the server.

**Comment by migig** [comment]
@jstedfast Thank you for the detailed explanation. I'm sure others will benefit from it as well!

One more thing though. If there are a suite of auth mechanisms to try, why remove that specific one? What is so special about it that you need to explicitly remove it - why not remove other unused ones as well (assuming you know in advance that the server doesn't support them)?

**Comment by jstedfast** [comment]
XOAUTH2 does not use a password, it uses an auth token that you have to explicitly fetch from an OAuth2.0 web server.
