### ISSUE TITLE
Can SendAsync complete without throwing, but essentially fail to deliver?

### ISSUE THREAD

**Issue by kikaragyozov** [jstedfast/MailKit#1761]
Can `SendAsync` method complete successfully without throwing an exception, but in reality, something had gone wrong with the e-mail - it was never sent, it's missing in the "Sent" folders of the account etc?

I see that `SendAsync` returns a string. Am I to inspect it for a specific string, to understand if the e-mail was really, successfully sent? Or is this already being done under the hood by the library?

I can confirm this occurred at least once, when running MailKit 4.3.0.

**Comment by jstedfast** [comment]
Short answer: yes.

Send/SendAsync will complete successfully if they manage to upload the message to the SMTP server without any errors.

But just because a message is sent successfully doesn't mean it will be delivered successfully.

Also, it should be noted that SmtpClient will not add the message to your Sent folder. SMTP doesn't have a way to do that.

You need to use the ImapClient to append the message to the Sent folder.

The string returned by the SendAsync method is the final response sent by the SMTP server indicating that the message has been successfully queued by the server. The reason that it is returned by MailKit is because some servers include identifiers that can be used for tracing telemetry session data and some developers find that useful.

**Comment by kikaragyozov** [comment]
> Short answer: yes.
> 
> Send/SendAsync will complete successfully if they manage to upload the message to the SMTP server without any errors.
> 
> But just because a message is sent successfully doesn't mean it will be delivered successfully.
> 
> Also, it should be noted that SmtpClient will not add the message to your Sent folder. SMTP doesn't have a way to do that.
> 
> You need to use the ImapClient to append the message to the Sent folder.
> 
> The string returned by the SendAsync method is the final response sent by the SMTP server indicating that the message has been successfully queued by the server. The reason that it is returned by MailKit is because some servers include identifiers that can be used for tracing telemetry session data and some developers find that useful.

Weird. I specifically used `SmtpClient` and I do get messages that were sent with it into my "Sent" folder. The e-mail is at `outlook.com`?

**Comment by jstedfast** [comment]
That is very non-standard behavior.
