### ISSUE TITLE
How to get folder id for imap server which doesn't have ImapCapabilities.ObjectID capabilities ?

### ISSUE THREAD

**Issue by aldayneko** [jstedfast/MailKit#1764]
Hello,

My imap server doesn't have ImapCapabilities.ObjectID capabilities. That's why when I call GetFoldersAsync with StatusItems.MailboxId, folder id is always null
However when I send imap command manually it returns the required ids
`
11 list "" "*" return (status (x-guid))
* LIST (\UnMarked) "/" Sent
* STATUS Sent (X-GUID ase97219a0eba6532354675421da3f223)
* LIST (\UnMarked) "/" Trash
* STATUS Trash (X-GUID ddvffb7219a2342353443645646a3f8rf4)
* LIST (\UnMarked) "/" Spam
* STATUS Spam (X-GUID 1234eba656ere345da33344434212342)
* LIST (\UnMarked) "/" Drafts
* STATUS Drafts (X-GUID 123dwerfg45423ef3rg24th356h43g3g)
* LIST () "/" INBOX
* STATUS INBOX (X-GUID 12233f4g4443g43g345g4545h45122d)
11 OK List completed (0.019 + 0.000 + 0.018 secs).
`
Is there any solution to retrieve this id ? I can't see how to do it using existing exposed interface from mailKit. Is that possible to send somehow raw imap command ?

**Comment by jstedfast** [comment]
X-GUID is not the same as OBJECTID. X-GUID is some sort of custom IMAP extension that I've never seen.

**Comment by aldayneko** [comment]
it's dovecot version 2.3

**Comment by jstedfast** [comment]
I can't find any documentation on any X-GUID IMAP feature.

Surprised Dovecot doesn't support OBJECTID. You should submit a feature request to the Dovecot developers to add that functionality.

X-\* features are typically not worth my time to support since they come and go frequently as they are experimental features that very few IMAP servers support; usually only implemented in 1 IMAP server while the author(s) of said server are in the process of drafting an official IMAP protocol extension for the IETF to review & eventually ratify/publish.

Seems like X-GUID might have been some sort of precursor to the official OBJECTID extension.
