### ISSUE TITLE
ImapClient 'silently' disposes?!?

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1795]
@jstedfast I just got a report from a 'new-to-me' real world problem: it appears that there could be situations where `ImapClient` disposes itself (for reason not know to my app) and my app would not know. Please see trace below:
```
2024-08-13 10:16:16:426 (xxxx) Mail.MailClient.MoveToAsync.Exception: mailAccount='aaa.bbb@ccc.com' System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ImapClient'.
   at MailKit.Net.Imap.ImapFolder.QueueOpenCommand(FolderAccess, CancellationToken)
   at Unusual.Mail.MailClient.MoveToAsync(Mail, MailFolder)
```
My app works of the assumptions that:
- `ImapClient` would never dispose 'by itself'
- only my app ever would dispose `ImapClient` and hence, should be aware of any 'dispose' cases (unless there really is a bug my code - which of course could be the case)

As first step(s) of my analysis I liked to understand:
- is my assumption "`ImapClient` would never dispose 'by itself'' correct?
- if my assumption is wrong: what would be the best way to trap such as case?

Thanks in advance

BTW: you might have guessed it ... this again was a MS365 mail account ;-)

**Comment by jstedfast** [comment]
> is my assumption "ImapClient would never dispose 'by itself'' correct?

Yes. ImapClient will never silently (or otherwise) dispose itself.

> if my assumption is wrong: what would be the best way to trap such as case?

Oof. The bane of every programmer since the dawn of software development.

I'd probably suggest adding some logging. If you create multiple ImapClient instances, I'd probably subclass ImapClient so that I could add an 'int' or Guid property to uniquely identify each ImapClient and then add logging to the .ctor/Dispose methods to see where these are getting called.

**Comment by DierkDroth** [comment]
Thanks @jstedfast 

Ok, next step: what would be the best way to detect that `ImapClient` was disposed (which is the problem in the case, right?!?). There are a couple of properties on `ImapClient`, but none of them would indicate .IsDisposed, no? `ImapClient.IsConnected`? `ImapClient.IsAuthenticated`? Else?

**Comment by jstedfast** [comment]
Most disposable objects don't have an IsDisposed-like property. A somewhat common practice is often to null out your member variable (if it's part of a class) once you dispose it.

Another option is to subclass ImapClient and either add the property to your subclass (and override the `Dispose(bool disposing)` method to update that property value to `true`, or in your case if you are just trying to add logging, you could just override the `Dispose(bool disposing)` method to log that the object got disposed.

In general, you shouldn't have to check if an object is disposed in your code because methods that act on that object should never be called to act on a disposed object in the first place (although, obviously, we've all had to debug issues where we were incorrectly operating on a disposed object at some point or another).

**Comment by DierkDroth** [comment]
> A somewhat common practice is often to null out your member variable (if it's part of a class) once you dispose it.
That's exactly what I'm doing ... which makes me pretty confident `.Dispose` was not triggered by my code.

So any of the `ImapClient.IsXXX` properties wouldn't cover what I'm looking for?

**Comment by jstedfast** [comment]
There's currently no public property that can be sued to determine the disposed state

**Comment by DierkDroth** [comment]
Thanks @jstedfast 

Hmm ... I'll look into subclassing `ImapClient` next then ...

**Comment by jstedfast** [comment]
If you override `Dispose(bool disposing)`, even the dotnet finalizer will call that.

So whether the ImapClient gets disposed due to a finalizer thread or from directly calling client.Dispose() or from a `using` statement, it will all cause the `Dispose(bool disposing)` method to be called.

**Comment by DierkDroth** [comment]
Thanks for clarification @jstedfast.

**Comment by jstedfast** [comment]
Have you found anything?

**Comment by DierkDroth** [comment]
Thanks for reaching out @jstedfast.

In a first step I cleared out some code on my end which seemed to be a bit fishy. I wanted to see if this actually would be the cause of trouble.

I closed his ticket for now and will get back to you if further research would be due...
