### ISSUE TITLE
Not receiving a MimeMessage sent on SmtpClient

### ISSUE THREAD

**Issue by bradykelly** [jstedfast/MailKit#180]
I'm just trying out MailKit for the first time, so I may be way off here, but I am using the Net.Pop3Client to pull a MimeMessage, and then send it to a new recipient. I am using the code below to send it, but it never appears in the recipient's gmail inbox:

    using (var smtp = new MailKit.Net.Smtp.SmtpClient())
    {
        smtp.Connect("smtp.gmail.com", 587, false);
        smtp.AuthenticationMechanisms.Remove("XOAUTH2");
        smtp.Authenticate(SmtpUser, SmtpPassword);

        message.To.Clear();
        message.To.Add(new MailboxAddress("Brady Kelly", SmtpRecipient));
        smtp.Send(message);
        smtp.Disconnect(true);
    }

The SmtpRecipient value is correct. I am using this with the built-in SMTP client and that works fine.

**Comment by jstedfast** [comment]
That looks correct, but make sure that the message does not have any Resent-From, Resent-To, Resent-Cc, etc. headers. If any of those headers are set, MailKit's SMTP implementation will use those instead of the normal From/To/Cc/Bcc headers.

If that's not the problem, try getting a log of the SMTP commands being sent:

```csharp
using (var smtp = new MailKit.Net.Smtp.SmtpClient(new ProtocolLogger("smtp.log")))
```

It's possible that the GMail SMTP server is rejecting the message for some reason and MailKit isn't properly catching the error(?).

**Comment by jstedfast** [comment]
I'll improve the docs to explain how it decides which sender and recipients to use when sending the message when you use `Send (MimeMessage message)`.

**Comment by jstedfast** [comment]
Oh, I bet I know what the problem is: You aren't setting the Sender or From header, so MailKit will use whatever the Sender or From header existed in the message downloaded from the POP3 server.

My guess is that since the email address that MailKit is choosing to use as the sender is not your email address, GMail is (silently?) rejecting it.

**Comment by bradykelly** [comment]
Thank you very much, Jeffrey. I have just tried again, with a proper sender, and all is running smooth as hell. I love MailKit!

**Comment by jstedfast** [comment]
Awesome! Glad you figured it out and love MailKit :-)
