### ISSUE TITLE
Problem to connect from Android by using SecureSocketOptions.SslOnConnect

### ISSUE THREAD

**Issue by NilsHoyer** [jstedfast/MailKit#1810]
I'm trying to connect from my .Net C# MAUI Android App to my IMAP provider using the mentioned SSL connection.

While this, I get a `MailKit.Security.SslHandshakeException`.

Inside my log, I found this:

    10:46:52:659	[System.err] error:10000044:SSL routines:OPENSSL_internal:internal error (external/boringssl/src/ssl/s3_both.cc:523 0x75f5a52803:0x00000000)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.handshake(ConscryptEngine.java:998)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:786)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:237)
    10:46:52:721	[System.err] 	at net.dot.android.crypto.DotnetProxyTrustManager.verifyRemoteCertificate(Native Method)
    10:46:52:721	[System.err] 	at net.dot.android.crypto.DotnetProxyTrustManager.checkServerTrusted(DotnetProxyTrustManager.java:29)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:264)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:570)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
    10:46:52:721	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1115)
    10:46:52:722	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1087)
    10:46:52:722	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
    10:46:52:722	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
    10:46:52:722	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
    10:46:52:722	[System.err] 	at com.android.org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:237)
    10:46:52:869	[System.err] Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb4000075ea2c9fc8: Failure in SSL library, usually a protocol error
    10:46:52:869	[System.err] error:10000044:SSL routines:OPENSSL_internal:internal error (external/boringssl/src/ssl/s3_both.cc:523 0x75f5a52803:0x00000000)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_do_handshake(Native Method)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:418)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.handshake(ConscryptEngine.java:972)
    10:46:52:869	[System.err] 	... 17 more
    10:46:52:869	[System.err] javax.net.ssl.SSLHandshakeException
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.Java8EngineWrapper.unwrap(Java8EngineWrapper.java:237)
    10:46:52:869	[System.err] Caused by: java.security.cert.CertificateException
    10:46:52:869	[System.err] 	at net.dot.android.crypto.DotnetProxyTrustManager.checkServerTrusted(DotnetProxyTrustManager.java:30)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:264)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:570)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1115)
    10:46:52:869	[System.err] 	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1087)
    10:46:52:870	[System.err] 	... 4 more

I'm using the same code and login in my Windows App and that works fine.

If you want, I can share my login information with you.

**Comment by jstedfast** [comment]
The issue seems to be in java code which is not part of MailKit.

**Comment by jstedfast** [comment]
I was at the doctor's office on my phone before, so it was difficult to type much of a response. I'm back at my desk now, so let me try to provide a (hopefully) more helpful response.

The issue seems to be this:

```text
10:46:52:869	[System.err] Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb4000075ea2c9fc8: Failure in SSL library, usually a protocol error
10:46:52:869	[System.err] error:10000044:SSL routines:OPENSSL_internal:internal error (external/boringssl/src/ssl/s3_both.cc:523 0x75f5a52803:0x00000000)
```

I'm not really sure what that means exactly, but it might be worth trying to play around with figuring out what SSL encryption options the server is using.

OpenSSL has a tool (s_client I think?) that you can use in diagnostic mode from your PC that will provide you with the server's supported SSL/TLS versions (e.g. SSLv3, TLS v1.0, v1.1, v1.2, v1.3), the cipher algorithms, and the hash algorithms.

You could also add some debug info to your app that works on PC that uses Console.WriteLine() to print out the SSL connection info that MailKit uses on the PC to make a successful connection:

* [client.SslProtocol](https://mimekit.net/docs/html/P_MailKit_Net_Imap_ImapClient_SslProtocol.htm) (singular)
* client.SslCipherAlgorithm
* client.SslCipherStrength
* client.SslHashAlgorithm
* client.SslHashStrength
* client.SslKeyExchangeAlgorithm
* client.SslKeyExchangeStrength

I think MailKit only allows setting [`client.SslProtocols`](https://mimekit.net/docs/html/P_MailKit_MailService_SslProtocols.htm) (plural), but that might be enough.

**Comment by NilsHoyer** [comment]
... so at the moment, you are not motivated to hunt a solution for this issue, correct?

**Comment by jstedfast** [comment]
Is there reason to believe the issue is with MailKit? You said it works on every other platform and the StackTrace you provided shows that the error is deep inside of Java code that sits below Microsoft's core .NET libraries that interoperate with Android's Java SDK.

Have you tried the suggestion I gave you in my previous comment? Have you gained any new information?

**Comment by NilsHoyer** [comment]
At home, I don't have an Internet connection ab outside mostly I have my Android device only. Because of this, it's not easy for me, but I do my best. 🙄

The c_client tool should analyze an SSL server, but I didn't find a binary for Android until now. Yesterday, I downloaded CMake to compile it. Maybe I can offer the requested answer within the next days.

But I didn't say, I would be able to use MailKit on multiple platforms. Until now, I use it on Windows only.

Until now, I tried Secure settings "Auto" only. Maybe I have more luck using a different one?

Maybe I will have one Sunday one hour time with my Notebook and an Internet connection to for the next tests...

**Comment by NilsHoyer** [comment]
Today, I spent one hour to find a solution or to provide more detailed information to you — without success.

But I believe, you should analyse this issue, because of this, I will not go ahead to find a solution for it.

Unfortunately, you are too ignorant, arrogant, and selfish to handle it. So I can't use MailKit on Android. Because of this, now I will buy a commercial toolbox for IMAP support.

**Comment by jstedfast** [comment]
I fully support your decision 👍

**Comment by NilsHoyer** [comment]
Thank you for confirming you are ignorant, arrogant.

**Comment by jstedfast** [comment]
Bye, Felicia

**Comment by NilsHoyer** [comment]
By labeling this issue with "not planned", you confirmed again your ignorance.

I believe, you still understood, it's not a server bug.

**Comment by NilsHoyer** [comment]
I tried to analyse this problem more detailed. If I'm right, the problem occurs while opening the `System.Net.Security.SslStream` in your `MailKit.Net.SslStrem`, which will be called from your `MailKit.Net.Imap.ImapClient` class inside the file `MailKit\MailKit\Net\Imap\AsyncImapClient.cs`.

If I use this following code, I can open an SSL stream on my Android device:

    #if ANDROID
        Java.Net.Socket socket = SSLSocketFactory.Default.CreateSocket(host, port);
        System.IO.Stream sslInputStream = SSLSocketFactory.Default.CreateSocket(host, port).InputStream;
        System.IO.Stream sslOutputStream = SSLSocketFactory.Default.CreateSocket(host, port).OutputStream;
    #endif

If I'm right, there are only some few changes inside the mentioned file needed to implement Android support into MailKit.

**Comment by jstedfast** [comment]
> If I'm right, the problem occurs while opening the System.Net.Security.SslStream

As I said, it sounded like a bug in the .NET libraries (or the Java libraries).

Your solution is what the System.Security SslStream .ctor should be doing if you are correct.

It should never be necessary to use Java.\* APIs in a cross-platform .NET library. In order to use those APIs, I would also need to target net8.0-android (which I do not as it should not be necessary since I am not using any Android UI APIs).

**Comment by NilsHoyer** [comment]
I believe, you understood the problem as well: The .Net does not work, like you want and you expect. Maybe there is a bug inside the code of Microsoft or of Google. Perhaps they do not fulfil the promised features of their software. But as far as I learned to tell them issues, they are too ignorant, arrogant, or selfish to fix them. Like you too…

That's the life: Other humans are not perfect, and they don't do everything we want. I accept this today and love them nevertheless. And if I can't do what I want on this base, I don't do it.

At the moment, I don't have food to eat something, but I accept this too. Maybe I will die, no problem: I love everyone like he shows him to me. 😉

**Comment by jstedfast** [comment]
MailKit's Imap/Pop3/SmtpClient APIs allow you to call `Connect`/`ConmnectAsync` methods using a `System.Net.Socket` or a `System.IO.Stream` instead of having MailKit create the socket (and make the low-level socket connection) itself.

If you need to on Android, you can work around this issue by creating the `Java.Net.Socket` and wrapping it in a custom `System.IO.Stream` implementation and then pass that to the ImapClient.Connect() or ConnectAsync() method and it should work just fine. Just note that if you use the SSLSocketFactory stuff, you'll need to use `SecureSocketOptions.None` or it will try to wrap the Stream with another SSL/TLS layer (which obviously won't work).

**Comment by NilsHoyer** [comment]
I believe, you understood: MailKit does not support Android.

And you decided not to implement support for Android.

So, it would be fair, if you add a note to your project, that Android is not supported by it.

**Comment by NilsHoyer** [comment]
I believe, the best solution would be an other ImapClient.Connect method with two parameters: InputStream and OutoutStream.

For the existing Connect method, maybe you can throw out an exception, if they will be called on Android with a hint, how to create the both streams on Android like I mentioned before here.

Indeed, this is at least one hour work for you, since ImapClient currently uses one stream for input and output together. So you would have to separate this.

Additional, you would have to accept: Wether .Net, nor your works is perfect. Or with other words: Are you able to accept, that absolutely nothing is perfect (you not, too)?
