### ISSUE TITLE
Syntax error in BODYSTRUCTURE. Unexpected atom token: 9.3736e+06

### ISSUE THREAD

**Issue by IChayka** [jstedfast/MailKit#1838]
**Describe the bug**

**Platform (please complete the following information):**
 - OS: Windows
 - .NET Framework: 4.7.1
 - MailKit Version: 4.8.0

**Exception**
```
MailKit.Net.Imap.ImapProtocolException: Syntax error in BODYSTRUCTURE. Unexpected atom token: 9.3736e+06
   в MailKit.Net.Imap.ImapEngine.ParseNumber(ImapToken token, Boolean nonZero, String format, Object[] args)
   в MailKit.Net.Imap.ImapUtils.<ReadNumberAsync>d__25.MoveNext()
```

**To Reproduce**
Exception occures when trying to fetch all messages.

**Code Snippets**
```csharp
            var messages = this.client.Inbox.Fetch(0, -1,
                MessageSummaryItems.Envelope | MessageSummaryItems.UniqueId | MessageSummaryItems.Flags | MessageSummaryItems.BodyStructure,
                headers).ToArray();
```

**Comment by jstedfast** [comment]
The problem is that your IMAP server responded to a query that should have sent a numeric integer value, but instead sent `9.3736e+06`

**Comment by jstedfast** [comment]
@IChayka are you also connecting to `mail.ru`?

**Comment by jstedfast** [comment]
I'm not going to support mail.ru because it appears to be a garbage IMAP server. (see https://github.com/jstedfast/MailKit/issues/1234 for another an example of an unfixable mail.ru issue)

The number of work-arounds I have already had to implement for mail.ru + the fact that it does not support any SEARCH criteria just goes to show it's not worth the effort to support it at all.

See also: https://ru.stackoverflow.com/questions/289544/mail-ru-imap-unsupported-search-criterion
