### ISSUE TITLE
DeleteAllMessages not working on Pop3Client 

### ISSUE THREAD

**Issue by bradykelly** [jstedfast/MailKit#184]
I am trying to clear a mailbox, with the method below (excuse the vb, not my fault):

    Public Sub DeleteAllMessages()

        If _pop3Client Is Nothing Then
            _pop3Client = BuildPop3()
        End If

        If Not _pop3Client.IsConnected Then
            ConnectPop3()
        End If

        _pop3Client.DeleteAllMessages()
        _pop3Client.Disconnect(True)

    End Sub

Yet `GetMessageCount` still always returns a 7, i.e nothing seems to be getting deleted. Then, I don't see any DELE command in the log file written:

	Connected to pop://mail.amadigital.com:110/?starttls=when-available
	S: +OK POP3
	C: CAPA
	S: +OK CAPA list follows
	S: USER
	S: UIDL
	S: TOP
	S: .
	C: USER process@amadigital.com
	S: +OK Send your password
	C: PASS ADproc14
	S: +OK Mailbox locked and ready
	C: CAPA
	S: +OK CAPA list follows
	S: USER
	S: UIDL
	S: TOP
	S: .
	C: QUIT
	S: +OK POP3 server saying goodbye...

My own `DeleteAllMessages` is the only method called, so I know only this method writing to the log.

**Comment by jstedfast** [comment]
The reason that `DeleteAllMessages()` is not doing anything is because I had (apparently wrongly) assumed that consumers of the API would call `GetMessageCount()` before doing anything (in general, doing anything without knowing the message count is impossible).

When `GetMessageCount()` is called, it caches the message count which is later used for validating index arguments to the various methods that take indexes as well as using it in the `DeleteAllMessages()` case to determine how many messages there are to delete.

Since it is clear that this assumption was wrong, I have modified Pop3Client to query the message count itself automatically once the client is authenticated. This means that I can now have a `Count` property instead of forcing consumers of the API to call `GetMessageCount()` and so I have also now [Obsolete]'d the `GetMessageCount()` method.

**Comment by bradykelly** [comment]
Thanks Jeffrey. Looks like that might have had an impact on my deletes for single messages as well, but that "magically' vanished, I think because I started calling GetMessageCount before calling delete.

**Comment by jstedfast** [comment]
No problem. I've just released MailKit 1.0.16 with this fix to nuegt.org as well.
