### ISSUE TITLE
Manage more recipients and SmtpCommandException. 

### ISSUE THREAD

**Issue by Didacuss** [jstedfast/MailKit#185]
Hi, I have this question.
In my message, there are two recipients, one has a correct email address and the other has an incorrect email address. So I aspect that Send method raises an exception but it’s not true, furthermore I see that SmtpCommandException has a MailBox property that: 

“This property will only be available when the MailKit.Net.Smtp.SmtpCommandException.ErrorCode value is either MailKit.Net.Smtp.SmtpErrorCode.SenderNotAccepted or MailKit.Net.Smtp.SmtpErrorCode.RecipientNotAccepted and may be used to help the user decide how to proceed.”

However, if there are more emails incorrect ? Where can I find this information?

Thanks in advance.
Regards
Diego Parolin.

**Comment by jstedfast** [comment]
If the addresses are wrong and you are not getting an exception, then that suggests that the SMTP server is not returning an error when MailKit sends the RCPT TO commands.

To verify this, you can try getting a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog).

As far as there only being a single MailboxAddress on SmtpCommandException: that's because of the way the SMTP protocol works. a RCPT TO command is sent for each recipient and the first recipient that fails, the exception gets thrown and the address that failed is stuffed into the SmtpCommandException.

**Comment by gbrunton** [comment]
@jstedfast 
Can you help me understand what will happen in the following use cases when the server recognizes that an email address is not valid because the recipient is not accepted.

**Use Case 1**
```
mimeMessage.To.AddRange(new []
{
	new MailboxAddress("valid", validAddress1),
	new MailboxAddress("not-valid", notValidAddress),
	new MailboxAddress("valid", validAddress2)
});
smtpClient.Connect(....);
smtpClient.Send(mimeMessage);
```
I believe a SmptCommandException will be thrown. If that's true, should I assume that the valid addresses did not get the email?


**Use Case 2**
```
mimeMessage.To.AddRange(new []
{
	new MailboxAddress("not-valid", notValidAddress1),
	new MailboxAddress("not-valid", notValidAddress2)
});
smtpClient.Connect(....);
smtpClient.Send(mimeMessage);
```
I believe an exception will be thrown but if it's a SmptCommandException ex, then will the ex.Mailbox.Address equal the notValidAddress1 value and there won't be any reference to the notValidAddress2 value?

Forgive me if this is the wrong place to ask this question. I'm happy to move it somewhere else.
