### ISSUE TITLE
How to quicly check for deleted messages

### ISSUE THREAD

**Issue by jacargentina** [jstedfast/MailKit#214]
I have my IMAP inbox with 10.000 messages.

My current mail client implementation is very slow when i delete a given message: i do a complete fetch, to remove from my cache those messages that where there and no more. This is not quick.

I've tried doing this:

    var deleted = folder.Search(MailKit.Search.SearchQuery.Deleted);

But, the list returned is empty. Which would be a quick way to do that?

**Comment by jstedfast** [comment]
What you want to do is add event handlers for the `MessageFlagsChanged` event and the `MessageExpunged` event.

For GMail, with their default configuration, you probably won't get a FlagsChanged event because they immediately move messages that get marked for deletion into their `Trash` folder (which is why doing a `Search()` for deleted messages returns an empty list - see https://github.com/jstedfast/MailKit/blob/master/FAQ.md#GMailHiddenMessages).

In the `MessageFlagsChanged` event handler, you'll want to sync those new set of message flags to your local cache of message summaries.

In the `MessageExpunged` event, you will want to remove the message summary at the given index from your cache.

There should never be a need to requery your local cache of message summaries unless the UidValidity value changes (there's a UidValidityChanged event you can listen to for that, but it will *rarely* ever be called, especially for GMail).

Hope that helps.

**Comment by jacargentina** [comment]
Jeffrey: How to handle the case when in a different email client, i open my inbox, and insted of delete, i move some random X messages over there...

Then i open my current mailkit c# client (which has is own disk cache), and i need to sync that cache to also move those X random messages to where they are now?

**Comment by jstedfast** [comment]
There's 2 scenarios:

1. Your MailKit client and your other email client both have the `Inbox` folder open when the other email client moves messages X, Y, and Z out of the Inbox and into some other folder.
2. Your MailKit client does not have the Inbox folder open when the messages get moved out of the Inbox.

In the first scenario, if you listen for the `MessageExpunged` event on the `Inbox`, you'll get notified when those messages are moved and so you'll be able to remove them from your local cache for the `Inbox` folder. You won't know where they were moved to, but that doesn't matter - you'll just use a process similar to the solution to the second scenario when you eventually open the destination folder.

In the second scenario, when you open the `Inbox` with the MailKit client, you will want to sync changes since the previous session. You'll want to do this no matter what, even if you don't know that another client moved messages out of the `Inbox` precisely because you don't know what other clients may have done (or if the server may have delivered new mail, etc).

So what you'll want to do is the following sequence:

#### Step 1

Get a list of UIDs in the folder:

```csharp
var uids = folder.Search (SearchQuery.All);
```

#### Step 2

Compare that list with your local cache and figure out which messages have been removed from the server and which messages have been added.

For each UID that no longer exists on the server, remove it from your local cache.

For each UID that your cache does not already know about, copy it to another list which we'll then use in a later step.

#### Step 3

Fetch the flags for each of the message summaries in your cache.

```csharp
// Note: optionally use the MessageSummaryItems.UniqueId as well if lookups are easier based on UID instead of index
var summaries = folder.Fetch (knownUids, MessageSummaryItems.Flags);
```

Iterate through all of these summaries and update the `Flags` value of each of your cached message summaries.

At this point, all of the message summary information in your cache should be fully up-to-date.

#### Step 4

Fetch the message summary info for the messages that have been added since your last session.

```csharp
// Note: what items you request here depends on what you want to cache
var summaries = folder.Fetch (uids, MessageSummaryItems.UniqueId | MessageSummaryItems.Full | MessageSummaryItems.BodyStructure);
```

Now add these items to your cache and you have successfully managed to resync your cache with the server.

Hope that helps.

**Comment by jacargentina** [comment]
Your response greatly helps me understand how mailkit/IMAP protocol both work. 

Btw, one more doubt: currently i'm using:

    var currentMsgs = folder.Fetch( ... )  

to get the summaries to be cached and browsed on the ui.

Now that u told me about doing:
    var uids = folder.Search (SearchQuery.All);

I'm questioning myself: what is the difference (pros/cons) of each one. Any advice ?

**Comment by jstedfast** [comment]
You can use either `Search (SearchQuery.All)` or `Fetch (0, -1, MessageSummaryItems.UniqueId)` to get the full list of UIDs in a folder, but the `Search()` should theoretically be more efficient since all it does is return a list of UIDs (and if the server supports ESEARCH, it'll be compacted as well).

To illustrate what I mean, here's what you could expect from each of the methods:

The `Fetch()` query will return something like the following response:

```
* 1 FETCH UID 10
* 2 FETCH UID 11
* 3 FETCH UID 12
...
* 100 FETCH UID 109
```

In contrast, the `Search()` query will return something more like this:

```
* SEARCH 10 11 12 ... 109
```

Bandwidth-wise, it's more efficient. However, it gets *even more* efficient if the server supports the `ESEARCH` extension:

```
* ESEARCH (TAG "A0001") UID 10:109
```

I would recommend using `Search()` instead of `Fetch()` to get the list of UIDs in a folder.

**Comment by jacargentina** [comment]
One more thing: doing **Step 3** really takes a lot of time. I have 18.105 messages on the Inbox, and every time i click on any given folder on the UI, i do all this logic (so the user sees the real updated latest status of that folder messages).

So, if nothing changes, step 3 always re-fetches all messages flags, and i must loop over cached message flags to apply any changes.

I can't believe this is what any other imap clients do? May be there is something i'm missing....

**Comment by jstedfast** [comment]
One thing you could do is to do `Step 4` before doing `Step 3` (which order you do those 2 steps in doesn't matter) so that you can show any new messages that the user got sooner. Then you could do `Step 3` incrementally (100 messages at a time?) to allow windows of time where the user could select a message and have your client download the message between chunks of flag updates.

There's actually more optimized ways of doing this whole process if the server supports the `CONDSTORE` and/or `QRESYNC` extensions (which I think GMail supports `CONDSTORE` at least?). I'll try to document these more optimized approaches once I have time to sit down and think things through. Basically, `CONDSTORE` adds a `mod-sequence` metadata value for each message (that you'll want to make sure you request in your `Fetch()`). The idea of this `mod-sequence` value is that you can use it to only request changes after a certain value. For example, if the last time you opened the `Inbox`, it had a `mod-sequence` value of `100`, then you can requested changes since revision `100` and the server will tell you what chanced since then, this way you don't have to resync all the flags for all messages for example, you could just say "hey, what flag changes have happened since revision 100?" and it'll say "message #56 had the `\Answered` flag set on it and message #72 was marked as `\Seen`" thus drastically reducing the query overhead that you are having with the current approach that I documented above.

**Comment by jacargentina** [comment]
So this should to the work?

    var changes = folder.Search(MailKit.Search.SearchQuery.ChangedSince(   HighestModSeq_SavedOnMyCache    ));

Where **HighestModSeq_SavedOnMyCache** is the number to be saved on the disk cache.

**Comment by jstedfast** [comment]
Correct. I'll have to play around with stuff a bit tonight if you don't figure out the finer details of it before I get a chance to do it, but yea, that's the general idea of what I was thinking.

I think what you'll want to do is something like this:

#### Step 1

Same as before, because, unfortunately, `Search (MailKit.Search.SearchQuery.ChangedSince (cachedHighestModSeq))` will not be able to tell you about expunged messages :-(

#### Step 2

Same as before.

#### Step 3

```csharp
var cachedUids = GetListOfCachedUids ();
var changed = folder.Search (cachedUids, MailKit.Search.SearchQuery.ChangedSince (cachedHighestModSeq));
var summaries = folder.Fetch (changed, MessageSummaryItems.Flags | MessageSummaryItems.ModSeq);

foreach (var summary in summaries) {
    cached[summary.Index].ModSeq = summary.ModSeq;
    cached[summary.Index].Flags = summary.Flags;
}
```

#### Step 4

Same as before.

(once again, the order of Steps 3 and 4 are up to you).

I think you'll want to keep track of the modseq for each message as well, but I'm not 100% sure that's necessary unless you plan to support offline usage where the user might update flags on a message in the offline state. In that case, the modseq value might be useful when syncing flag changes back up *to* the server.

**Comment by jatinpateljeckrose** [comment]
This Post helps me a lot!
One Question is, Is there any better way if mod-sequence is not supported?. Do I need to loop thru all the messages, that is the only way?

**Comment by jstedfast** [comment]
Correct, if the server doesn't support MODSEQ, then you'll need to manually loop thru the full list of messages to figure out what has changed.

See https://github.com/jstedfast/MailKit/issues/214#issuecomment-121624653 for more details about how to do this.
