### ISSUE TITLE
Mark an email as read POP3

### ISSUE THREAD

**Issue by ericscaglioni** [jstedfast/MailKit#218]
Hi. I'm developing a desktop application that monitors an email and gets its messages.
However, everytime I'm gonna read them, I'm obligated to read every email again and again.
Is there a way to set them as READ and then only read the UNREAD emails?

Please help me

**Comment by jstedfast** [comment]
POP does not support read/unread status, it only supports deleting messages.

If you want to track read/unread status, you'll need to keep a log of which messages you've already "read".

If the POP3 server supports the UIDL extension, using the UIDs is probably the simplest way. Otherwise you'll have to use something else... like an MD5 sum of a few choice message headers (avoid headers like `Status` and `X-Status` as they may change between downloads).

To track by uids, you might do something like this:

```csharp
void DownloadUnreadMessages (HashSet<string> known)
{
    using (var client = new PopClient ()) {
        client.Connect ("pop.gmail.com", 993, true);
        client.Authenticate ("username", "password");

        if (client.Capabilities.HasFlag (Pop3Capabilities.Uidl)) {
            var uids = client.GetMessageUids ();
            for (int i = 0; i < client.Count; i++) {
                if (known.Contains (uids[i]))
                    continue;

                var message = client.GetMessage (i);
                known.Add (uids[i]);
            }
        } else {
            // good luck!
        }

        client.Disconnect (true);
    }
}
```

**Comment by ericscaglioni** [comment]
Thank you man!
