### ISSUE TITLE
Not able install MailKit

### ISSUE THREAD

**Issue by VaikeshLeo** [jstedfast/MailKit#223]
Not able to install __MailKit__ in my project.

**Install-Package : Could not install package 'MailKit 1.2.8.0'. You are trying to install this package into a project that targets 
'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files 
that are compatible with that framework. For more information, contact the package author.**
**At line:1 char:2**
**+ Install-Package MailKit**
**+ ~~~~~~~**
**+ CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException**
**+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand**

My current profile : **PCL 4.5 - Profile78**

How can i solve it ?
Any idea ?

![pm](https://cloud.githubusercontent.com/assets/12531760/9032027/fab13602-39d7-11e5-927d-09c2e77073e3.JPG)

**Comment by jstedfast** [comment]
Unfortunately, MailKit does not support Windows Phone 8 - so this is not possible. I would recommend changing the PCL profile of your project to something that supports Windows Phone 8.1 instead.

**Comment by mrward** [comment]
Therein lies the problem since I cannot find a PCL profile which you can choose that makes the project compatible.

MimeKit is fine. If it was targeting Windows Phone 8.1 (wpa81) it would work too.

    MimeKit: portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10

However MailKit is a problem. It's PCL profile is:

    MailKit: portable-netcore451+wpa81

netcore451 == win81 in NuGet land. I do not see a PCL profile that would work with the above. If I use Profile259, which does support Windows Phone 8.1 my PCL project would have a NuGet style PCL profile of:

    portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10

How NuGet works is that it looks at every target framework for the PCL profile in the NuGet package and they all need to be compatible with the frameworks in the PCL project. The Mono and Xamarin frameworks are optional so can be ignored. Since the MailKit NuGet package says nothing about net45 support, for example, then NuGet determines it to be incompatible.

The nearest PCL profile which could work is possibly `Profile32 win81+wpa81` but that seems to not be supported by the Xamarin frameworks. Also testing it on Windows it fails to install MimeKit since NuGet seems to think it is incompatible which is presumably because MimeKit does not support wpa81. If I remove the MimeKit dependency from MailKit then I can install it into a PCL project targeting Profile32.

**Comment by jstedfast** [comment]
The problem is that the WindowsPhone PCL profiles that have networking support are completely at odds with the System.Net namespace (i.e. they use Windows.Networking which does not exist EXCEPT in WindowsPhone-specific PCL profiles). There's no way I can possibly support a generic PCL profile with MailKit that is compatible with desktop and/or Xamarin.Android/iOS.
