### ISSUE TITLE
Unexpected token in IMAP response: ')'

### ISSUE THREAD

**Issue by githubxiaowen** [jstedfast/MailKit#233]
It ran smoothly last week,But now the sentence IList<IMessageSummary> list = inbox.Fetch(0, -1, MessageSummaryItems.Full) throws an exception "Unexpected token in IMAP response: ')' ",Can you help me with that? Here are the code and mail log:
> client.Connect(server, 993, SecureSocketOptions.SslOnConnect);
>client.Authenticate(loginemail, password);  var inbox = client.Inbox;
>inbox.Open(FolderAccess.ReadOnly);
>List<IMessageSummary> list = inbox.Fetch(0, -1, MessageSummaryItems.Full); 

>Connected to imaps://imap.qq.com:993/
S: * OK [CAPABILITY IMAP4 IMAP4rev1 IDLE XAPPLEPUSHSERVICE ID UIDPLUS AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready
C: A00000000 AUTHENTICATE LOGIN
S: + VXNlciBOYW1lAA==
C: OTQyOTExNzI2QHFxLmNvbQ==
S: + UGFzc3dvcmQA
C: eHh3ODgzNzIx
S: A00000000 OK [CAPABILITY IMAP4REV1 X-NETSCAPE NAMESPACE MAILBOX-REFERRALS SCAN SORT THREAD=REFERENCES THREAD=ORDEREDSUBJECT MULTIAPPEND ID UIDPLUS] User <login> authenticated
C: A00000001 NAMESPACE
S: * NAMESPACE (("" "/")) NIL NIL
S: A00000001 OK Success
C: A00000002 LIST "" "INBOX"
S: * LIST (\HasNoChildren) "/" "INBOX"
S: A00000002 OK LIST completed
C: A00000003 EXAMINE INBOX
S: * 71 EXISTS
S: * 0 RECENT
S: * OK [UNSEEN 25]
S: * OK [UIDVALIDITY 1316352875] UID validity status
S: * OK [UIDNEXT 5790] Predicted next UID
S: * FLAGS (\Answered \Flagged \Deleted \Draft \Seen)
S: * OK [PERMANENTFLAGS ()] No permanent flags permitted
S: A00000003 OK [READ-ONLY] EXAMINE complete
C: A00000004 FETCH 1:* FULL
......
......
S: * 57 FETCH (FLAGS () RFC822.SIZE 23408 INTERNALDATE "19-Aug-2015 08:16:00 +0800" ENVELOPE ("Wed, 19 Aug 2015 00:15:28 +0000" "=?GBK?B?VGhhbmsgeW91IGZvciB5b3VyIHBhcnRpY2lwYXRpb24=?=" (("=?GBK?B?Q291cnNlcmE=?=" NIL "noreply" "coursera.org")) (("=?GBK?B?Q291cnNlcmE=?=" NIL "noreply" "coursera.org")) (("=?GBK?B?Q291cnNlcmE=?=" NIL "noreply" "coursera.org")) (("=?GBK?B?OTQyOTExNzI2?=" NIL "942911726" "qq.com")) NIL NIL NIL "<0000014f434f8160-13f00108-f91f-4a4d-a508-6db87a6fd026-000000@email.amazonses.com>"))
S: * 58 FETCH (FLAGS (\Seen) RFC822.SIZE 806 INTERNALDATE "19-Aug-2015 16:04:46 +0800" ENVELOPE ("Wed, 19 Aug 2015 16:04:20 +0800" "=?GBK?B?suLK1A==?=" (("=?GBK?B?ssbO8bK/?=" NIL "942911726" "qq.com")) (("=?GBK?B?ssbO8bK/?=" NIL "942911726" "qq.com")) (("=?GBK?B?ssbO8bK/?=" NIL "942911726" "qq.com")) NIL NIL NIL "<C4WSGXKOWVT4.Y638TNW10P151@XXW-PC>"))
>

**Comment by jstedfast** [comment]
The problem is that your IMAP server is broken.

The ENVELOPE should consist of the following fields:

1. Date
2. Subject
3. From
4. Sender
5. Reply-To
6. To
7. Cc
8. Bcc
9. In-Reply-To
10. Message-Id

The problem is that your server is only returning 9 of the 10 fields, hence why MailKit does not expect the ')' token that ends the ENVELOPE response.

For example, if you examine the response for message 58:

Date = `"Wed, 19 Aug 2015 16:04:20 +0800"`
Subject = `"=?GBK?B?suLK1A==?="`
From = `(("=?GBK?B?ssbO8bK/?=" NIL "942911726" "qq.com"))`
Sender = `(("=?GBK?B?ssbO8bK/?=" NIL "942911726" "qq.com"))` 
Reply-To = `(("=?GBK?B?ssbO8bK/?=" NIL "942911726" "qq.com"))`
To = `NIL`
Cc = `NIL`
Bcc = `NIL`
In-Reply-To = `"C4WSGXKOWVT4.Y638TNW10P151@XXW-PC"`

But there is no value for the Message-Id...

The IMAP specification states the syntax as:

```
envelope        = "(" env-date SP env-subject SP env-from SP
                  env-sender SP env-reply-to SP env-to SP env-cc SP
                  env-bcc SP env-in-reply-to SP env-message-id ")"

env-bcc         = "(" 1*address ")" / nil

env-cc          = "(" 1*address ")" / nil

env-date        = nstring

env-from        = "(" 1*address ")" / nil

env-in-reply-to = nstring

env-message-id  = nstring

env-reply-to    = "(" 1*address ")" / nil

env-sender      = "(" 1*address ")" / nil

env-subject     = nstring

env-to          = "(" 1*address ")" / nil
```

**Comment by jstedfast** [comment]
FWIW, it looks like message 57 has a valid ENVELOPE, it's just message 58 that does not.
