### ISSUE TITLE
1000's Connections

### ISSUE THREAD

**Issue by tonytone999** [jstedfast/MailKit#237]
Can I ask what would be the best way to approach maintaining 100 or 1000's of connections?  I want to monitor multiple IMAP accounts via IDLE.  Thanks!

**Comment by jstedfast** [comment]
I've been told that MailKit can handle 1000's of connections as it stands right now. I'm not sure if the people who told me this are using threads + client.Idle() or if they are using the client.IdleAsync() method by itself. I would probably recommend using a thread as instinct tells me that will scale better, but I honestly don't know as I personally have no need to scale to that many connections.

The guys in issue #189 are working on a port of MailKit to be be async from the ground up instead of using async wrapper methods like it does now. You could try using their port as it is also their need to make 1000's of connections.

**Comment by quentez** [comment]
We are able to maintain 1000's of connections using a threaded approach. We'll still need a fully async port sometime in the future, but the current lib can definitely be used as it is in such scenarios.
