### ISSUE TITLE
NTLM authentication does not work with Exchange 2013

### ISSUE THREAD

**Issue by jonnymaboy** [jstedfast/MailKit#265]
The new version of shared exchange 2013 has got NTLM authentication mechanism which somehow breaks the imap mail kit authentication. The error is authentication error.

If like said for other tickets i remove NTLM  like authenticationmechanism.remove("NTLM ") then all works fine. 

Would it not be better to scan for auth mechanism and use the correct one instead of having to edit code for removing these when finding them.

thanks

**Comment by jstedfast** [comment]
I'll need a protocol log to figure out why this happens.

Normally MailKit does try other authentication mechanisms if the first one it tries fails.

**Comment by jstedfast** [comment]
You can follow these directions on how to get a protocol log: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog

**Comment by jonnymaboy** [comment]
i have done as requested

Connected to imap://<domain name>:143/?starttls=when-available
S: * OK The Microsoft Exchange IMAP4 service is ready. Using Client Access Server 4.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 STARTTLS
S: A00000001 OK Begin TLS negotiation now.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 AUTHENTICATE NTLM
S: +
C: <encryted code>
S: <encryted code>
C: <encrypted code>
S: A00000003 NO AUTHENTICATE failed.
C: A00000004 AUTHENTICATE PLAIN
S: +
C: <encryted code>
S: A00000004 NO AUTHENTICATE failed.
C: A00000005 LOGIN username password
S: A00000005 NO LOGIN failed.

**Comment by jonnymaboy** [comment]
as soon as i then do:  client.AuthenticationMechanisms.Remove("NTLM") it all works

**Comment by jstedfast** [comment]
It looks to me like MailKit is correctly falling back to trying other authentication mechanisms, but the server is rejecting the attempts, possibly because it has decided that once a failed attempt has occurred, it will reject all following attempts during the same session.

There's not anything MailKit can do to work around that behavior.

The only thing I can do is fix the NTLM logic (if there is a bug there), but in order to do that I need a test case and I need to know exactly what the server is responding with.

**Comment by jstedfast** [comment]
At the very least, I need the base64 data segments sent between MailKit and the IMAP server for the NTLM authentication command (you can leave out the PLAIN and LOGIN commands since that isn't very secure).

Since you haven't responded, I suspect you didn't realize I needed that info.

My hands are completely tied until I get that.

**Comment by jstedfast** [comment]
Is it possible that the problem is the same as described here? http://msitpros.com/?p=2031

**Comment by jonnymaboy** [comment]
hi sorry i didnt see the latest message. As i have got it working with remove ntlm im not to concerned.  I think your comment above is probably correct

" like MailKit is correctly falling back to trying other authentication mechanisms, but the server is rejecting the attempts, possibly because it has decided that once a failed attempt has occurred, it will reject all following attempts during the same session"

thanks

**Comment by ahanley** [comment]
I have also experienced this issue and can provide a detailed log of the communication if that can help.  Turning off NTLM authentication did fix it for me as well but i assume this is not a desired resolution and fixing the underlying cause if there is one would be favoured.    Let me know if you want me to email you the log or how you want me to get it too you.

**Comment by jstedfast** [comment]
Yes, I'd be interested in logs that I can use - you can send them to jestedfa@microsoft.com (don't post to github unless you don't care about the info being public).

**Comment by jstedfast** [comment]
I'm wondering if this new NTLM patch fixes NTLM auth for you guys.
