### ISSUE TITLE
Question about Pop3ClientGetMessage(uniqueId);

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#283]
Why is the Pop3Client.GetMessage(uniqueId) obsolete when the Pop3Client.GetMessageUids() isn't?

And what is otherwise the best method to retrieve chunks of messages.. for example 100 messages in one go.

Greetings,
Kees van Spelde

**Comment by jstedfast** [comment]
GetMessage(uniqueid) is obsolete because it requires MailKit to track UIDs which is awkward and memory expensive.

GetMessageUids() allows you to track uids yourself.

The way to use GetMessageUids is this:

```csharp
var uids = client.GetMessageUids ();
for (int i = 0; i < client.Count; i++) {
    if (UniqueIdIsAlreadyDownloaded (uids[i]))
        continue;
    var message = client.GetMessage (i);
    message.WriteTo (path);
    AddUniqueIdToDownloadedList (uids[i]);
}
```

If you want to retrieve 100 messages in a row, you can use `client.GetMessages (startIndex, count);` or you can use `client.GetMessages (new int[] { index1, index2, index3, ... });`

Hope that helps.
