### ISSUE TITLE
The best way to copy the MimeMessage object

### ISSUE THREAD

**Issue by Sicos1977** [jstedfast/MailKit#284]
Hi,

I have made a class that inherits the MimeMessage class like this

public class Email2StorageMessage : MimeMessage
{
...
}

In this class I override some methods with the new keyword and I have added some methods that are not in the MimeMessage class.

In some other code I retrieve a message (IMAP) like this

foreach (var uniqueId in uniqueIds)
{
  try
 {
      var message = folder.GetMessage(uniqueId);
....
}

What is the best way to load the message object into my own Email2Storage class. I know that it has a static Load method that is in the MimeMessage class but this method needs a Stream. I also know that there is a folder.GetStream (IMailFolder) method but that one expects an section parameter.

I could do it with a MemoryStream but that will consume a lot of memory because everything is loaded into Memory... this is something that I'm trying to avoid.

Any help would be appreciated.

Greetings,
Kees

**Comment by jstedfast** [comment]
To get a stream from a MimeMessage, you could use message.WriteTo (stream), although that will require either using a MemoryStream as you mentioned or a FileStream located in some tmp directory.

As you've also discovered, there are several folder.GetStream() methods that you could potentially use. The best one to use for hat you want to do is probably http://www.mimekit.org/docs/html/M_MailKit_Net_Imap_ImapFolder_GetStream_2.htm (which seems to be the one you mentioned). In your case, the `section` string that you will want to use is simply `string.Empty`.

But even given that, I'm not sure that will completely help since `MimeMessage.Load()` will always return MimeMessage and not Email2StorageMessage, so some changes to MimeKit may be needed in order to support what you are trying to do, I'm just not sure what the best way to do it is.

**Comment by Sicos1977** [comment]
I think I found the answer for my problem on stackoverflow

http://stackoverflow.com/questions/729527/is-it-possible-to-assign-a-base-class-object-to-a-derived-class-reference-with-a

Going to try that one out. I want to avoid in making changes to the MimeKit library... otherwise I have to do it every time when library is updated. Another solution could be Extension methods but that doesn't work with properties.

**Comment by jstedfast** [comment]
Okay, good luck!
