### ISSUE TITLE
Storing MimeMessage in data base

### ISSUE THREAD

**Issue by infinitimods** [jstedfast/MailKit#294]
Hi Jeff,

I'm trying to store MimeMessage inside the database if for whatever reason our mail server may be down. Have the following fields defined in my sql server: from, to, subject and body.

I'm storing 'from' and 'to' fields in this format in database: {MyCompany,mail@mycompany.com} and body, bodyBuilder.ToMessageBody().ToString() as nvarchar(max). Now that I have it stored, I want to be able to retrieve the fields and re-compose the original MimeMessage. I can re-parse the 'from' and 'to' fields, set the subject, but how do I simply set the body of the message since I already have stored in the database in this format "Content-Type: multipart/mixed; boundary=........." ? Thank you for your help

**Comment by jstedfast** [comment]
Okay, first, I'm going to have to recommend not using ToString() to serialize the message body.

What you want to use is the `WriteTo(Stream)` method. ToString() is for debugging purposes only because it makes assumptions about the charset (it always serializes in iso-8859-1).

If you use `WriteTo(Stream)`, you can de-serialize the output by using `MimeEntity.Load(Stream)`.

Hope that helps.

**Comment by infinitimods** [comment]
Ah! I see it! Thank you so much Jeff!
