### ISSUE TITLE
Add the original mail response

### ISSUE THREAD

**Issue by javierpv** [jstedfast/MailKit#296]
Hi, How I can add to the original message response ?, the original message is a message with HTML content.

Thanks.

**Comment by jstedfast** [comment]
I'm not sure what you are asking... can you elaborate?

**Comment by javierpv** [comment]
Yes, sorry for my English.
I need to respond to a message, the body of the email must have the mail that I will send and also the mail reply,

I've seen other pages the solution you propose
[http://stackoverflow.com/questions/31460653/quote-original-message-in-a-reply-using-mailkit](url)

But what I want is not correct because it responds to an email containing images, paragraphs, tables, but does not send good mail.

Shows no content, if I respond to an email with plain text if it serves the solution you've given

**Comment by jstedfast** [comment]
This is really hard to do which is why I didn't go into the details of how to do it on the stackoverflow question.

This is something that you will have to figure out on your own :-\

But I can start you off by saying that you will need to construct a `MultipartRelated` that contains your `TextPart` containing your reply HTML and also attach all of the images in the original message so that they show up in the reply email.

I would also recommend reading http://www.mimekit.org/docs/html/WorkingWithMessages.htm - take special note of the HtmlPreviewVisitor to see how to implement a MimeVisitor since you'll probably want to use a custom MimeVisitor class to create your reply (e.g. to clone the original message's `MultipartRelated`).

**Comment by javierpv** [comment]
Thanks for the answer.
But I do not get include the original message in the reply.
If included as an attachment gmail looks good, but Outlook or Apple Mail does not see well, they look like an attachment.

**Comment by jstedfast** [comment]
Make sure to set the ContentDisposition to `inline` and not `attachment`.

**Comment by javierpv** [comment]
Hi, I do not get it.

var message = new MimeMessage ();
var originalMessage= ObtainMessage(reply.InReplyTo);

how do i get the var message contains originalMessage in the message.Body?

**Comment by jstedfast** [comment]
I don't understand what you are asking. Are you asking how to embed the originalMessage inside message?

```csharp
message.Body = new MessagePart () {
    ContentDisposition = new ContentDisposition (ContentDisposition.Inline),
    Message = originalMessage
};
```

**Comment by javierpv** [comment]
result is the same, the original message show me like an attachment.
I want the result would be:

to: example@gmail.com
from: initial@gmail.com
subject: RE: hello

Hello
-------------------------------------------------
to: initial@gmail.com
from: example@gmail.com
subject: hello

Hello my friend.

**Comment by jstedfast** [comment]
Sorry, if what I showed you doesn't work, then I don't know how to get what you want. You'll have to look at how your favorite email client does it and try to reproduce the results.
