### ISSUE TITLE
Question about downloading attachments.

### ISSUE THREAD

**Issue by karaliolio** [jstedfast/MailKit#303]
Hello, I have the following issue.

I'm using the IMAP protocol and the Fetch() method to get some emails.
Some of them have attachments in the form of BodyPartBasic. 
I was wandering if there is a way to download the attachments without having to make a call to the server to get the BodyPart like this:

IMessageSummary message = inboxFolder.Fetch(messageIDs, MessageSummaryItems.BodyStructure)[0];
client.Inbox.GetBodyPart(email.UniqueId, message.Attachments.FirstOrDefault());

I have created my own EmailMessage class and I wish to save the attachments and to be able to download them when I want without having to make requests to the server for each of them. 
This is possible if I use the GetMessage() method instead of Fetch(), because that way I get MimeMessage object, which have attachments of class MimeEntity, which I can download like this :

using (var stream = System.IO.File.Create(path)
{
      mimeAttachment.ContentObject.DecodeTo(stream);
}

I was also wandering what is the reason the GetMessage() method and Fetch() method to return different types of message objects (MimeMessage and IMessageSummary)?

**Comment by jstedfast** [comment]
An `IMessageSummary` is really just metadata for a message, it isn't an actual message. It's meant to be used for things like presenting a list of messages to the user (e.g. a mail client's message list). It also has the `MessageSummaryItems.Body` & `BodyStructure` fields which allow the client to get a glimpse at the structure of the message, allowing the client to optionally decide to download only a subset of the full message (this is ideal for situations where the network is slow and/or storage space on the device is limited, such as cell phones).

This is different from calling `GetMessage()` because `GetMessage()` will download the complete message and so calling `attachment.ContentObject.DecodeTo(stream)` isn't actually downloading anything because it has already been downloaded as part of `GetMessage()`.

So what does this mean?

You have 2 options:

1. Download complete messages using `GetMessage()`, thus making things easy allowing you to decode attachments to streams at any time without need of requesting any additional data from the IMAP server, or...
2. Using `Fetch()` to request message metadata, allowing you to download only the parts of the message that you want/need, but requiring you to keep track of which folder the message is from, what the message's UID is, and which `BodyPartBasic` corresponds to the part you want.

Which one you choose will depend on what you want to do.

Hope that helps.

**Comment by karaliolio** [comment]
Great explanation! Thanks alot for the quick answer :)
