### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by issame** [jstedfast/MailKit#368]
What about proxy support?

**Comment by jstedfast** [comment]
I leave proxy support to you by providing `Connect()` methods that take a `Socket`.

See http://www.mimekit.org/docs/html/M_MailKit_Net_Imap_ImapClient_Connect.htm

**Comment by JobaDiniz** [comment]
@issame have you figured out?
@jstedfast how can I pass a `IWebProxy` instance with `Socket`?

**Comment by jstedfast** [comment]
A socket does not take an `IWebProxy`. What you need to do is use the `IWebProxy` object to figure out what IP address (or host name) and what port to connect to and then connect to it using the `Socket.Connect()` method.

For example:

```csharp
var uri = new Uri ("imaps://imap.gmail.com:993");

if (proxy.IsBypassed (uri)) {
    client.Connect ("imap.gmail.com", 993, SecureSocketOptions.SslOnConnect);
} else {
    uri = proxy.GetProxy (uri);
    var socket = new Socket (SocketType.Stream, ProtocolType.Tcp);
    socket.Connect (uri.DnsSafeHost, uri.Port);
    client.Connect (socket, uri.DnsSafeHost, uri.Port, SecureSocketOptions.Auto);
}
```

Keep in mind this code is untested and you will likely have to tweak it to your needs.

**Comment by yadavmukul1986** [comment]
@jstedfast I am using proxy for connecting to internet. I am using socket to pass it in client.Connect method - I am using POP3 with SSL.

` using (var socket = new Socket(ipAddress.AddressFamily,
                                      SocketType.Stream,
                                      ProtocolType.Tcp))

var ipAddress = IPAddress.Parse("Proxy Server IP"); // Proxy server IP
socket.Connect(ipAddress, "Proxy Server Port");
client.Connect(socket, "outlook.office365.com", 995, SecureSocketOptions.SslOnConnect);` 

The error i am receiving is - The handshake failed due to an unexpected packet format.

After this error i googled it and found a suggestion to send bytes to socket after connecting -

`var bufferToSend = Encoding.UTF8.GetBytes(string.Format("CONNECT outlook.office365.com:995 HTTP/1.1<CR><LF>");
SocketError status;
socket.Send(bufferToSend, 0, bufferToSend.Length, SocketFlags.None, out status);`

I received success in status. Then received bytes from Socket - 

`byte[] buffer = new byte[socket.Available];
var result = socket.Receive(buffer, socket.Available, SocketFlags.None);`

When ran this code, it got stuck in socket.Receive and after few minutes it says - "connected party did not properly respond".

Same Proxy is configured in IE and i can access the same mailbox from IE.

**Comment by yadavmukul1986** [comment]
@jstedfast I am using proxy for connecting to internet. I am using socket to pass it in client.Connect method - I am using POP3 with SSL.

```
using (var socket = new Socket(ipAddress.AddressFamily,
                                      SocketType.Stream,
                                      ProtocolType.Tcp))

var ipAddress = IPAddress.Parse("Proxy Server IP"); // Proxy server IP
socket.Connect(ipAddress, "Proxy Server Port");
client.Connect(socket, "outlook.office365.com", 995, SecureSocketOptions.SslOnConnect);
```

The error i am receiving is - The handshake failed due to an unexpected packet format.

After this error i googled it and found a suggestion to send bytes to socket after connecting -

```
var bufferToSend = Encoding.UTF8.GetBytes(string.Format("CONNECT outlook.office365.com:995 HTTP/1.1<CR><LF>");
SocketError status;
socket.Send(bufferToSend, 0, bufferToSend.Length, SocketFlags.None, out status);
```

I received success in status. Then received bytes from Socket - 

```
byte[] buffer = new byte[socket.Available];
var result = socket.Receive(buffer, socket.Available, SocketFlags.None);
```

When ran this code, it got stuck in socket.Receive and after few minutes it says - "connected party did not properly respond".

Same Proxy is configured in IE and i can access the same mailbox from IE.

**Comment by JobaDiniz** [comment]
I don't know if it will help anyone in the future, but my problem was not *proxy*.
I thought it was because the machine was behind a proxy, but turns out it was anti-virus blocking the socket communication.

**Comment by jamesjetspoon** [comment]
can you provide full code please, i cannot implement this solution.

**Comment by jstedfast** [comment]
MailKit 2.1.0 now has support for Socks4 and Socks5 proxies.
