### ISSUE TITLE
Mailkit samples

### ISSUE THREAD

**Issue by rboy1** [jstedfast/MailKit#400]
Hi, I'm sorry to raise a ticket for this but I can't seem to find a forum page or a discussion page for MailKit. This is an amazing library which is just outstanding, but for all it's complexities it would great to have some samples which are very simple for starters.

The most basic need for example is how to one get the HTMLBody and TextBody of a IMAP message without downloading the attachments. Now I've seen MULTIPLE examples from your explanations on StackOverFlow to the documentation and SampleIMAPClient code but they are ALL either complicated (the documentation gives like 5 different ways to so it) but none of them are complete or to the point.
The closest one I found was on the mail page and this is it:

    foreach (var summary in inbox.Fetch (0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId)) {
    var text = summary.Body as BodyPartText;

    if (text == null) {
        var multipart = summary.Body as BodyPartMultipart;

        if (multipart != null)
            text = multipart.BodyParts.OfType<BodyPartText> ().FirstOrDefault ();
    }

    if (text == null)
        continue;

    // this will download *just* the text part
    var part = inbox.GetBodyPart (summary.UniqueId.Value, text);
    }

Even this only gets the text, how about the html? So my request is it possible to create some sample codes which just do some basic things like:
1. Get only Body for IMAP messages (text and html alternative views) without attachments
2. Get only attachments without the body

I may be over simplifying it but for starters these complete working sample reuseable codes are an excellent way to dip your toes in the water without getting overwhemled by the awesome capabilities and complexities of MailKit

**Comment by jstedfast** [comment]
I've updated that section of the README.md to show how to use the `TextBody` and `HtmlBody` properties of an `IMessageSummary`

**Comment by jstedfast** [comment]
Your next homework assignment is to read this: http://www.mimekit.net/docs/html/WorkingWithMessages.htm#MessageStructure

While the following sections deal with `MimeMessage`'s, the **Message Structure** section still applies to the `IMessageSummary.Body`.

**Comment by rboy1** [comment]
Thank you very much!! And yes I did look at that too. It's a great page for introductions to how MIME messages are formed. Very helpful, but to be honest at the end it suffered from the same issue. How to translate that volume of information into simple code. Let me share an example of what I mean.
You understand the complexities of the message structure and components and how to traverse it. That was one complicated piece of code. Next up you read about HtmlBody and TextBody parts and it talks about it being part of childs and then it goes onto decoding. Now all this seems like parts of a HUGE schema to parse a MIME eMail. One would be hard pressed to map all that information into code, let alone to know or suspect that the answer could as simple as what you posted on the main page.

Do you see the gap? Translating the theory and background of that volume of information into code is nearly impossible without doing a Phd. I would never guess it's as simple as what you posted, I started thinking about how to traverse parts looking for HTML and Text parts, how to decode them etc etc etc.

Does that help?

**Comment by rboy1** [comment]
Maybe segregate the documentation into parts. A simple way would be most everyone things of messages as
1. Headers
2. Body
3. Attachments

Now organize the content to address the three above and then a Misc section for all else. And each one have it's own samples codes, now that would be easy to correlate and move forward from taking theory into code. Just my 2 cents, thanks still for such an awesome piece of work!

**Comment by rboy1** [comment]
ACtually that was going to be my next, I went through the docs and couldn't find how to get the headers (from email, replyto etc when using the fetch command)?

**Comment by rboy1** [comment]
Sorry is this is a basic question, why not just use summary.TextBody and summary.HtmlBody instead of getBodyParts in your sample code? Am also trying to figure out how to get the actual text or html from the MimeEntity? (I can see it under a base field called Text but can't access it)

**Comment by jstedfast** [comment]
**The Message Structure** illustrates that MIME is a nested structure of multiparts and leaf-node parts. In order to find the "attachments", you need to understand that *some* multiparts, such as `multipart/alternative` and (arguably) `multipart/related` do not contain "attachments", but rather they contain only parts needed for rendering the non-attachment component(s) of the message body.

The third most common multipart is `multipart/mixed` which is the generic multipart type. If you get a multipart and do not recognize the subtype, you treat it the same as you'd treat a `multipart/mixed`.

The next most common types are `multipart/signed` and `multipart/encrypted` which I'm sure you can figure out their content based on the names.

In general, "attachments" are direct descendants of `multipart/mixed` containers, and they are only "attachments" if they are not part of the "body".

The reason I am putting the terms "attachment" and "body" in quotes is because these are at least partially open to interpretation. This means that there are no hard and fast rules for how to treat MIME parts.

What do I mean by "partially open to interpretation"? Well, typically what MIME considers to be an attachment is any MIME part with a `Content-Disposition` header with a value of `attachment`. If you are like most people, though, this is not a good enough interpretation because you will, undoubtedly, receive MIME messages at some point (if not already) that will have what you (or your mail client) considers to be an attachment that does *not* have a `Content-Disposition` header with a value of `attachment`.

This is why people are *constantly* submitting issues to the issue tracker thinking they have found a bug in MimeKit and/or MailKit because `MimeMessage.Attachments` does not include the "attachment" they think should be in there because *their* interpretation of "attachment" is not limited to the `Content-Disposition` value.

The point I'm trying to make is that you'll need that PhD in MIME to truly get what you need :)

That said, the **Traversing a Message** section in the docs immediately after the **The Message Structure** section in the link I provided above contains an `HtmlPreviewVisitor` class which, IMHO, is the most comprehensive example you are ever likely to find *anywhere* which breaks down how to render a message into a mail client's "Preview Pane" (or "View Pane" or whatever you want to call the pane where Outlook, Thunderbird, etc all render the message). It *also* has the full added benefit of illustrating exactly how mail clients determine what *is* and what *is not* an "attachment" - i.e. anything that gets used by the renderer is the "body" while everything not rendered is an "attachment".

This code is based on `MimeEntity` rather than the `BodyPart` structure provided in the `IMessageSummary.Body` property, but the concept is the same (although `BodyPart` currently does not have a `MimeVisitor`-like equivalent API - largely because BodyPart classes do not have the comprehensive subclasses that `MimeEntity` has).



Before you spend a lot of time trying to wrap your head around `BodyPart` objects, might I suggest considering downloading the entire `MimeMessage` using `ImapFolder.GetMessage()` and just using something like the `HtmlPreviewVisitor` and/or simply `MimeMessage.Attachments` to get what you want?

If you want to download *all* attachments anyway, I would point out that in general, attachments make up a far larger percentage of the message size than the message bodies tend to use, so it probably makes more sense to download the entire message because most likely it'll be faster for several reasons:

1. In order to download individual attachments, you'll need to request the BODYSTRUCTURE of each of the messages that you will be dealing with (that's a fair bit of data).
2. You'll need to use more IMAP commands to get the data you want which means more round-trips over the internet which probably add up to more time spent than if you simply downloaded the full message.

**Comment by jstedfast** [comment]
FWIW, my plan has been to expand the documentation to a far greater level than I already have, but I am only 1 person (and not even a trained technical writer!) and the sheer amount of information needed to fully explain "all the things" about MIME, IMAP, POP3 and SMTP would make Lord of the Rings look like a short story :)

**Comment by rboy1** [comment]
Thank you for that detailed explanation and you're right it does need a PhD and I'm trying to see if there's a balance to be struct. While your code is super amazing and comprehensive it also needs the PhD to use it. Hence my original request (which you have done) to provide options for the most common scenarios for starters.
As for the attachment issue I guess with some creative thoughts perhaps it could be renamed or when you redo the docs possibly highlight it in the explanation. But honestly a simpler getting started doc for basic users would be brilliant.

I'm sending a donation your way, it isn't easy supporting open source and taking the time to write all this. Thank you!!

**Comment by jstedfast** [comment]
Currently working on expanding the unit tests to not be so embarrassingly low. Then my plan is to start writing more docs.

Thanks for the donation!
