### ISSUE TITLE
Why do you use use InboxCountChanged and not just use new MessagesArrived to tell if new message has arrived?

### ISSUE THREAD

**Issue by truane** [jstedfast/MailKit#437]
Why do you use use InboxCountChanged and not just use new MessagesArrived to tell if new message has arrived?

// Keep track of messages being expunged so that when the CountChanged event fires, we can tell if it's
 // because **new messages** have arrived vs messages being removed (or some combination of the two).

**Comment by jstedfast** [comment]
The `MessagesArrived` event is emitted whenever the IMAP server sends the client an `EXISTS` event where the number of messages in the folder has increased. Since the `e.Count` value is calculated as `NewMessageCount - OldMessageCount`, it might actually be misleading since you could have a situation such as:

1. Open a folder, current message count is 10
2. Move a message out of the folder
3. while the message is being moved, you get 2 new messages
4. `MessagesArrived` event is emitted with a `Count` of 1 (10 - 1 + 2 = 11... 11 - 10 = 1)
