### ISSUE TITLE
AddFlags doesn't works with SpecialFolder.All

### ISSUE THREAD

**Issue by berets76** [jstedfast/MailKit#442]
Hi, thanks for your great work, I've a "problem" setting as deleted some email not in INBOX.

The same following code , if run using INBOX works fine (even if email are deleted and not moved to trash, is it correct ?), with SpecialFolder.All it run without exceptions but email are not flagged as deleted.

```csharp
            ImapClient ic = new ImapClient();
            ic.Connect("imap.gmail.com", 993, true);
            ic.AuthenticationMechanisms.Remove("XOAUTH2");
            ic.Authenticate("user@gmail.com", "mypass");
            var folder = ic.GetFolder(SpecialFolder.All);
            folder.Open(FolderAccess.ReadWrite);
            int deleted = 0;
            IList<UniqueId> uids = folder.Search(SearchQuery.FromContains("@sender.com "));
            foreach (UniqueId uid in uids)
            {
                var msg = folder.GetMessage(uid);
                Console.WriteLine(msg.Date + " > " + msg.Subject);
                folder.AddFlags(uid, MessageFlags.Seen | MessageFlags.Deleted,true);
                deleted++;
            }
            Console.WriteLine("Deleted : " + deleted);
            ic.Disconnect(true);
            Console.ReadLine();
```

**Comment by jstedfast** [comment]
GMail is weird with the way it treats deleted messages by default. How it works depends on what settings you've used to configure your IMAP account in GMail's `POP3/IMAP Settings` panel.

On top of that, you are setting flags in the "All" folder which shows *all* messages, including those from the Trash folder.

I guarantee that MailKit is marking them as deleted. The problem is with your GMail settings.

Make sure that your settings look like this:

![GMail POP3 and IMAP Settings](http://content.screencast.com/users/jeff.xamarin/folders/Jing/media/7d50dada-6cb0-4ab1-b117-8600fb5e07d4/00000022.png "GMail POP3 and IMAP Settings")

**Comment by berets76** [comment]
I've your identical settings, but if I mark as deleted email into All folder gmail doesn't delete them, if I did the same using Inbox folder all works, but obviously if I serach Inbox I cannot find other folder's matches.

With All special folder, something somewhere is going wrong, I'll try to investigate a little
