### ISSUE TITLE
Is it possible to read the .eml file using the mailkit

### ISSUE THREAD

**Issue by skd123us** [jstedfast/MailKit#472]
I have some .eml files created using another smtp client that I was using to send emails in the background. I want to migrate my code to mailkit and am wondering if there is a deserialize function to load from the disk. I know that we can serialize emails using ToString on the Mime but unable to find a way to load from the file.

**Comment by jstedfast** [comment]
Yes. See the [MimeKit](https://github.com/jstedfast/MimeKit) README, specifically the section on [parsing messages](https://github.com/jstedfast/MimeKit#parsing-messages).

FWIW, *never* use ToString() to serialize the message. Use the WriteTo() methods instead. See the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#Serialize) on how to use the WriteTo() methods.

The reason you should not use ToString() is because messages may use multiple charsets (i.e. a different charset per text part and/or per header) and so it's impossible to represent this as a string.

Hope that helps.

**Comment by jstedfast** [comment]
The ToString() method is mostly for debugging purposes. I may have to start adding extra junk into the string produced by ToString() to force people to use WriteTo() because everyone keeps assuming ToString() is the right way to serialize messages :(

**Comment by Sicos1977** [comment]
Just add an obsolete attribute to your method that warns them not to use it this way. This is what I do in cases like this. Then they get a compiler warning (or error if you want)

See: https://msdn.microsoft.com/nl-nl/library/22kk2b44(v=vs.90).aspx

**Comment by skd123us** [comment]
Pretty straightforward. Should have looked more first!
