### ISSUE TITLE
Here are some samples I am looking forusing the imapClient for Mailkit

### ISSUE THREAD

**Issue by maddisn** [jstedfast/MailKit#478]
#1) Check to see if an mailbox folder contains unread messages 
2) If yes then parse each message subject, body, attachments, and inline attachments
3) Will fetching a message mark it as read?
4) How to mark a messages as unread

I am using mailkit to parse email that live in a microsoft outlook server.
I just need samples of the following, and I am mgrating from another imap library which did not work in the end.

**Comment by jstedfast** [comment]
1. Check the [ImapFolder.Unread](http://www.mimekit.net/docs/html/P_MailKit_MailFolder_Unread.htm) property.

2. Do you want to just download the entire message and get the Subject/etc that way? or download individual MIME parts?

Download entire messages:

```csharp
var message = folder.GetMessage (uid);

// here's how to get the Subject
string subject = message.Subject;

// here's how to get the body (in the simple way)
string text = message.TextBody;
string html = message.HtmlBody;

// here's how to get *just* attachments:
foreach (MimeEntity attachment in message.Attachments) {
    // ...
}

// here's how to get both attachments and inline attachments:
foreach (MimeEntity attachment in message.BodyParts) {
    // ...
}
```

For more information on how to get the message body in the more complex way, see the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#MessageBody).

For more information on how to save the attachments, see the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SaveAttachments).

Here's how you can download summary information instead of full messages (and then use said summary info to get the stuff you want):

```csharp
var items = client.Inbox.Fetch (0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure | MessageSummaryItems.Envelope);

foreach (var item in items) {
    // here's how to get the subject
    string subject = item.Envelope.Subject;

    // here's how to get the text body
    BodyPart part = item.TextBody;

    if (part != null) {
        // here's how to download said body part (we can safely cast to TextPart because
        // we know that this part is a text/* part)
        TextPart entity = (TextPart) folder.GetBodyPart (item.UniqueId, bodyPart);

        // here's how to get the text
        string text = entity.Text;
    }

    // here's how to get the html body
    part = item.HtmlBody;

    if (part != null) {
        // here's how to download said body part (we can safely cast to TextPart because
        // we know that this part is a text/* part)
        TextPart entity = (TextPart) folder.GetBodyPart (item.UniqueId, bodyPart);

        // here's how to get the text
        string text = entity.Text;
    }

    // here's how to get *just* the attachments
    foreach (var attachment in item.Attachments) {
        MimeEntity entity = folder.GetBodyPart (item.UniqueId, attachment);

        // to save the content, it works exactly the same as in the GetMessage example
    }

    // here's how to get both attachments and inline attachments
    foreach (var attachment in item.BodyParts) {
        MimeEntity entity = folder.GetBodyPart (item.UniqueId, attachment);

        // to save the content, it works exactly the same as in the GetMessage example
    }
}
```

Take a look at the documentation for [IMessageSummary](http://www.mimekit.net/docs/html/T_MailKit_IMessageSummary.htm) in order to see what else is stored on each `item` in the above code. It's also worth taking a look at the [MessageSummaryItems](http://www.mimekit.net/docs/html/T_MailKit_MessageSummaryItems.htm) so that you can figure out which items flags you need to specify to get what `IMessageSummary` properties to become populated (it's pretty much a 1:1).

3. No. Downloading a message or any of its parts will not automatically mark it as read. You have to do that yourself.

4. Take a look at [ImapFolder.AddFlags](http://www.mimekit.net/docs/html/Overload_MailKit_MailFolder_AddFlags.htm) and [ImapFolder.SetFlags](http://www.mimekit.net/docs/html/Overload_MailKit_MailFolder_SetFlags.htm)

Or see my answer to this question on [StackOverflow](http://stackoverflow.com/questions/31984490/how-can-i-mark-a-message-as-read-in-mailkit/31994027#31994027)

**Comment by jstedfast** [comment]
FWIW, I just updated the FAQ regarding the "unread count" question: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ImapUnreadCount

**Comment by jstedfast** [comment]
The `HtmlPreviewVisitor` is also valuable to take a look at if you want to be able to render HTML messages that reference attached images.

**Comment by maddisn** [comment]
Hello Jeffrey,


I am still stuck on trying to download the messages from the email.

I just need all the attachments downloaded to a local folder.

I am still a student in school, and I am having trouble with the current api I am using to do stuff with email.

I am looking to migrate over to Mime/mailKit



   public void getAtttachments()
        {
            using (var client = new ImapClient())
            {
                //authenticate
                client.Connect(Constant.OutlookImapHost, Constant.ImapPort, SecureSocketOptions.SslOnConnect);
                client.Authenticate(Constant.GoogleUserName, Constant.GenericPassword);
                Console.WriteLine(client.IsAuthenticated);

                if (client.IsConnected == true)
                {
                    FolderAccess inboxAccess = client.Inbox.Open(FolderAccess.ReadWrite);
                    IMailFolder destination = client.GetFolder(Constant.InboxFolder);
                    IList<UniqueId> uids = client.Inbox.Search(SearchQuery.All);

                    if (destination != null)
                    {
                        foreach (UniqueId msgId in uids)
                        {
                            MimeMessage message = destination.GetMessage(msgId);

                            foreach (MimeEntity attachment in message.Attachments)
                            {
                                //attachment.WriteTo(new FileStream(string.Concat("C:\\Users\\maddirsh\\Desktop\\", attachment.ContentDisposition.FileName), FileMode.Create, FileAccess.Write));
                            }
                        }
                    }
                }
                else
                {
                    throw new NullReferenceException();
                }
            }
        }



________________________________

**Comment by jstedfast** [comment]
```csharp
public void getAtttachments()
{
    using (var client = new ImapClient ()) {
        client.Connect(Constant.OutlookImapHost, Constant.ImapPort, SecureSocketOptions.SslOnConnect);
        client.Authenticate(Constant.GoogleUserName, Constant.GenericPassword);

        client.Inbox.Open(FolderAccess.ReadWrite);
        IList<UniqueId> uids = client.Inbox.Search(SearchQuery.All);
        foreach (UniqueId uid in uids) {
            MimeMessage message = client.Inbox.GetMessage(uid);

            foreach (MimeEntity attachment in message.Attachments) {
                // copied & pasted from the FAQ:
                string fileName = attachment.ContentDisposition?.FileName ?? attachment.ContentType.Name;

                if (string.IsNullOrEmpty (fileName)) {
                    // This attachment doesn't have a filename, I guess we'll skip it...
                }

                string path = Path.Combine ("C:\\Users\\maddirsh\\Desktop", fileName);
                using (var stream = File.Create (path)) {
                    if (attachment is MessagePart) {
                        var rfc822 = (MessagePart) attachment;
            
                        rfc822.Message.WriteTo (stream);
                    } else {
                        var part = (MimePart) attachment;
            
                        part.ContentObject.DecodeTo (stream);
                    }
                }
            }
        }
    }
}
```

**Comment by jstedfast** [comment]
All you had to do was literally copy & paste from the FAQ.

**Comment by maddisn** [comment]
Jeff,

That works perfect, sorry for the ticket, I am still trying to catch on since I am a student.
![saveimage](https://cloud.githubusercontent.com/assets/25490236/24972914/0210e81c-1f8b-11e7-8798-e7f7e973cf74.PNG)

1) You mentioned earlier, that downloading the entire message is better than stripping parts. I assume the above example is downloading the entire message, because I am avoiding the way of doing it as below. 
`IList<IMessageSummary> items = client.Inbox.Fetch(0, -1, MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure | MessageSummaryItems.Envelope);`
I just need some clarity of what you mean by download the entire message, it sounds like you meant to download the .eml file of each email locally?
That would work faster, than making trips acorss the network.
(I have seen an example of that, and I am aware of how that can be done).

2) I also see a specific way of authenticating with gmail in the FAQ section.
I am using Gmail with Imap, and I am using the same code. Is there an advantage to that?, becuase I am able to get into gmail without removing OAUTH 2 and the ServerCertificateValidationCallback.
https://github.com/jstedfast/MailKit/blob/master/FAQ.md#q-how-can-i-access-gmail-using-mailkit

3) I am using the code above to get both the attachments, and inline attachments. The email body text, and the html version are being pulled down. Is there another method that can only download the attachments, and inline attachments.
I notice that the files are unnnamed, and have no extension. I can write something to avoid writing to the desk if the file has not type, and is unnamed.

**Comment by jstedfast** [comment]
@maddisn 

1. `GetMessage()` is what I mean by "download the entire message". If you want to save all of the attachments of a message that exists on an IMAP server, you have 2 ways of doing this: 1. use `GetMessage()` to download the entire message and then iterate over each attachment... -or- 2. fetch the BODYSTRUCTURE of the message and then use `GetBodyPart()` to download individual MIME parts (i.e. the individual attachments).

2. You don't need to remove the XOAUTH2 item from the `AuthenticationMechanisms` hash set. I am mostly just illustrating how you could tell MailKit which authentication mechanisms *not* to use. In the example, since we don't have an auth_token, obviously XOAUTH2 won't work, so I show how to bypass it.

3. What do you mean by "are being pulled down"? `GetMessage()` downloads the *entire* message, yes, but like I said (and you reiterated in question 1), the text and html bodies are likely to be small by comparison to the attachments and so it's simpler to just download the entire message. There's also the fact that you seem to be struggling with the simplest approach, so I didn't want to confuse you more by explaining how to download individual body parts (e.g. `GetBodyPart()`).

If by "are being pulled down" you mean that you are saving out the text and html bodies as files on your hard drive, well, you can avoid doing that by simply avoiding saving out body parts that don't have a `FileName` set. Or you could use some other heuristic.

You should read the FAQ about message structures - that will no doubt help you understand MIME better.

**Comment by maddisn** [comment]
That makes perfect sense, thanks for clearing that up.
so do all inline messages, get defaulted to a filename of "pastedImage", I have tried to copy and paste some images from the internet.

Thanks again Jeff.

**Comment by jstedfast** [comment]
> so do all inline messages, get defaulted to a filename of "pastedImage"

Maybe with whatever mail client you are using, but not with most clients.

**Comment by maddisn** [comment]
I tried it with both gmail, and outlook. All the inline images are saved with the filename of "pastedImage".
I can write something where a number is added to the filename like ++unamed, from your earlier examples.

I am trying to download all the images, whether it's inline or attached into one location on my local drive. This location will be used by the program to convert all these files to base64 strings, in order to upload them to our ticketing system.
