### ISSUE TITLE
resolve mail garbled

### ISSUE THREAD

**Issue by Yuan1111** [jstedfast/MailKit#490]
The message is as follows
<pre>
{Received: from localhost6.localdomain6 (219.133.73.161) by ad.corp.wosign.com
 (218.246.1.136) with Microsoft SMTP Server (TLS) id 14.2.247.3; Thu, 6 Apr
 2017 05:30:42 +0800
Content-Type: multipart/alternative;
	boundary="===============0928121954660309197=="
From: <xxx@xxx.com>
To: <xxxx@wosign.com>
Subject: =?utf-8?b?6YKu566x6LSm5oi35a+G56CB5Yiw5pyf5o+Q6YaS?=
Message-ID: <a1584e03-a39a-44ce-aa68-f901023a797f@ad.corp.wosign.com>
Return-Path: ops@wosign.com
Date: Thu, 6 Apr 2017 05:30:42 +0800
X-MS-Exchange-Organization-AuthSource: ad.corp.wosign.com
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 06
X-Originating-IP: [219.133.73.161]
X-MS-Exchange-Organization-AVStamp-Mailbox: MSFTFF;1;0;0 0 0
MIME-Version: 1.0

--===============0928121954660309197==
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: 8bit

<p>æ¸©é¦¨æç¤º:<br />&nbsp;&nbsp;æ¨çé®ç®±è´¦æ·<span style="color:#337FE5;"> xxx@xxx.com </span>å¯ç å³å°è¿æï¼è¯·å°½å¿«éç½®é®ç®±å¯ç ã</p>
--===============0928121954660309197==--

</pre>

when I get text is garbled, then i change the code MimeKit.TextPart
<pre>
public string Text{
  get{
   .....
   .....
         if (charset.ToLower() == "us-ascii") {encoding = CharsetUtils.GetEncoding("utf-8");}
         else{ encoding = CharsetUtils.GetEncoding(charset);}
        }
}
</pre>
 I can get the value (温馨提示:
  您的邮箱账户 xxx@xxx.com 密码即将过期，请尽快重置邮箱密码。
) ,But I do not know if this change will affect other mail resolution, hopes your help, thanks!

**Comment by jstedfast** [comment]
`TextPart` provides the `GetText` method that you can use instead to override which encoding is used.

The problem is that assuming UTF-8 when the charset is us-ascii is not necessarily going to work in all cases, so you'll probably need to provide the user with a menu so that they can override which charset to try (such as "iso-8859-1") if it still looks like garbage. Historically, that's what a lot of mail clients have done and that's why I provided the `GetText()` methods. The same problem will exist for `TextParts` with other charsets as well, no doubt some will say "utf-8" when they are actually something else and so on. In other words, software lies and you can't always trust what charset it tags text with.

If you asked me 10 years ago, I would have said iso-8859-1 is far more common than UTF-8, but these days I'm not sure which is more common... UTF-8 has continued to become adopted by more and more software.

**Comment by Yuan1111** [comment]
thanks for  your help！
