### ISSUE TITLE
Syntax error in BODYSTRUCTURE. Unexpected token: NIL

### ISSUE THREAD

**Issue by neobgd** [jstedfast/MailKit#503]
Hello,
I just start exploring MailKit and bump on some kind of error.
When I try to fetch Message summary I got this error:
Syntax error in BODYSTRUCTURE. Unexpected token: NIL

The code which I use is:
` var inbox = client.Inbox;`
  `inbox.Open(FolderAccess.ReadOnly);`
  `int index = Math.Max(inbox.Count - a.received_last, 0);`
 `foreach (var summary in inbox.Fetch(index, -1,  MessageSummaryItems.UniqueId | MessageSummaryItems.BodyStructure |MessageSummaryItems.Flags)){};`

When I remove `MessageSummaryItems.BodyStructure` everything is fine.

I use most recent version 1.16

**Comment by jstedfast** [comment]
please follow the directions when you click "New Issue" and provide a Protocol Log.

No protocol log = no fix.

**Comment by neobgd** [comment]
Sorry about that, my first post here.
[imap.zip](https://github.com/jstedfast/MailKit/files/974982/imap.zip)

**Comment by jstedfast** [comment]
Thanks. Taking a look now...

**Comment by jstedfast** [comment]
The problem is the following response:

```
S: * 12582 FETCH (UID 14214 FLAGS () RFC822.SIZE 6435 ENVELOPE ("Wed, 25 May 2016 16:44:58 +0530" "URGENT - DELIVERY" (("Theo britton" NIL "orjobins4043" "gmail.com")) (("Theo britton" NIL "orjobins4043" "gmail.com")) (("Theo britton" NIL "orjobins4043" "gmail.com")) ((NIL NIL "support" "deshodes.net")) NIL NIL NIL "<CAD-334528=3285b69C054442A281fbE6F93_7e3a6622abc179@mail.gmail.com>") BODYSTRUCTURE ((("text" "plain" ("charset" "UTF-8") NIL NIL "7bit" 148 12 NIL NIL NIL NIL)("text" "html" ("charset" "UTF-8") NIL NIL "quoted-printable" 337 6 NIL NIL NIL NIL) "alternative" ("boundary" "6c7f221bed92d80548353834d8e2") NIL NIL NIL)(("text" "plain" ("charset" "us-ascii") NIL NIL "7bit" 0 0) "x-zip" NIL ("attachment" ("filename" "YSOZ 265230.ZIP")) NIL NIL) "mixed" ("boundary" "c52bbfc0dd5365efa39b9f80eac3") NIL NIL NIL))
```

Specifically, the problem is this: `... "7bit" 0 0) "x-zip" NIL (...`

The server is saying that you've got a multipart/x-zip (no such thing) followed by a `NIL` `body-fld-param` (which is technically valid to have, but makes no sense since it also has a `text/plain` child which means that it *must* have a `boundary` param... but the server says it has no params... wtf?):

```
body-type-mpart = 1*body SP media-subtype
                  [SP body-ext-mpart]

body-ext-mpart  = body-fld-param [SP body-fld-dsp [SP body-fld-lang
                  [SP body-fld-loc *(SP body-extension)]]]
                    ; MUST NOT be returned on non-extensible
                    ; "BODY" fetch
```

**Comment by jstedfast** [comment]
I've fixed MailKit's `body-part-mpart` parser to handle `NIL` as a `body-fld-param` token which it should have technically handled anyway since it is valid syntax even though it doesn't make sense in your particular situation because it has subparts which REQUIRES a `boundary` param be defined.

Either the message is severely broken or your IMAP server is broken or both. But at least now your client isn't :)

**Comment by neobgd** [comment]
Hello,
I can confirm that fix working.
Thanks for quick response.

**Comment by neobgd** [comment]
Hello,
after two year I got the same error. Here is IMAP log.

**Comment by neobgd** [comment]
After two year I got same error.
IMAP log in link, I could not attach here.
https://we.tl/t-2o3pJXHQ1p

**Comment by neobgd** [comment]
I forgot to mention, now using latest version 2.3

**Comment by jstedfast** [comment]
Please file a new issue with the log. This is a different (related, but not identical) issue.
