### ISSUE TITLE
The remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by barkon007** [jstedfast/MailKit#511]
I am trying to create an application for reading mail. I am used mailkit and mimekit.
Well the application is working in my local system , but when deployed in the remote UAT server and executed I get this error msg - 
The remote certificate is invalid according to the validation procedure.
Don't know how to tackle this.

**Comment by jstedfast** [comment]
You need to either add the server's certificate to the system's certificate store or else set your own custom validation callback.

See the [FAQ](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate) for more information.

**Comment by DanJ210** [comment]
@jstedfast Is there a way to turn off the certificate operation all together? I'm on a server that's using `MailKit.Security.SecureSocketOptions.None` meaning no credentials. But I'm unable to send email because it's stating that the certificate is invalid. Is there a way to just turn of the process for certs? Like to continue without having a valid cert?

**Comment by jstedfast** [comment]
SecureSocketOptions.None should completely disable SSL/TLS. I don't understand how you could be getting that error.

Are you sure you are using SecureSocketOptions.None? Which client? Do you have protocol logs? Is it trying to STARTTLS or something?
