### ISSUE TITLE
How can I get the raw body of a MimeMessage

### ISSUE THREAD

**Issue by RobertPhoenix** [jstedfast/MailKit#543]
To help me debug your issue, please explain:
**- What were you trying to do?**

I recently moved to MailKit from a previous set of Pop3 and Smtp utilities.  

For historical reasons our database stores the raw header and the raw body.  I was trying to get the raw body from an incoming MimeMessage and the .Body.ToString() does not give me what I expected.

**- What happened?**

.Body.ToString() returns a string which includes one line of the header and then a blank line as in

```
Content-Type: multipart/mixed; 
boundary="--=_Part_26515894_712437450.1500330981009"

----=_Part_26515894_712437450.1500330981009
Content-Type: multipart/alternative; 
boundary="--=_Part_26515895_1820079270.1500330981009"

etc, etc, etc

```
**- What did you expect to happen?**

My understanding is that the header is separated from the body by a blank line (From Microsoft - If a message body is included, it is separated from the header fields by an empty line (\r\n\r\n) )

Also I believe it says the same thing in RFC822 Para 3.2. HEADER FIELD DEFINITIONS 

So I expected to get the body without the header line

```
----=_Part_26515894_712437450.1500330981009
Content-Type: multipart/alternative; 
boundary="--=_Part_26515895_1820079270.1500330981009"

etc, etc, etc

```
**- Step-by-step reproduction instructions and/or a simple test case.**

I'd be happy to send a test case, but I think the issue is clear without it.

**If you got an exception, please include the exception Message *and* StackTrace.**

No exception

**Please also INCLUDE A PROTOCOL LOG (scrubbed of any authentication data), especially
if you got an exception such as `Syntax error in XYZ. Unexpected token: ...`.
If you do not include the protocol log, you will make me VERY UNHAPPY.**

**Without a protocol log, I CANNOT fix the issue. I will simply close the bug report.**

I'd hate to make you very unhappy, but since the message is received without a problem I hope you won't just close this report ( Please !! )

**Comment by jstedfast** [comment]
In this particular case, you don't need a protocol log - so I'm not unhappy :)

You are also the first person to follow the instructions! Hurray!

Okay, so... now to answer your question.

This is somewhat awkward since MimeKit was not designed to split the headers and "body".

The reason MimeMessage.Body.ToString() didn't give you what you expected was because the Body property is actually a MimeEntity (MIME entities have headers). So what you got was the MIME Content-* headers and then the content of said MIME entity.

Writing only the *content* of the message is easy:

```csharp
message.Body.WriteTo (stream, contentOnly: true);
```

Writing only the headers is a bit more complicated currently because you can write the *message* headers simply enough using:

```csharp
message.Headers.WriteTo (stream);
```

*but* that won't include the top-level MIME entity headers.

You could fudge it like so, tho:

```csharp
message.Headers.WriteTo (stream);
message.Body.Headers.WriteTo (stream);
```

However, that won't preserve the *exact* order of the original combined headers because all of the Content-* headers will be moved to the end.

You could clone the logic inside of `MimeMessage.WriteTo()`, but that's more work than I want consumers of my library to have to do... so... I'll add a new `MimeMessage.WriteTo (Stream stream, bool headersOnly, ...);` method. How does that sound?

**Comment by jstedfast** [comment]
I'll try to make a new release of MimeKit in the next few days - I'm working on adding some PGP functionality for my Microsoft HackWeek project (which is a PGP plugin for Outlook).

**Comment by RobertPhoenix** [comment]
Perfect and extremely prompt response !!

Thank you very much.

Robert.
