### ISSUE TITLE
How can you search for a Gmail MessageID? 

### ISSUE THREAD

**Issue by Tfurrer** [jstedfast/MailKit#553]
Awesome package. Really love this library. 

Typically the messageID and inReplyTo (part of the mime message which looks similar to the following
TAGTkOQjo2kXyEtupz473eGsvn5fCwxBq6+jaQfPKbTXxZGjoHg@mail.gmail.com) is listed, but is there an example of how to search or get these messages using this ID? Perhaps I am going about this incorrectly? Is there a way to convert this into the id used in "inbox.GetMessage(uid)"

Thanks for the help!

**Comment by riyadparvez** [comment]
Do you have the solution?

**Comment by jstedfast** [comment]
```csharp
inbox.Search (SearchQuery.HeaderContains ("Message-ID", msgid));
```

**Comment by riyadparvez** [comment]
Thanks. I already got that. I was looking for how to search all emails, not just the emails in the inbox.

**Comment by jstedfast** [comment]
You'll have to iterate over all of your folders and Search() on all of them.

There's no way to query all folders at the same time (there's actually a multi-search extension, but it's not supported by any server that I could find so I didn't bother implementing it).

**Comment by riyadparvez** [comment]
Thanks. But this process seems very slow, since there's lot of back and forth communication. Is there any way to batch all these API requests into one HTTP request? Similar to Gmail batch request: https://developers.google.com/gmail/api/guides/batch

**Comment by jstedfast** [comment]
Unfortunately, no. There's 2 factors preventing this:

1. It's *really* hard to support batching of arbitrary IMAP commands in an API. MailKit does support batching of a number of things (appending a bunch of messages, updating flags on messages, getting summary information for a bunch of messages, etc), but the API's for these are based around common operations.
2. The IMAP protocol itself has limitations in what can be batched and this is one of those limitations. In order to `SEARCH` an IMAP folder, you must first open the folder (`SELECT` or `EXAMINE` commands, depending on `FolderAccess.ReadWrite` or `FolderAccess.ReadOnly`). The IMAP protocol does not allow batching `SEARCH` commands with `SELECT` or `EXAMINE`. Then, on top of that, you can't `SELECT` or `EXAMINE` the next folder until the `SEARCH` on the current folder completes.

**Comment by riyadparvez** [comment]
Okay, makes sense. Is it possible to batch download message requests into one call?

**Comment by jstedfast** [comment]
I don't think it would be generally useful for the official MailKit project, but you could fork it and add it to your fork.

**Comment by riyadparvez** [comment]
I believe it would be useful, because most of the time users have to download more than one email. That being said, can you give me some pointers on how to implement it? I will have a look into it.

**Comment by jstedfast** [comment]
You could just copy the code that downloads 1 message and pack it into a loop :)

Once you look at the code for GetMessage, I'm sure you'll see that it's pretty trivial.

**Comment by jstedfast** [comment]
Just made some minor changes to `FetchStreamContext` to make what you want to do even easier (since you can just reuse all of the core logic now).

**Comment by jstedfast** [comment]
FWIW, as I'm looking at the GetMessage() implementations, I'm not entirely sure what you'll want to return...

The "obvious" thought is to return an `IList<MimeMessage>`, but then the caller has no absolute way of knowing which message maps to which UniqueId (or index if you fetched the messages based on indexes).

While it might *seem* like you could simply construct the list of messages such that you keep them in the same order as the order of the uids/indexes, it's not quite so simple because if any of the indexes or uids doesn't exist, what do you do?

1. throw an exception - this is bad because you just wasted a ton of time downloading messages which could be quite large and the caller got nothing for it
2. simply add nulls to the list for any message that the server did not send back to the client - this sucks because people won't expect nulls in their list
