### ISSUE TITLE
How to use "SyncRoot"?

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#578]
How can I use "SyncRoot" for synchronization of my client and IMAP server?
any helping material you can share.

**Comment by jstedfast** [comment]
The same way you use SyncRoot for standard collections in .NET.

```csharp
lock (folder.SyncRoot) {
    folder.DoSomething ();
}
```

```csharp
lock (client.SyncRoot) {
    c lient.DoSOmething ();
}
```

**Comment by docrizwan** [comment]
I had read about the `lock` you mentioned in your writings, but what "SyncRoot" actually does?
I guess its used to perform a single operation at a time and blocks all other threads until current operation is completed.
Not getting how this keeps all the things in "sync".

**Comment by jstedfast** [comment]
It’s just a dummy object that is shared between all folders and their client that can be used to synchronize threads if your app is accessing IMAP via multiple threads.

**Comment by docrizwan** [comment]
does this locks the whole client object, when one thread locks it?

**Comment by jstedfast** [comment]
If you create your own class that implements the IList interface, for example, you will notice that you need to implement a SyncRoot property.

**Comment by docrizwan** [comment]
thank you!

**Comment by jstedfast** [comment]
> does this locks the whole client object, when one thread locks it?

Yes. When you lock the SyncRoot on any folder or the client, it prevents any other thread from locking any of the SyncRoots for the same IMAP connection.

**Comment by atiyka** [comment]
Hi @jstedfast , I have a question on this thread. I'm using an ImapClient between threads and couple of times (maybe when the idle operation fires multiple times) I got the following error: 

> The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.

When I perform an operation on a folder, I just lock the SyncRoot property of that folder, not the client's SyncRoot property. Is it okay/enough? Or I should lock the client when I'm doing any operation?

**Comment by jstedfast** [comment]
@atiyka 

The ImapClient.SyncRoot is the same object as the ImapFolder.SyncRoot (assuming the ImapFolder came from the ImapClient), so yes, that is enough.

That said, the most common reason most people see that error is not because of locking anymore... the most common reason seems to be because you are trying to invoke an IMAP command from within an IMAP event handler. You cannot do that.

Here's why:

In MailKit, the ImapClient processes the server response and emits those events WHILE IT IS STILL PROCESSING THE COMMAND.

In other IMAP client libraries, the ImapClient will read the **entire response** into one big **massive string** before it starts parsing it, but MailKit doesn't do that. It parses the response as it reads it from the socket.

What you need to do in your event handlers is to queue a new command somehow in your program. How you do that depends on how you design your program. Are you using Tasks? If so, you could do `.ContinueWith (...)` on the current running Task.

**Comment by atiyka** [comment]
Thank you very much the response! Yes, I'm using Tasks.
