### ISSUE TITLE
Get attachment with no file name

### ISSUE THREAD

**Issue by vnwind** [jstedfast/MailKit#586]
Hi Jeff
I am trying to save the outlook auto forward attachment from gmail account. The email content is 

```
--_000_CY1PR16MB0523DF565EE9722F16335587C85D0CY1PR16MB0523namp_--
--_004_CY1PR16MB0523DF565EE9722F16335587C85D0CY1PR16MB0523namp_
Content-Type: message/rfc822
Content-Disposition: attachment; creation-date="Fri, 03 Nov 2017 20:07:52 GMT"; modification-date="Fri, 03 Nov 2017 20:07:52 GMT"

Received: from cy1pr16mb0523:444 by CY1PR16MB0523.namprd16.prod.outlook.com with HTTP; Fri, 3 Nov 2017 19:55:26 +0000
```

I use the code 
```csharp
var attachments = new List<MimePart> ();
var iter = new MimeIterator (message);

// collect our list of attachments and their parent multiparts
while (iter.MoveNext ()) {
    var part = iter.Current as MimePart;
    if ( part != null && part.IsAttachment) {
        attachments.Add (part);
    }
}
```
I don't get the attachment or any exceptions. I was wondering how do you handle this situation ? Thanks for your help

**Comment by jstedfast** [comment]
`message/rfc822` attachments don't subclass `MimePart`, they subclass `MessagePart` (the reason for this is to allow the `MimeParser` to recursively parse `message/rfc822` parts rather than parsing them on-demand as they are needed... since we have to pass over the data while slurping up the outer message, why not parse the inner message(s) as well?).

You can change your code to look like this:

```csharp
var attachments = new List<MimeEntity> ();
var iter = new MimeIterator (message);

// collect our list of attachments and their parent multiparts
while (iter.MoveNext ()) {
    if (iter.Current.IsAttachment)
        attachments.Add (iter.Current);
}
```

To see how to save `MessagePart`s, see https://github.com/jstedfast/MimeKit/blob/master/FAQ.md#SaveAttachments

**Comment by vnwind** [comment]
thank you so much
