### ISSUE TITLE
Microsoft.IO.RecyclableMemoryStream and ImapFolder

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#596]
Hey Jeffrey,

I was happy to find out ImapFolder have ability to create custom streams thru CreateStream method. This allows me to use this beautiful piece of code from Microsoft https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream

However there are few checks in MailKit which prevent disposition of MemoryStreams

which prevent RecyclableMemoryStream from releasing internal buffers. Is it possible to add something like 
protected virtual bool ShouldDisposeStream(Stream stream)
{
if (!(stream is MemoryStream || stream is MemoryBlockStream))
						dispose = true;
} 

so we can choose if we won't to dispose the stream or not

**Comment by jstedfast** [comment]
You'll have to do better to explain to me where this is needed.

**Comment by ekalchev** [comment]
I am getting alot of GC activity because of copies of MemoryStreams. being garbage collected, as well as LOH fragmentation, because of that. This happens when I download entire mailbox with Mailkit. RecyclableMemoryStream should prevent this by using memory pool for these.

**Comment by jstedfast** [comment]
Don't RecycleableMemoryStreams ever need to be disposed?

If ImapFolder never disposes them, even when there are errors reading from the imap connection into said memory stream, how will things ever get cleaned up?

**Comment by jstedfast** [comment]
Oh, you mean the logic that decides whether or not to dispose memory streams when parsing MimeMessage and MimeEntity.

That's not so much ShouldDisposeStream as ShouldPersistStream.

The reason we don't dispose memory streams when parsing is because the parsed messages/entities keep a reference to them rather than cloning the content of the mime parts.

**Comment by jstedfast** [comment]
Keep in mind that if ImapFolder does not dispose the stream, then you have to manually dispose every stream referenced by the MimeMessage that gets returned to you.

Since MemoryStream and MemoryBlockStream do not have any unmanaged references, this is not necessary - hence why the code checks for those.

**Comment by jstedfast** [comment]
Hello?

**Comment by ekalchev** [comment]
RecycleableMemoryStreams should be disposed to return its buffers to the internal memory pool. 

> The reason we don't dispose memory streams when parsing is because the parsed messages/entities keep a reference to them rather than cloning the content of the mime parts.

Ye, saw that code... It is nice optimization but makes it harder to work with RecyclableMemoryStream. It will be good somehow to say i am done with MimeMessage so streams can be disposed. 

My initial problem was solved by not parsing Mime messages during the mailbox synchronization - We are now downloading the Mime parts and saving them as stream to the database and the parsing is done when we need to show them. This way the performance is much better and GC activity is acceptable. We are using IMailFolder.GetStream which works well with RecyclableMemoryStream

**Comment by jstedfast** [comment]
Okay, using GetStream() is definitely a better solution for this. I'll close this since your solution is better.
