### ISSUE TITLE
SMTP credential charset/encoding, what is "correct"?

### ISSUE THREAD

**Issue by alex-becker-startp** [jstedfast/MailKit#620]
Hi Jeff,

today I got a problem authenticating against an MS-Exchange SMTP service.
The username contains a german umlaut which is by default UTF-8/BASE64 encoded by MailKit.
It seems that Exchange only accepts ISO-8859-1/BASE64 encoded usernames.

I found an encoding argument in the .Authenticate() method, so I can set this up.
But what is the "correct" approach to do this?
I've never seen a mailclient where I have to configure the encoding to be used for login.
So I think the client must have a way to determine the correct one on its own.

Because MailKit uses UTF-8 as default, I think this is the recommended one, right?
I had some problems fetching this information from the RFCs for my own...
Maybe you can help me out?

Best regards,
Alexander

**Comment by jstedfast** [comment]
Typically, mail clients use either UTF8 by default or the locale charset on the user's machine. The problem is the user's locale charset is irrelevant to what the *server's* locale charset is, which is what the server expects the usernames and passwords to be encoded in. The *assumption* is that the user's locale charset in his/her machine is the same as the server's because it is *assumed* that both the user and server are in the same geographic vicinity and likely to be using the same OS and are configured to use the same charset encoding, but that's a lot of assumptions :)

There's no way for the client to know which charset to use. 15-20 years ago, UTF-8 wasn't very wide-spread, but these days, if you aren't using unicode, you're a dinosaur.
