### ISSUE TITLE
How  to detect that mail have attachment or not 

### ISSUE THREAD

**Issue by sour7230** [jstedfast/MailKit#622]
i wont to detect that mail have attachment or not.

**Comment by jstedfast** [comment]
Well, a simple way would be:

```csharp
var summaries = folder.Fetch (uids, MessageSummaryItems.BodyStructure | OtherItems);
foreach (var summary in summaries) {
    bool hasAttachments = summary.Attachments.Any();
}
```

You can read more about that property in the documentation here: http://www.mimekit.net/docs/html/P_MailKit_MessageSummary_Attachments.htm

I would prefer you read the documentation instead of asking me all these questions (there's even a search bar at the top to help you search on keywords). My free time is valuable and I'm not getting paid to answer your questions.

A donation would be appreciated!

Thanks.

**Comment by sour7230** [comment]
My motive was not waste you time.i appreciate you reply.but you did not
mention document link anywhere,therefore I was getting in this situations.
           As before that I had some query than I would put down in
github.if you are not interest reply,so please would not reply on same mail.
                            I knew that I would not pay for that.if you are
not interest to answer.so you will not reply on that.
              Sry for you valuable time.

**Comment by jstedfast** [comment]
The documentation is linked to from the README.
