### ISSUE TITLE
ASP.NET Core 2.0 Trying to send email with O365 account

### ISSUE THREAD

**Issue by Mike-tech** [jstedfast/MailKit#624]
Hi 
Hope some one can point me to what i could be doing wrong. Trying to send email with MailKit using below sample code but seems to fail. I'm using an Office 365 account. 

I've tried different ports, 25, 587, 465, set useSSL to false, true, SecureSocketOptions.StartTls, SecureSocketOptions.StartTlsWhenAvailable. But zero success.

`client.ServerCertificateValidationCallback = (s, c, h, e) => true;
 client.Connect("mydomain.mail.protection.outlook.com", 25, true);
client.Authenticate("username", "password");
client.Send(message);
client.Disconnect(true);`

I've also tried using `client.AuthenticationMechanisms.Remove ("XOAUTH2"); ` in the code but make no difference. 

The error i'm getting is mainly "The SMTP server does not support authentication", but sometime "The handshake failed due to an unexpected packet format."

I have an older web API project where i'm using the .net smtp to connect with above details with no issue. Is this an account setting thing or issue in my code???

Thanks in advance

**Comment by jstedfast** [comment]
You need to match the useSsl value with the port otherwise things are bound to fail.

Port 465 is the *only* port you are *likely* to want to use `useSsl = true` with.

That explains the "unexpected packet format" error you got.

The "server does not support authentication" error means precisely that, the server does not support authentication. Which means don't call `client.Authenticate()` :)

**Comment by Mike-tech** [comment]
Thanks for the pointer for excluding `client.Authenticate()` Wow! I never saw anywhere on the net that this should be excluded. In fact i didn't think this would work without authentication.

Many thanks for quick response. :)
