### ISSUE TITLE
Searching with MessageId retuns null

### ISSUE THREAD

**Issue by PrasanthSpine** [jstedfast/MailKit#647]
I wanted to get the notification of mail exist in the current folder with current message id

CurrentMessage.MessageId = "!&!AAAAAAAAAAAuAAAAAAAAAJgr9Oae7vFOr2lkxxiHuYUBAMO2jhD3dRHOtM0AqgC7tuYAAAAAAA4AABAAAAC9RWLM+jWeRIGwiXWxRt0DAQAAAAA=@yahoo.com"

var MySearchUids = MailKitService.CurrentselectedFolder.Search(SearchQuery.HeaderContains("Message-Id", CurrentMessage.MessageId));

Here I got the MessageId,but when I am trying to search with that message id in my current folder I got  "NULL" in MySearchUids.

Why I getting Null...?

**Comment by jstedfast** [comment]
I don't know. This is why when you created this bug report, you were asked to include a [ProtocolLog](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog)

**Comment by PrasanthSpine** [comment]
Actually,When I am trying to search with message id that I received from "yahoo. com". the result is going to be null.

Is it possible to search a message in the current selected folder with unique message id..?Then, Please help me.

**Comment by jstedfast** [comment]
You can use the Search method just like you seem to have done.

Maybe you need to do `"<" + CurrentMessage.MessageId + ">"`? I don't know.

Like I said, I need a protocol log to see why it is returning null.

**Comment by PrasanthSpine** [comment]
imap.log has nothing for todays activity.

We are trying to search with "MessageId" but that particular email send from MsOutlook with Yahoo account is not retrievable, giving error "No uids were specified".
There has not been anyother mail message which has such problem.

MessageId = "!&!AAAAAAAAAAAuAAAAAAAAAJgr9Oae7vFOr2lkxxiHuYUBAMO2jhD3dRHOtM0AqgC7tuYAAAAAAA4AABAAAAC9RWLM+jWeRIGwiXWxRt0DAQAAAAA=@yahoo.com"

![img1](https://user-images.githubusercontent.com/36146341/36425074-97e7c5f4-166b-11e8-8d4b-6f84947382b9.png)

Then I am Searching with 

var MySearchUids = MailKitService.CurrentselectedFolder.Search(SearchQuery.HeaderContains("Message-Id", CurrentMessage.MessageId));

Here I get MySearchUids ={}

var results = MailKitService.CurrentselectedFolder.Fetch(MySearchUids, MessageSummaryItems.Full | MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId);


Then I fetch with  this  MySearchUids  I got Exception like "No uids were specified.\r\nParameter name: uids" but Uid also Exist in the "CurrentMessage"


![img2](https://user-images.githubusercontent.com/36146341/36425404-afb913da-166c-11e8-894a-ad48ef04ecd2.png)


This is one alternative code but we cant type cast UnQID to Mailkit.UniqueId.

int UnQID = Int32.Parse(CurrentMessage.UId);
if (MySearchUids == null || MySearchUids.Count < 1)
{
    dynamic resultss = MailKitService.CurrentselectedFolder.Fetch(UnQID, MessageSummaryItems.Full | MessageSummaryItems.UniqueId).ToList();
    foreach (var item in MailKitService.CurrentselectedFolder.Fetch(0, -1, MessageSummaryItems.Full | MessageSummaryItems.UniqueId))
    {
        var message = MailKitService.CurrentselectedFolder.GetMessage(item.UniqueId);
        Render(MailKitService.CurrentselectedFolder, item.UniqueId, item.Body);
        CurrentMessage.Text = MyMessageBody;
        CurrentMessage.Text = message.HtmlBody;
    }
}


How to overcome these issues....?

**Comment by jstedfast** [comment]
This is completely wrong:

```csharp
int UnQID = Int32.Parse(CurrentMessage.UId);
if (MySearchUids == null || MySearchUids.Count < 1)
{
dynamic resultss = MailKitService.CurrentselectedFolder.Fetch(UnQID, MessageSummaryItems.Full | MessageSummaryItems.UniqueId).ToList();
```

You are using the unique id as an index into the folder, so that will not work. UniqueIds are not the same thing as indexes.

Your MySearchUids is empty (not null!) because the server returned an empty list of matches. It is empty because the server is not finding that message id. Either the server's search algorithm is broken or the message id you are giving it really does not exist.

**Comment by PrasanthSpine** [comment]
Thanks for your replay....

When I am searching with "MessaageId" that sent from gmail account that working fine and here I get "MySearchUids" perfectly

![mailkitgmail01](https://user-images.githubusercontent.com/36146341/36467364-6e96e524-1704-11e8-8a42-3005b094d9aa.png)


![mailkitgmail02](https://user-images.githubusercontent.com/36146341/36466618-11788d5a-1701-11e8-9f04-0ce5a5ab396e.png)

The issue(MySearchUids is empty) is coming only when search with "MessageId"  that  send from MsOutlook with Yahoo account.This figure shown below list shown the uid but not get it this in search.

![mailkiterror](https://user-images.githubusercontent.com/36146341/36467379-7ff2ff74-1704-11e8-8e82-a6afbe2922c5.png)


![mailkitgmail03](https://user-images.githubusercontent.com/36146341/36467223-ce543e72-1703-11e8-8e9a-f22fbe2913b2.png)

why this happening...?

**Comment by jstedfast** [comment]
I don't know, but I can tell you it's not a bug in MailKit.

Have you tried adding "<" ">" around the message-id string to see if that works? I've noticed that some IMAP servers expect `<>`'s and some do not.

**Comment by dylangmiles** [comment]
Hello Jeffrey,

Thank you for a great library. I have a similar problem with searching for a Gmail by Message-Id starting with `!&!..`. in that it returns no results (empty list of uids). 

Other messages on the same server are found okay.

Tried:
`var uids = folder.Search(SearchQuery.HeaderContains("Message-Id", $"<{message.MessageId}>"));`

and

`var uids = folder.Search(SearchQuery.HeaderContains("Message-Id", message.MessageId));`

I have tried wrapping the Message-Id in <>'s like you suggest but still not working.

I have included a protocol log with a search for the problem email as well as one that is working. 
[plog-INBOX-1.20180214.log](https://github.com/jstedfast/MailKit/files/2965332/plog-INBOX-1.20180214.log)

I have also included a screen shot of the headers of the email not being found.
![2019-03-14_10-14-03](https://user-images.githubusercontent.com/5096688/54341706-2b04d180-4643-11e9-8282-96faa98cd236.png)


It is very strange, in that it almost seems like the problem is tied to the message id itself with both my one and PrasanthSpine's message id having `!&!...` in front.

This is against a Gmail IMAP server.

Kind Regards,
Dylan

**Comment by jstedfast** [comment]
What if you strip the leading "!&!" string, e.g.:

```csharp
var id = message.MessageId.Trim ('!', '&');
var uids = folder.Search(SearchQuery.HeaderContains("Message-Id", id));
```

**Comment by dylangmiles** [comment]
Thanks for the suggestion. 

Unfortunately does not work, even tried a few characters from the middle of the Id to use for the search.

Going to log these over the next while and to identify more examples and see if a pattern emerges.

**Comment by lbrosacan** [comment]
I have same problem! Any solutions?

**Comment by jstedfast** [comment]
@lbrosacan have you tried putting the message-id string in `<>`'s?

The problem with IMAP is that every server implements SEARCH differently (they will all implement the same search commands, but the implementation of how they do the matching is all different).

If you look at the raw MIME of the message, is the Message-ID header folded in any way? Or encoded in any way?

If so, the server might not be unfolding (or decoding) when applying its matching algorithm in its SEARCH implementation - in other words, it might be matching against the raw header value instead of the canonical value.

**Comment by jstedfast** [comment]
@sachinshrestha483 see my previous comment. Look into those issues and report back and maybe I can make suggestions on what to do.

Short of that, you'll have to forego server-side searching and do client-side searching instead.
