### ISSUE TITLE
IMAP /SMTP client connection is very slow

### ISSUE THREAD

**Issue by docrizwan** [jstedfast/MailKit#656]
Yo Jeff,
I'm using your library and loved this...

Now, I'm facing an issue regarding speed. [ in backend, I'm creating new ImapClient on each operation on server in "using" code block  (`using (var client = new ImapClient() { client.connect() })`)]
Imap or Smtp client creation and connection with server (using email, password, incoming/outgoing server with ports) and FOLDER opening (by `client.GetFolder()` ) takes much time and makes the overall process much slower.

Is there a way to speed this up? or any valuable suggestions are highly appreciated.
Thank you so much!

**Comment by jstedfast** [comment]
I would recommend keeping the ImapClient reference and not disposing it after each minor usage.

Most likely this will mean you'll have to stop using it in a `using` statement and instead have some sort of application-level reference to the ImapClient so that you can reuse them over and over again.

You will also need to keep the connection alive by invoking client.NoOp() every once in a while (I would recommend calling NoOp() every 5-10 minutes or so).

For SMTP, I would recommend queueing a bunch of messages to send and then sending all of them like this:

```csharp
using (var client = new SmtpClient ()) {
    client.Connect (.....);
    client.Authenticate (....);

    for (int i = 0; i < messages.Count; i++)
        client.Send (messages[i]);

    client.Disconnect (true);
}
```

**Comment by docrizwan** [comment]
Thank you, got your point.
Another angle to apply your proposed solution is to apply lazy loading (means when the client is not connected, connect it immediately, else return client)
Just a lil thing to ask more, In my scenario, a user can have multiple accounts even more than 10. How should I maintain clients for multiple accounts (user is free to do any operation on any connected account, e.g. MarkRead on Acc1, Compose in Acc2, Sync in Acc3, all in a go, etc)

Any better technique to manage alive ImapClient /SMTP client?

**Comment by jstedfast** [comment]
Have an Account object which stores an SmtpClient and an ImapClient that you can easily look up based on account name or email address or something.

**Comment by glowysourworm** [comment]
Hello, I'm a new user to this API. There's a more performant way to get the messages back, which should've been put here.

When using the client, find a way to get all messages with one call. I've found at least one; and the developer should be able to list all the rest of them:

                    var folder = client.GetFolder(MailKit.SpecialFolder.All);
                    folder.Open(FolderAccess.ReadOnly);

                    var messages = folder.Fetch(0, folder.Count - 1, MessageSummaryItems.All);

                    foreach (var message in messages)
                    {
                        // write the message to a file
                        Console.WriteLine("Message:  {0}", message.NormalizedSubject);
                        Debug.WriteLine("Message:  {0}", message.NormalizedSubject);
                    }

The only question I currently have is how to make sure the API returns the whole message. There is only a MessageSummary option that I see. Perhaps jstedfast has a better way?

Thanks.

**Comment by jstedfast** [comment]
@glowysourworm 

I'm not sure I'd say that fetching all messages in a folder all at once is the most performant way of doing it.

If the folder contains hundreds of thousands of messages, for example, it could take a really long time for that Fetch() method to return (e.g. 10+ minutes even on a super fast connection).

I would say you need to take into consideration:
1. the type of application you are writing (does the user expect the list of messages to be interactive while they are being fetched?)
2. network/server reliability (if there are a significant number of messages, the odds of the connection being dropped during that Fetch() increase which means you'll need to re-connect and re-send the Fetch request, ideally where the previous attempt left off rather than from the beginning again)
3. likely other factors that aren't immediately coming to mind right now

As with all things, there are compromises that need to be made.

In an ideal world where network/server connectivity is not an issue, yes, a giant Fetch() request that fetches the summary information for all messages at once will technically complete faster than a series of Fetch() requests that request smaller batches (100 or 1000, for example) at at time... BUT it is much easier and less costly to recover from a failed Fetch() request for a smaller number of messages than a single giant Fetch() request.

Similarly, a series of smaller Fetch() requests allow you to incrementally populate the message list for your users while they wait and would also allow your app to inject other commands (like fetching the content of the message) between those Fetch() requests if the user clicks on a particular message, for example.

That said, ImapFolder has a [MessageSummaryFetched](https://mimekit.net/docs/html/E_MailKit_MailFolder_MessageSummaryFetched.htm) event that will be emitted for each and every `* 123 FETCH ...` response the client gets from the server, allowing you to incrementally populate a message list and/or local cache and I would highly recommend making use of that event for local synchronization to reduce the need to re-fetch message summaries if a connection gets dropped in the middle of your Fetch() request.

> The only question I currently have is how to make sure the API returns the whole message. There is only a MessageSummary option that I see. Perhaps jstedfast has a better way?

You can't. While the IMAP protocol does allow for such requests, it is generally not good practice because messages can be quite large and requesting a large batch of messages to all be loaded into memory in a single request would have the potential to result in local memory exhaustion.

I wouldn't recommend it.

The IMAP protocol is designed such that clients generally should not request the content of every message all at once anyway - the idea of IMAP is that the message content is stored remotely and the client only really needs the summary information to display to the user and should only fetch the message content when the client needs to render the message in response to the user selecting it for reading... and even then, it's not really necessary (for a properly implemented client) to download the full message because they can use the summary info to request only the necessary part(s) needed for rendering the message, leaving the attachments for download if-and-only-if the user asks the client to save them locally.

That's why ImapFolder has methods like GetBodyPart().

**Comment by glowysourworm** [comment]
@jstedfast I'm going to create a fork of MailKit, then, to add the batch methods required to create a server architecture, because these methods are needed to help manage mail servers. Thank you for doing so much research on the IMAP protocol - it greatly helps out people trying to learn.

The Fetch method is working fine, and can be throttled to handle bottle necks. A GetBodyPart() investigation will take time to reveal whether or not it fully fetches the contents of the MimeMessage.

Thanks very much.

**Comment by jstedfast** [comment]
@glowysourworm what type of app are you writing? Are you saying you are writing a mail server?

**Comment by glowysourworm** [comment]
> [@glowysourworm](https://github.com/glowysourworm) what type of app are you writing? Are you saying you are writing a mail server?

I'm going to write a portion of a desktop app as a simple server queue. Completing the entire IMAP detail may not get done; but I'm wanting to manage the data portion of the application myself because I have large email accounts.

The application will have a separate core for the server and database portion, which may be used in a server application; but it's not really important how it's used.

**Comment by jstedfast** [comment]
> but I'm wanting to manage the data portion of the application myself because I have large email accounts.

This seems like all the more reason not to download all of the raw messages, no?

**Comment by glowysourworm** [comment]
> > but I'm wanting to manage the data portion of the application myself because I have large email accounts.
> 
> This seems like all the more reason not to download all of the raw messages, no?

Well, you can minimize the memory footprint if you manage what data comes over and when. What most applications do is to wait to download the email body and attachments until the user clicks on an email, unless the user specifies to download them locally. What I'm working on is to build a server-like portion that will manage local email storage (of the entire body); and can handle how to queue and manage throttling the queue politely.

Do you know of anyone who has built an email viewer component for the MailKit.BodyPart component tree that you have built? What viewer do you usually use in a desktop client?

Thanks.

**Comment by jstedfast** [comment]
https://github.com/jstedfast/MailKit/blob/master/samples/ImapClientDemo/ImapClientDemo/MainWindow.cs

That renders the message using the BosyPart tree instead of downloading the full message.

There's no caching there, but in a real client, I'd cache the body parts.

Btw, I just remembered that ImapFolder has a GetStreams method that would allow downloading a list of messages (they just don't get parsed into MimeMessages): https://mimekit.net/docs/html/M_MailKit_Net_Imap_ImapFolder_GetStreams.htm

There's also an asynchronous version.

This API is better than returning a list of MimeMessages because messages can be huge and keeping potentially thousands or even a million messages in RAM would be insane.

This provides a callback allowing you to save to disk immediately as they are sent by the server.

**Comment by glowysourworm** [comment]
@jstedfast 

Which parts of this did you build? There must be some older existing backend. What clients / servers use MailKit? 

I'll give GetStreams a try. There has to be batch methods if anyone bothered to build a client even because the GetMessage (example) takes like 20 minutes to complete, at least for my first gmail client.

Fetch works as far as I know. I have yet to render the retrieved HTML body.

There are some inefficiencies either in authentication, or during web calls, that we should work through. How long does a fetch take for your client? Have you built a desktop client for MailKit?

**Comment by jstedfast** [comment]
@glowysourworm 

> Which parts of this did you build?

Which parts of what did I build? I wrote all of MimeKit and MailKit if that's what you are asking. I also wrote the samples.

>  There must be some older existing backend.

I'm not sure what you're talking about.

> What clients / servers use MailKit?

I don't have a list of the clients and servers that make use of MimeKit and MailKit. I haven't written a client or server that uses them yet (don't have the time).

> There has to be batch methods if anyone bothered to build a client even because the GetMessage (example) takes like 20 minutes to complete, at least for my first gmail client.

I've written email clients in C before (long before I wrote MimeKit and MailKit) and they did not batch request full messages from the IMAP server.

I would bet anything that the reason GetMessage takes 20 minutes for you when connected to GMail is because GMail is throttling you because you've been batch requesting large amounts of data (they tend do that).

> There are some inefficiencies either in authentication, or during web calls, that we should work through. How long does a fetch take for your client? Have you built a desktop client for MailKit?

The amount of time that a Fetch request takes will depend on how many messages you have, your network speed, the MessageSummaryItems you are asking for, the server implementation (and whether it has stuff cached or not), etc.

Perhaps you could profile your app to see where the hot spots are?

The only desktop client I've written using MailKit is the ImapClientDemo in the samples directory. It's not a particular stellar client, but it's all I've had time for.

**Comment by glowysourworm** [comment]
Oh, are you the guy on the couch here? 

https://mimekit.net/ 

How's your company doing? ^_^

**Comment by jstedfast** [comment]
Doing well. We got bought by Microsoft in 2016.

I'm working on Office365 Exchange now.
