### ISSUE TITLE
MailService.ConnectAsync has odd behaviour for useSsl parameter

### ISSUE THREAD

**Issue by codepb** [jstedfast/MailKit#667]
I've been using MailKit, and specifically the SmtpClient. When using ConnectAsync on localhost whilst debugging I was getting an SSL certificate error regardless off the value I passed to useSsl.

This may be my lack of understanding, so didn't want to create a pull request directly, but I've tracked this back to MailService and this line of code (670):

    this.ConnectAsync(host, port, (SecureSocketOptions)(useSsl ? 2 : 4), cancellationToken);

This translates to SecureSocketOptions.SslOnConnect for true and SecureSocketOptions.StartTlsWhenAvailable for false. This behaviour seems odd, and I would expect false to translate to SecureSocketOptions.None, though this may be my lack of understanding of how StartTlsWhenAvailable works.

If this is deemed an error, I'm happy to create a pull request with a fix. If it's not an error and just my lack of understanding, I apologise for raising the issue!

**Comment by jstedfast** [comment]
That is the desired behavior.

For background:

- `SslOnConnect` means that the service is "SSL-wrapped", meaning that the client needs to be in SSL mode immediately on connection before it sends or receives anything from the server.

- `StartTls` means that the client should use the STARTTLS command (this happens *after* connecting, reading the greeting from the server and getting the server's capabilities) and bomb if the server doesn't support it (this is to make sure that you never assume that the connection is encrypted when it really isn't).

- `StartTlsWhenAvailable` means that the client should use STARTTLS if the server supports it, otherwise fall back to using the cleartext protocol. I.e. the client isn't overly concerned with privacy.

How do you map these 3 values to a single bool? You can't.

So I took the only logic choice: make it map to `SslOnConnect` vs `StartTlsWhenAvailable`.

**Comment by jstedfast** [comment]
Generally, also, when people think of `useSsl`, they think SSL-wrapped connections and not STARTTLS.

**Comment by codepb** [comment]
Thanks for the advice. The reason I was confused was I was getting an untrusted SSL certificate error when connecting, even when setting useSsl to false. This was obviously confusing. The way you have described it makes sense, and also I understand why I was getting the issue.

**Comment by jstedfast** [comment]
Cool, glad my explanation helped. You aren't the first person to be confused by the true/false `useSsl` argument and probably won't be the last. It's a terrible API, I agree, which is why I also provide the overload that takes an enum.
