### ISSUE TITLE
Unilateral response

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#685]
Not sure if this an issue or working as designed. This is the raw response

C: A00000023 FETCH 38:37 (UID FLAGS INTERNALDATE RFC822.SIZE ENVELOPE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (IMPORTANCE DELIVERY-DATE)])
S: * 37 FETCH (UID 11882 FLAGS () INTERNALDATE "16-Mar-2018 14:02:54 +0200" RFC822.SIZE 5906 ENVELOPE ("Fri, 16 Mar 2018 15:02:53 +0300" "Plain text attachment" ((NIL NIL "a.a" "a.com")) ((NIL NIL "a.a" "a.com")) ((NIL NIL "a.a" "a.com")) (("'a a'" NIL "a.a" "a.com")) NIL NIL NIL "<0afe01d3bd1e$b70011e0$250035a0$@a.com>") BODYSTRUCTURE ((("text" "plain" ("charset" "us-ascii") NIL NIL "7bit" 26 8 NIL NIL NIL NIL)("text" "html" ("boundary" "----=_NextPart_000_0AFF_01D3BD2F.7A897E20" "charset" "us-ascii") NIL NIL "quoted-printable" 3980 130 NIL NIL NIL NIL) "alternative" ("boundary" "----=_NextPart_001_0134_01D3C5BC.8584E900") NIL NIL NIL)("text" "plain" ("name" "text.txt" "charset" "us-ascii") NIL NIL "7bit" 13 0 NIL ("attachment" ("filename" "text.txt")) NIL NIL) "mixed" ("boundary" "----=_NextPart_000_0133_01D3C5BC.8584E900") NIL ("en-us") NIL) BODY[HEADER.FIELDS (IMPORTANCE DELIVERY-DATE)] {2}
S: 
S: )
S: * 38 FETCH (UID 11883 FLAGS () INTERNALDATE "07-Mar-2018 10:52:34 +0200" RFC822.SIZE 2548 ENVELOPE ("Wed, 7 Mar 2018 11:52:34 +0300" "test" (("test" NIL "test1" "a.com")) (("test" NIL "test1" "a.com")) (("test" NIL "test1" "a.com")) (("a.a" NIL "a.a" "a.com")(NIL NIL "a.a" "a.com")) NIL NIL NIL "<AEH8IWVQT3U4.DTNWQR4OCRAN1@DESKTOP-I1FS3O9>") BODYSTRUCTURE ((("text" "plain" ("charset" "utf-8") NIL NIL "7bit" 106 5 NIL NIL NIL NIL)("text" "html" ("boundary" "----=_NextPart_000_05F3_01D3BB96.7C476AA0" "charset" "utf-8") "<UGJTJWVQT3U4.7R1ZN34I6A7V@DESKTOP-I1FS3O9>" NIL "quoted-printable" 535 23 NIL NIL NIL NIL) "alternative" ("boundary" "----=_NextPart_001_013C_01D3C5BC.8C432310") NIL NIL NIL)("application" "octet-stream" ("name" "Untitled attachment 00304.dat") NIL NIL "7bit" 4 NIL ("attachment" ("filename" "Untitled attachment 00304.dat")) NIL NIL) "mixed" ("boundary" "----=_NextPart_000_013B_01D3C5BC.8C432310") NIL NIL NIL) BODY[HEADER.FIELDS (IMPORTANCE DELIVERY-DATE)] {2}
S: 
S: )
S: * 29 FETCH (MODSEQ (15845) FLAGS ())
S: * 36 FETCH (MODSEQ (15845) FLAGS ())
S: * 38 FETCH (MODSEQ (15845) FLAGS ())
S: A00000023 OK Fetch completed (0.001 + 0.000 secs).

I saw MailKit returned total of 4 MailMessageSummaries. We have 5 FETCH responses from the server.
I wonder if Mailkit is merging the two lines for message index 38 in a single MailMessageSummary?

Not sure why the server is sending unilateral flag response for the message we explicitly requested flags for.

**Comment by jstedfast** [comment]
Yes that's what MailKit is doing and yes it's functioning by "design".

The IMAP specifications allow for servers to return multiple untagged FETCH responses for the same message and the client is expected to merge them.

For example, if I request ENVELOPE and BODYSTRUCTURE, the server could respond with 2 untagged FETCH responses - one with the ENVELOPE data and one with the BODYSTRUCTURE data.

MOST servers will use a single FETCH response per message with all of the requested data, but not all of them will do it all of the time.

In this particular case, what is happening is that it is responding to the request with all of the data and the last 3 untagged FETCH responses are flag change events - probably because another client just updated those flags as the server was responding to your request.
