### ISSUE TITLE
The SMTP server has unexpectedly disconnected.

### ISSUE THREAD

**Issue by njvolz** [jstedfast/MailKit#695]
To help me debug your issue, please explain:
- What were you trying to do? I was attempting to send a file via .net/c# that contained an attachment around 4.5mb.
- What happened? During client.Send I got back an error "The SMTP server has unexpectedly disconnected." after a bit of a wait. The email did however go through and with the attachment.
- What did you expect to happen? I would have expected it to send without an exception being thrown. This was sort of the reason I was switching over to using MailKit because the .Net Smtp client had a known issue with file attachments over 3mb.
- Step-by-step reproduction instructions and/or a simple test case.
Protocol log is attached (some values changed for privacy)
[imap.log](https://github.com/jstedfast/MailKit/files/1881920/imap.log)

**Comment by jstedfast** [comment]
The problem is that the server never responded once the message had been uploaded.

After the `DATA` command has been terminated, the SMTP server should respond saying that the message has been accepted, but it dropped the connection.

This doesn't indicate a bug in MailKit, it just indicates that either the server dropped the connection (on purpose or due to a bug) or the you simply lost your network connection.

**Comment by njvolz** [comment]
Fair enough. Any idea why it only happens with messages containing larger attachments? Or should I just contact the host to see if they have any insight?

**Comment by jstedfast** [comment]
Well, larger attachments are going to require the socket to stay connected longer (takes time to upload large amounts of data) and therefore increases the likelihood that it gets disconnected.
