### ISSUE TITLE
Away Notes and Meeting invitations

### ISSUE THREAD

**Issue by mbeckenbach** [jstedfast/MailKit#701]
Hi, 

Im fetching mails via pop3. Is there a best practice way to detect away notes and meeting invitations.

I guess the meeting invitations could be detected by checking if there is an attachment with an .ics file. But what about away notes? Those look different depending on the sender, correct?

Thanks in advance

Max

**Comment by jstedfast** [comment]
I think you're probably on the right track for meeting invites, but I'm not at all familiar with away notes. The ones I've seen are just normal text messages with some sort of blurb about being away, so that doesn't sound like something that would be easy to recognize without a serious risk of false positives and/or false negatives.

I guess if you are writing this for a particular office where all of the employees use the same template for their away notes, then that might be doable. Other than that, it sounds like you'd need a natural language parser and/or some sort of bayesian-like filter.

Good luck, I hope you find a solution...

**Comment by mbeckenbach** [comment]
Outlook shows a special icon for away notes. There must be something to detect it. Maybe I should have a look at some headers from different mail servers.

Beste Grüße
Max Beckenbach

Am 19.04.2018 um 15:48 schrieb Jeffrey Stedfast <notifications@github.com<mailto:notifications@github.com>>:


I think you're probably on the right track for meeting invites, but I'm not at all familiar with away notes. The ones I've seen are just normal text messages with some sort of blurb about being away, so that doesn't sound like something that would be easy to recognize without a serious risk of false positives and/or false negatives.

I guess if you are writing this for a particular office where all of the employees use the same template for their away notes, then that might be doable. Other than that, it sounds like you'd need a natural language parser and/or some sort of bayesian-like filter.

Good luck, I hope you find a solution...
