### ISSUE TITLE
Best way to fetch all emails for import processing

### ISSUE THREAD

**Issue by marco-bue** [jstedfast/MailKit#706]
Hi, first I want to say that this is an awesome library. Thank you for putting so much effort into it.

I have some server process running which needs to import all emails from an IMAP inbox into a database. As I am not familiar with the things I can expect from an arbitrary IMAP server, I am not quite sure about the best way to do it.

It is very important that I do not "miss" any mail.
I thought about the following algorithm (pseudo-code):

````
minIndex = 0     // when running first time, just get all mails
summaries = inbox.Fetch(minIndex, -1, ...)
for (var i = 0 ; i < summaries.Count; ++i ) {
    if (not yet imported summaries[i].mailId) {
       import(summaries[i]);
    }

   if (import okay) {
      minIndex = i + 1;       // next time the process starts, fetch after last imported mail
   }
}
`````

This assumes the following:
- When fetching index 0 to -1, I get always all emails within the inbox
- Same indices used on fetch will always produce the same result. It is not dependant on sorting etc.
- On new emails, the index used by fetch is incremented. Let an inbox contain mails with indices i_0 .. i_n, then a new mail will have an index i >= i_n + 1.
- A mail will always have the same mail id.

Can I make these assumptions?
If not, what would be the right way to retrieve all emails in a reliable way?

Thank you in advance.

**Comment by jstedfast** [comment]
Indices is the wrong way to track which messages you have seen because another client could delete a message.

You need to use the summary.UniqueId combined with the folder.UidValidity value to determine if you've seen a message or not.

The folder.UidValidity value should rarely ever change (but can if the server restores from a backup or if another client deletes all messages in the folder, then deletes the folder, and finally recreates said folder... it *might* get a new UidValidity).

The summary.UniqueId is the unique identifier for the message in the folder and is the only reliable way to identify them.

In order to make sure that the summary.UniqueId value is set, you'll need to pass `MessageSummaryItems.UniqueId` as one of the fields to the `Fetch()` method (these flags can be bitwise-or'd together to request multiple items).

Hope that helps.
