### ISSUE TITLE
IMAP connection losing automatically 

### ISSUE THREAD

**Issue by SumitRamco** [jstedfast/MailKit#707]
I was using MailKit to get notification and read new mails. But faced problems when I tried using it for long interval of time.
1. The connection was lost sometimes without any logs ; (ProtocolLogger(Console.OpenStandardError()))
2. The connection was lost with some logs saying "Outlook signing off " (Don't have exact error right now)

So I am connecting my Outlook office email using MailKit with timer being set as 9 minutes.

I am not able to figure it out why my connection is losing automatically.

**Comment by jstedfast** [comment]
IMAP servers can disconnect you for any reason at any time. Typically, they will hold a connection open for at least 10 minutes but I have found that to not always hold true. GMail, for example, will almost always kick me off if my client idles for more than somewhere around 9 minutes.

You just have to handle re-connecting when that happens.

That said, have you tried lowering your interval to, say, 5 minutes instead of 10?

**Comment by jstedfast** [comment]
Yes.

Catch `ImapProtocolException` exceptions and then you can check `client.IsConnected` to see if you need to reconnect or not.

I think the `Disconnected` event also gets emitted, but I'm less sure on that offhand.

**Comment by jstedfast** [comment]
You will get an ImapProtocolException the next time you attempt to send a command.
