### ISSUE TITLE
Unable to send an email useSsl =false at local smtp server 

### ISSUE THREAD

**Issue by alirazaedev** [jstedfast/MailKit#709]
I m try to send an email using my smpt live server port 465 useSsl=true with below code it run correctly and email sent but when i try to send an email using my local smpt server port 25 useSsl=false.

Environment
language C#
window 10

Below is the code i m trying it throw an exception 
 
```csharp
MailKit.Net.Smtp.SmtpClient client = null;
using (client = new MailKit.Net.Smtp.SmtpClient())
                {
                   
                    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    client.Connect(IpAddress, 25, false);                  
                    client.Send("here is object of  MimeMessage");
                    client.Disconnect(true);
                    client.Dispose();                  
                } 
```

Exception at below
message: The SMTP server has unexpectedly disconnected.

```
StackTrace:   at MailKit.Net.Smtp.SmtpStream.<ReadAheadAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpStream.<ReadResponseAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpStream.ReadResponse(CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.<DataAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MailKit.Net.Smtp.SmtpClient.<SendAsync>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
```

Please reply what is going wrong 
i want to fix that

**Comment by alirazaedev** [comment]
Below are the version  i m using
BouncyCastle.1.8.1
MailKit.2.0.3
MimeKit.2.0.3

**Comment by rolandjordan** [comment]
Have you correctly setup a mailing server? You'll need more than just port number to send mails from your local workstation...

This issue seems to be unrelated to MimeKit TBH.

**Comment by alirazaedev** [comment]
mail server is correctly setuped because before using mimekit I m using below code System.Net.Mail it runs correctly but it not sending email when  set client.EnableSsl=true that is problem with below code

 using (SmtpClient client = new SmtpClient(smtpSection.Network.Host))
                {
                    client.EnableSsl = smtpSection.Network.EnableSsl;
                    client.Host = smtpSection.Network.Host;
                    client.UseDefaultCredentials = false;
                    client.Credentials = new NetworkCredential(smtpSection.Network.UserName,
                        smtpSection.Network.Password);
                    client.Port = smtpSection.Network.Port;
                
                 }

**Comment by alirazaedev** [comment]
whith local smpt server what is the code to send an email using mimekit
local smpt server use port=25 and enablesll=false

**Comment by jstedfast** [comment]
Based on the stack trace, it looks like the SmtpClient gets all the way to the `DATA` command before getting disconnected.

This means that it was able to successfully establish a connection with your local SMTP server, authenticate, and specify which recipients to send the message *to*, but the connection was lost for some reason during the actual upload of the message to the server.

Typically when something like this happens, either:

1. There was a network outage for the server (e.g. a hickup with its router)
2. There was a network outage for the client (e.g. a hickup with your router)
3. The server dropped your connection for some other reason (reboot? out of resources? server bug? protocol violation in the client?)

In general, 1 and 2 aren't the problem if you are connecting to a local server, especially if it continues to happen, but I listed them because it's important not to completely dismiss them as possibilities to consider if other avenues don't pan out.

That leaves option 3 as the likely culprit. My first instinct is to ask how large the message is - is it a simple text-only message or does not have large attachment(s) that might exceed the server's message size limit (often 25MB, but sometimes less, sometimes more)?

If that doesn't seem to be a likely cause, my next suggestion is to send me a [protocol log](https://github.com/jstedfast/MailKit/blob/master/FAQ.md#ProtocolLog) so that I can see if I can figure out what might have gone wrong (or at least verify that it's not a protocol violation on the client's side).

If you need to send me a protocol log, feel free to scrub the AUTH command data so that your credentials are safe (even if you email them to me, I won't use them or decode them, but no sense risking exposure of them unnecessarily and I highly doubt they will be necessary to diagnose the issue).

**Comment by jstedfast** [comment]
Oh, and since you know you'll be sending me a protocol log which will contain the message data, feel free to craft it such that it does not contain anything sensitive either.

**Comment by alirazaedev** [comment]
Please find the attached log

**Comment by alirazaedev** [comment]
please find the attached log
[smtp.log](https://github.com/jstedfast/MailKit/files/2030168/smtp.log)

**Comment by jstedfast** [comment]
Doesn't seem like the message would qualify as being too large for any SMTP server to accept, so I think we can safely rule out that potential explanation.

I noticed that the server supports authentication and that you didn't authenticate. Is it *possible* that the server is dropping your connection at the end of the DATA content being submitted because you didn't authenticate?

Truthfully, if that is the case, I would call shenanigans on the SMTP server for doing that since it should have errored out much sooner if it wants you to authenticate first, but SMTP servers do weird things sometimes.

I don't think there's a bug in MailKit's SmtpClient here, it seems to have gotten disconnected before MailKit could read a response from the server.

**Comment by alirazaedev** [comment]
1) I have an smtp server where ssl certificate installed that require authentication and for that my code is 
    using (var client = new MailKit.Net.Smtp.SmtpClient())
                {                 
                    client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                    client.Connect(host, port, ssl);
                    // Note: only needed if the SMTP server requires authentication
                    client.Authenticate(u, p);
                    client.Send(mailMessage);
                    client.Disconnect(true);
                    client.Dispose();                    
                }

Parameter i m passing  to client.Connect(host, port, ssl); is port=465 with ssl=true and port=25 with ssl=false in both cases it run correctly.


2) **Problem**  I have an smtp server where ssl certificate not installed and that require no authentication, relay based user configured on that server
    using (var client = new MailKit.Net.Smtp.SmtpClient())
                {                                    
                    client.Connect(host, port, ssl);                
                    client.Send(mailMessage);
                    client.Disconnect(true);
                    client.Dispose();                    
                }
Parameter i m passing  to client.Connect(host, port, ssl); is port=25 with ssl=false in this cases it throw an exception that i was mentioned in my first comment at top

**Comment by alirazaedev** [comment]
but i want to solution with Mailkit

**Comment by jstedfast** [comment]
Try this:

```csharp
using (var client = new MailKit.Net.Smtp.SmtpClient())
{
    client.Connect(host, port, ssl);
    client.Capabilities &= ~SmtpCapabilities.Pipelining;
    client.Send(mailMessage);
    client.Disconnect(true);
}
```

**Comment by alirazaedev** [comment]
Thanks
try above code the issue resolved please can you explain client.Capabilities and can i go with this in production environment where different servers may support different type of capabilities.
how can i check a server support how many capabilities and and after connect what is the default values of capabilities.

**Comment by jstedfast** [comment]
The `Capabilities` property just specifies which SMTP extensions that the server claims to support. In your case, the server claims to support the `PIPELINING` extension but seems to break when the client actually uses it.

What my code above does is it removes the `Pipelining` flag from the property so that the `SmtpClient` doesn't try to use it.

You can disable any feature that the server supports using the above technique if you think it may be causing interoperability problems.

I suggested removing `PIPELINING` since I know some SMTP servers break when that extension gets used.

That's the only extension I know of that causes problems sometimes, so I don't think you have to worry about any others.

You will always be safe disabling `PIPELINING` (even if the server doesn't support it - it'll just end up being a no-op), so feel free to do that.

**Comment by wonea** [comment]
I'm using Papercut and cannot send use SMTP with MailKit, but sending a message from PowerShell (using Net.Mail.SmtpClient) does work.

MailKit error
mailkit syntax error, 3 retry(ies) remaining

```
using (var client = new MailKit.Net.Smtp.SmtpClient())
{
	client.Capabilities &= ~SmtpCapabilities.Pipelining;
	client.Connect("localhost", 25, false);
	client.Send(message);
	client.Disconnect(true);
}
```

If with MailKit I change the localhost to smtp://localhost then I no longer get a syntax error, but server is not found. Is there broken regex somewhere?

**Comment by jstedfast** [comment]
I don't know what that syntax error is, but it's not from MailKit. MailKit has 0 regex usage and does not do anything with the hostname except pass it to Socket.Connect().

You can see the socket connect logic here: https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/SocketUtils.cs#L55

The host string is the exact string you passed into the client.Connect() method.

**Comment by jstedfast** [comment]
BTW, `client.Capabilities &= ~SmtpCapabilities.Pipelining;` is pointless to do before connecting / authenticating.

**Comment by wonea** [comment]
My code is running on <TargetFramework>netcoreapp2.2</TargetFramework>
Looking at the #If directives, surely netcoreapp2.2 will use netstandard2.0

**Comment by jstedfast** [comment]
Correct, that's what I would expect, too.

**Comment by vmakwana** [comment]
Similarly, i set the useSsl to false but the client.connect still tries to initiate SSl/TLS and fails on following error:

An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

**Comment by jstedfast** [comment]
The `useSsl` argument only tells MailKit whether the port that you are connecting to is an SSL-wrapped port, e.g. port 465 for SMTP, port 993 for IMAP, or port 995 for POP3.

If you do not want MailKit to use the STARTTLS command when connecting to a plain-text port, then you need to use:

```csharp
client.Connect (host, port, SecureSocketOptions.None);
```
