### ISSUE TITLE
Slow authentication - against Office 365

### ISSUE THREAD

**Issue by SarathyEST** [jstedfast/MailKit#715]
I am using MailKit - Xamarin iOS app. Authentication & sending a simple mail against imap for Office 365 taking 20sec. or more. Any idea why? Am I missing anything?

```csharp
        public void SendEmail(string Response)
        {
            var AccountDetails = ReadAccountDetails();
            string FromMail = AccountDetails.Email;
            string ToMail = (!string.IsNullOrEmpty(AccountDetails.SharedEmail) ? AccountDetails.SharedEmail : AccountDetails.Email);
            string Password = AccountDetails.Password;
            int SmtpPort = AccountDetails.PortNumber;
            string Host = AccountDetails.Server;
            try
            {
                var message = new MimeMessage();
                var builder = new BodyBuilder();
                message.From.Add(InternetAddress.Parse(FromMail));
                message.To.Add(InternetAddress.Parse(ToMail));
                message.Subject ="Approval";
                byte[] byteArray = Encoding.UTF8.GetBytes(Response);
                MemoryStream stream = new MemoryStream(byteArray);
                builder.Attachments.Add( "message.json" ,stream);
                message.Body = builder.ToMessageBody();
                using (var client = new SmtpClient())
                {
                    client.ServerCertificateValidationCallback = (s, certificate, chain, sslPolicyErrors) => true;

                    client.Connect(Host, 25, false);
                    client.Authenticate(FromMail, Password);
                    client.Send(message);
                    client.Disconnect(true);
                }
```

On analysis, we found, this part takes time...

```csharp
                using (var client = new SmtpClient())
                {
                    client.ServerCertificateValidationCallback = (s, certificate, chain, sslPolicyErrors) => true;
                    client.Connect(Host, 25, false);
                    client.Authenticate(FromMail, Password);
                    client.Send(message);
                    client.Disconnect(true);
                }
```

**Comment by jstedfast** [comment]
How slow is it? How fast do you expect it to be? Is your expectation realistic? I.e. do other SMTP libraries send the message faster? How much faster? Have you looked at the protocol log to see if maybe the problem is that MailKit has to try multiple AUTH mechanism fallbacks before the server accepts your credentials? If so, have you tried asking MailKit to use the AUTH mechanism that works reliably?

**Comment by RhodriHuwWilliams** [comment]
Hi, I've got a similar issue - it can take up to 20s to authenticate against my Office365 account. It seems to vary between 2s and 20s. Is this expected? 

I've removed the XOAUTH2 authentication mechanism. LOGIN is the only remaining authentication mechanism.

**Comment by jstedfast** [comment]
Does your Office365 account have tarpit enabled?

This is something I just learned about and it turns out that after the first EHLO command, every command that the server receives, it will delay a configurable number of seconds before replying until the client is authenticated.

If you are connecting on port 25 or 587, try connecting on port 465. This will save you 2 commands. If your server's tarpit is set to delay 10s for each command, that will solve this.

**Comment by jstedfast** [comment]
In any case, if you are experiencing slowness, it is 100% guaranteed to be the server purposely delaying the client as an anti-spam or anti-DDoS measure.

**Comment by RhodriHuwWilliams** [comment]
Thanks for your reply. No, I don't believe so as I'm using my personal account.

Connect times out when using port 465 for smtp.office365.com.

I'll add an option to allow customers to use Microsoft's built in SMTPClient, if they also experience the same delay on authentication with MailKit.

**Comment by jstedfast** [comment]
You could always try getting a protocol log with timestamps to see if you can find the delays there. If everything in the log has more-or-less instant responses, then it probably means the slowness is in the socket connecting.

To get a protocol log with timestamps:

```csharp
var client = new ImapClient (new ProtocolLogger ("imap.log") { LogTimestamps = true });
```

**Comment by jstedfast** [comment]
FWIW, System.Net.Mail.SmtpClient keeps a connection pool alive so, if you create SmtpClients to send a single message and then dispose it and a few seconds later create another SmtpClient, send a message, etc, then you aren't creating a new TCP/IP connection, you are simply re-using an existing TCP/IP connection.

In MailKit, if you use SMtpClient the same way, you are actually creating and closing TCP/IP connections each time.

You can do the same with MailKit, but you'd need to "pool" the SmtpClients yourself and make sure to call client.NoOp() or NoOpAsync() every few minutes to keep said connection alive.

I have a feeling this is why people think MailKit is "slow" at connecting. They are comparing the time it takes to create a TCP/IP connection (in MailKit) to a dictionary lookup in System.Net.Mail and concluding that MailKit is slow by comparison.

**Comment by RhodriHuwWilliams** [comment]
Thanks. I've added the protocol log with timestamps. This is the authentication part of the log when it took 10 seconds;

2022-01-25T16:53:21Z S: 250-LO2P123CA0072.outlook.office365.com Hello [82.24.149.111]
2022-01-25T16:53:21Z S: 250-SIZE 157286400
2022-01-25T16:53:21Z S: 250-PIPELINING
2022-01-25T16:53:21Z S: 250-DSN
2022-01-25T16:53:21Z S: 250-ENHANCEDSTATUSCODES
2022-01-25T16:53:21Z S: 250-AUTH LOGIN XOAUTH2
2022-01-25T16:53:21Z S: 250-8BITMIME
2022-01-25T16:53:21Z S: 250-BINARYMIME
2022-01-25T16:53:21Z S: 250-CHUNKING
2022-01-25T16:53:21Z S: 250 SMTPUTF8
2022-01-25T16:53:23Z C: AUTH LOGIN
2022-01-25T16:53:23Z S: 334 VXNlcm5hbWU6
2022-01-25T16:53:23Z C: ********
2022-01-25T16:53:23Z S: 334 UGFzc3dvcmQ6
2022-01-25T16:53:23Z C: ********
2022-01-25T16:53:33Z S: 235 2.7.0 Authentication successful

OK, thanks for explaining the differences between the two. 

Using MailKit, rather than System.Net.Mail.SmtpClient, has resolved a few issues that some of our customers have reported recently. It does seem to be more reliable. 

I'll look into changing our emailing process to use a background thread, or move it to the server side.

**Comment by jstedfast** [comment]
Looks like the 10s delay is after the client sends the password.

There's also a ~2s delay between when the client received the EHLO response and when it sent the AUTH command. There could be 2 reasons for that:

1. There's a ~2s delay somehow between `client.Connect (...)` and `client.Authenticate (...)`?
2. The socket wouldn't accept data for ~2s? (not entirely sure if this would be a local OS issue or if it could depend on the server's socket not being ready to accept data - I suspect it'd be local only, but I'm not positive)

**Comment by RhodriHuwWilliams** [comment]
Sorry, I may have had a breakpoint on authenticate, which would have caused that 2s delay. This is the log without any breakpoints. It took 30 seconds this time;

2022-01-25T18:08:00Z Connected to smtp://smtp.office365.com:587/?starttls=when-available
2022-01-25T18:08:00Z S: 220 LO4P123CA0264.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 25 Jan 2022 18:07:59 +0000
2022-01-25T18:08:00Z C: EHLO [192.168.0.44]
2022-01-25T18:08:00Z S: 250-LO4P123CA0264.outlook.office365.com Hello [82.24.149.111]
2022-01-25T18:08:00Z S: 250-SIZE 157286400
2022-01-25T18:08:00Z S: 250-PIPELINING
2022-01-25T18:08:00Z S: 250-DSN
2022-01-25T18:08:00Z S: 250-ENHANCEDSTATUSCODES
2022-01-25T18:08:00Z S: 250-STARTTLS
2022-01-25T18:08:00Z S: 250-8BITMIME
2022-01-25T18:08:00Z S: 250-BINARYMIME
2022-01-25T18:08:00Z S: 250-CHUNKING
2022-01-25T18:08:00Z S: 250 SMTPUTF8
2022-01-25T18:08:00Z C: STARTTLS
2022-01-25T18:08:00Z S: 220 2.0.0 SMTP server ready
2022-01-25T18:08:00Z C: EHLO [192.168.0.44]
2022-01-25T18:08:00Z S: 250-LO4P123CA0264.outlook.office365.com Hello [82.24.149.111]
2022-01-25T18:08:00Z S: 250-SIZE 157286400
2022-01-25T18:08:00Z S: 250-PIPELINING
2022-01-25T18:08:00Z S: 250-DSN
2022-01-25T18:08:00Z S: 250-ENHANCEDSTATUSCODES
2022-01-25T18:08:00Z S: 250-AUTH LOGIN XOAUTH2
2022-01-25T18:08:00Z S: 250-8BITMIME
2022-01-25T18:08:00Z S: 250-BINARYMIME
2022-01-25T18:08:00Z S: 250-CHUNKING
2022-01-25T18:08:00Z S: 250 SMTPUTF8
2022-01-25T18:08:00Z C: AUTH LOGIN
2022-01-25T18:08:00Z S: 334 VXNlcm5hbWU6
2022-01-25T18:08:00Z C: ********
2022-01-25T18:08:00Z S: 334 UGFzc3dvcmQ6
2022-01-25T18:08:00Z C: ********
2022-01-25T18:08:30Z S: 235 2.7.0 Authentication successful

**Comment by jstedfast** [comment]
Based on the 30s delay, I'm going to guess that this is because the SMTP server has some anti-DDoS/spam/bot algorithms that are rate-limiting your connections.
