### ISSUE TITLE
High memory traffic from MemoryBlockStream

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#725]
I am using MailKit for about an year and I notice memory spikes from time to time. In this particular case I am downloading full messages (header + message parts) from a local mail server (high bandwidth). 
![image](https://user-images.githubusercontent.com/10009149/41546139-86ffc496-7325-11e8-8590-668243002410.png)

The process memory jumps from 300mb to 1gb for about 2-3 sec. I can see with the memory profiler the allocations are byte arrays of size 2048 bytes. They are allocated in  MemoryBlockStream. Those allocations are not memory leaks as you can notice at 51s I forced GC and everything is gone. Still having so much memory traffic is not very good. 

I can see that each MemoryBlockStream holds a private list of byte arrays that are thrown away after the stream is disposed.

What if a shared pool of byte arrays is used instead of allocating them for each stream?

https://github.com/dotnet/corefx/blob/master/src/System.Buffers/src/System/Buffers/ArrayPool.cs

or 

replace entirely MemoryBlockStream with https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream

**Comment by jstedfast** [comment]
Can you try these methods yourself and report back to me on how they perform? I don't have access to tooling to compare (one of the downsides of developing on a Mac).

Thanks!

**Comment by jstedfast** [comment]
I've got a patch to use ArrayPools that I'm about to land. Perhaps you can test it. If it doesn't solve the problem, could you try replacing uses of MemoryBlockStream inside of MimeParser.cs (and in ImapFolder.cs?) and see if that solves the problem?

**Comment by ekalchev** [comment]
The account I am testing with have a series of email with big attachment. I still see memory peaks but this time it is not caused by MemoryBlockStream.

![image](https://user-images.githubusercontent.com/10009149/41581472-3e6c4f06-73a7-11e8-9963-18d0bf4d2fb4.png)

You can see these peaks comes from MemoryStream.set_Capacity. It seems we have very big attachments and the memory stream keep resizing itself.
![image](https://user-images.githubusercontent.com/10009149/41581435-1f836638-73a7-11e8-8692-01632bc45cf1.png)

I think using RecycleableMemoryStream instead of MemoryStream (or MemoryBlockStream?) will solve the set_Capacity issue. However I am not sure how easy is to do that. I remember you have some checks in MailKit/MimeKit

if (stream is MemoryStream) do not dispose. And RecycleableMemoryStream inherit Memory Stream but it must be disposed to return.

You can see on the image ArrayPool did it job, it allocated 180mb of byte arrays but none of them is collected by the GC and it probably was reused later. I asked myself what happens with the array pool buffers after certain amount of time. If the array pool keep the reference to these buffers this will be "memory leak". However I noticed that after some time GC collected those buffers. It seems array pool byte arrays have some "time to live" after which they are released. I'll check the source code to verify that.

**Comment by jstedfast** [comment]
Regarding `MemoryStream.set_Capacity`, that's being invoked when you write a message to a stream. The target stream is a `MemoryStream`. That's not related to parsing the message.

Can you find out where messages are being written to a `MemoryStream` and replace that logic with writing to a `MemoryBlockStream`? That will likely solve a huge chunk of your problem. If you are using `message.ToString()`, don't use that, use `message.WriteTo (customStream);`

As far as using `ArrayPool.Shared`, I agree, using a custom `ArrayPool` was something I was already considering doing but was waiting to hear back how this trial worked out. I was going to go with 100 chunks instead of 200, but meh, 200 is fine too. Any value we use is going to just be guessing anyway.

**Comment by jstedfast** [comment]
Question on ArrayPool: How many buckets does an ArrayPool allocate? Just the 1? Or will it create a number of buckets as it needs them but just not go above a hard-coded threshold?

**Comment by ekalchev** [comment]
I ran the DefaultArrayPool contructor because it is hard to read the bit operations they have

For these values

var maxArrayLength = 2048;
var maxArraysPerBucket = 200;

8 buckets are generated.

Bucket 0 = 16
Bucket 1 = 32
Bucket 2 = 64
Bucket 3 = 128
Bucket 4 = 256
Bucket 5 = 512
Bucket 6 = 1024
Bucket 7 = 2048

**Comment by jstedfast** [comment]
Ah, so that's what they mean by buckets. Ok. It sounds to me, then, like ArrayPool() is not the ideal solution to this problem because all other array sizes will go unused.

I think a better solution will be to use something *like* an ArrayPool, but with a single buffer size.

**Comment by ekalchev** [comment]
Keep in mind those arrays in the buckets are not pre-allocated. When array is requested with Rent, only then the array is created and added in the bucket. MemoryBlockStream will request only byte arrays of 2048 bytes and other buckets will stay empty. No memory will be wasted in other buckets.

**Comment by ekalchev** [comment]
Regarding MemoryStream.set_Capacity

I am using ImapFolder.GetStreams method and then I construct MimeMessage with MimeMessage.Load. Then I am using custom MimeVisitor to get all the message parts as MimeEntity.

Then for every MimeEntity i am calling

mimeEntity.Headers.WriteTo
mimeEntity.WriteTo

to save header and body in my database. MemoryStream.set_Capacity is called from WriteTo methods. Is there more efficient way to do that?

**Comment by jstedfast** [comment]
Well, both of those WriteTo() methods take a Stream argument. It doesn't have to be a MemoryStream. You can use whatever stream type that you want. Seems like you should use something else...

Another option might be to use a MimeKit.IO.MeasuringStream to write it to that first to measure how much buffer space you need, then allocate a MemoryStream with that capacity, then call WriteTo() again on the MemoryStream?

It might be slower since you're writing the headers/mime parts twice, but the penalty for that might be less than the penalty to realloc the MemoryStream's buffer and copying all the data to the new internal buffer.

**Comment by ekalchev** [comment]
Hmm you are right when I saw the call stack I thought that MailKit is doing some internal allocations but the problem is the memory stream I am passing as argument.

MeasuringStream will be really useful for me. I am using SQLite and you can open a stream to SQLite blob column and directly write to the disk. The problem I had is that I didn't know what will be the output size which is required when creating SQLite blob column. This way i'll be able to avoid MemoryStream completely and directly write to the database. Thanks a lot!

**Comment by jstedfast** [comment]
No problem :)
