### ISSUE TITLE
LOGIN failed after upgrading to 2.0.5 (PLAIN)

### ISSUE THREAD

**Issue by StefanBertels** [jstedfast/MailKit#731]
I have working code that checks an IMAP inbox.

After upgrading to 2.0.5 `Authenticate` fails with AuthenticationException "LOGIN failed."

Downgrading to 2.0.4 solved the issue immediately. I did some additional check using alpine (https://www.washington.edu/alpine/) and alpine's log confirm that login via PLAIN still works.
Therefore I don't think it is something server related.

Stacktrace:
`   bei MailKit.Net.Imap.ImapClient.<AuthenticateAsync>d__76.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei MailKit.Net.Imap.ImapClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   bei MailKit.MailService.Authenticate(ICredentials credentials, CancellationToken cancellationToken)
`

Here is my protocol log (some private parts replaced by XXXXXX, let me know if you need details).

``` 
Connected to imap://XXXXXX:143/?starttls=always
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000000 OK CAPABILITY completed.
C: A00000001 STARTTLS
S: A00000001 OK Begin TLS negotiation now.
C: A00000002 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: A00000002 OK CAPABILITY completed.
C: A00000003 AUTHENTICATE PLAIN
S: +
C: XXXXXX
S: A00000003 NO AUTHENTICATE failed.
C: A00000004 LOGIN XXXXXX XXXXXX
S: A00000004 NO LOGIN failed.
```

My code:
```
            var ic = new ImapClient();
            ic.Connect(host: "XXXXXX", options: SecureSocketOptions.StartTls, cancellationToken: ct);
            ic.AuthenticationMechanisms.RemoveWhere(am => !am.Equals("PLAIN"));
            ic.Authenticate(credentials: networkcredentials, cancellationToken: ct);
```

* `networkcredentials` is of type `NetworkCredential`
* `ct` is just an (uncancelled) `CancellationToken`

The working version (2.0.4) only tries PLAIN and gets answer
```
S: A00000003 OK AUTHENTICATE completed.
```

I'm wondering why MailKit tries LOGIN at all -- as you can see I explicitly removed anything but PLAIN (`AuthenticationMechanisms` only has 1 element).

If you need more information, please let me know.

**Comment by jstedfast** [comment]
AuthenticationMechanisms only specifies SASL mechanisms, but the LOGIN *command* is not a SASL mechanism (not to be confused with the LOGIN SASL mechanism which is completely different).

As far as the failure goes...

Does your NetworkCredentials specify a Domain?

If so, that's probably why it is failing now since the PLAIN authentication mechanism now sends the Domain string as well.

**Comment by StefanBertels** [comment]
Thanks for the fast reply. 

Yes, my NetworkCredential has Domain set. After overwriting Domain with string.Empty everything works fine, again.

After re-reading your release notes and checking #721 things are clear now.

BTW: The domain name was not included when using LOGIN. Don't know why Exchange refused to authenticate then (perhaps doesn't like LOGIN here?).

Why are attemps inconsistent: LOGIN _without_ domain and PLAIN _with_ domain?

I agree (#721) that Domain could be used for authzid (even if this does not work for me / with MS Exchange).
Maybe there could be another attempt using PLAIN _without_ domain to be more fault-tolerant?

Anyway, my issue is solved. You might want to close this now. Thank you for your support!

**Comment by jstedfast** [comment]
The IMAP `LOGIN` command does not allow sending a domain, but the PLAIN SASL mechanism does.

The `LOGIN` SASL mechanism also does not allow sending a domain (which is one of the reasons `PLAIN` is universally preferred, I think... well, that and because the `LOGIN` SASL mechanism requires multiple round trips with the server).

That said... I wonder how many other developers will hit this. I didn't consider this possibility because I typically don't set a Domain string.

Did you get your NetworkCredential from some system location or anything? Wondering what your workflow was that you ended up with one so that maybe I can better understand how this happened.

In general, I expect that the use of a Domain string for `PLAIN` auth will be extremely rare, so my concern *now* is that this change might have broken more people than it helped.

**Comment by StefanBertels** [comment]
Don't know how rare authzid is. 

I personally have no real problem at all because I control all thing that happen with this NetworkCredential (create, store, load, apply).


IMHO: I think there are multiple ways to reduce the risk of breaking other people's code:

1. Add a boolean switch UseDomainNameForAuthzid, maybe default to false.
Makes #721 some (non-obvious) option and everyone else will continue like 2.0.4.

You could additionally add a hint to the exception that is thrown when auth fails and PLAIN was tried and Domain was set: "try switching UseDomainNameForAuthzid". 

2. Make it fault-tolerant, i.e. attempt PLAIN with _and_ without domain -- at least you try LOGIN without domain so you aren't strict anyway...
Could perhaps make everybody happy (silently).

3. Add an optional boolean switch UseDomainNameForAuthzid and default to None/null. If NetworkCredentials have non-empty Domain part AND switch is None/null then throw Error ("you have to set UseDomainNameForAuthzid to true/false").
Drawback: we get an Exception even more often. But would force users to be explicit about their choice. 

4. Make behaviour (or default of the switch) dependent on mail server -- if this is a very specific thing. I don't like this one, but might make people happier (than 2.0.4) without making two PLAIN attempts. Is there anything in server response (CAPABILITY?) that could help here?


I personally would vote for 1 or 2.

**Comment by jstedfast** [comment]
1. I'm not sure this idea can be done unless the developer instantiates their own SaslMechanismPlain object, but that's not how you hit this issue (nor how most devs will hit it) since they typically just let MailKit figure out which auth mechanism to use...
2. kinda awkward to implement but possible - I'll wait to see how common this problem comes up first tho
3. Same problem as 1.
4. I agree, I don't like doing server-specific hacks

**Comment by StefanBertels** [comment]
BTW: I just tried to test NTLM because our exchange server has support for this, but 

`AuthenticationMechanisms.RemoveWhere(am => !am.Equals("NTLM"))`

did not work. MailKit (2.0.5) used LOGIN command only and succeeded (because domain isn't included anyway).

**Comment by StefanBertels** [comment]
Ok, I found it:

Just
`ic.Authenticate(mechanism: new SaslMechanismNtlm(networkcredential), cancellationToken: ct);`

did it (using NTLM) -- and auth work both with _and_ without domain name.
