### ISSUE TITLE
Mail sent via Mailkit using SMTP not showing up based on threading in Outlook 

### ISSUE THREAD

**Issue by suhail123805** [jstedfast/MailKit#748]
I was trying to send mail using Mailkit in Xamarin.Forms, Mail sent via Mailkit using SMTP not visible in Outlook sent folder. I want to see in Outlook sent mail in sent folder

**Comment by suhail123805** [comment]
I was trying to send mail using Mailkit in Xamarin.Forms, Mail sent via Mailkit using SMTP not visible in Outlook sent folder. I want to see in Outlook sent mail in sent folder

**Comment by jstedfast** [comment]
To get the sent message in the Sent folder, you'll need to use IMAP to Append() the message to that folder. The SmtpClient cannot put the message there because the SMTP protocol does not have a way of doing that.

As far as threading of replies, make sure you follow the instructions that I laid out here: https://github.com/jstedfast/MailKit/blob/master/FAQ.md#Reply

**Comment by jstedfast** [comment]
If that doesn't work for Outlook, I don't know what to suggest. This is the strategy I've been using for creating replies for 2 decades and it has consistently worked across clients.

What I wrote in the FAQ I linked to above is the world-wide standard way of constructing replies that every mail client uses.

**Comment by swapnil591** [comment]
Threading not working with outlook
Refered https://github.com/jstedfast/MailKit/blob/master/FAQ.md#Reply still not working 
@jstedfast can i please know 
you had tested threading with  outlook

Thank you
