### ISSUE TITLE
using ImapClient Idle command's doneToken causes disconnect

### ISSUE THREAD

**Issue by dolly22** [jstedfast/MailKit#75]
When canceling doneToken used in ImapClient.Idle() method, client state goes to disconnected and new connection is created on next command. 

This seems to be caused by ImapStream ReadAhead() method when OperationCanceledException is thrown inside it's try block.

**Comment by DannyWave** [comment]
I was searching for this, since I get the same behaviour. Unfortunately with the current version 1.2.4

After calling the Cancel Method for the DoneToken I get an exception saying the Client was disconnected. Would be glad to know how to manually set the Connection Flag to true.

Thank you for your great project!
