### ISSUE TITLE
where is "BouncyCastle.csproj"?

### ISSUE THREAD

**Issue by eliot3** [jstedfast/MailKit#79]
Hello,
When compiling "MailKit.net40.sln" (example) there is an unknow reference error : 
"..\bc-csharp\crypto\BouncyCastle.csproj"

I don't found it in severals downloaded "bc-csharp" packages...

Please, explain me where is my mistake.

Regards.

**Comment by b9chris** [comment]
If anyone else runs into this setting up MailKit, here's a little script/trick I use for things like this:

1) Create a script in a dir that's easy to reference like ~/sh - I put the script at:

~/sh/gitsetup.sh

#!/bin/bash
# Uses git's built-in submodule fetching command to initialize any submodules you didn't explicitly pull
# (for example, by pulling a repo that has submodules with TortoiseGit's defaults), then preps all the submodules
# for TortoiseGit usage by adding TortoiseGit's custom config setting that points to your Putty key.

# git built-in
echo "Setting up submodules"
git submodule update --init

echo "Setting up submodules for TortoiseGit/Putty"
# 1) Find the
#         puttykeyfile = C:\\Users...\\.ssh\\PuTTY.ppk
#
# in .git/config

# pass to sed to double-escape all backslashes (Windows problem) - that way it doesn't become an issue when we use it in sed
puttyline="$(grep puttykeyfile .git/config | sed 's/\\/\\\\/g')"

# 2) Search for .git/modules/*/config

files=$(find .git/modules -type f -name config)

# 3) Find [remote "origin"]
# 4) Insert line (entire puttykeyfile line we picked up earlier)

echo 'Inserting missing TortoiseGit .ppk into submodules:'

for file in $files
do
        # -q says don't print the grep results, just return 0 or 1
        if grep -q putty $file
        then
                # I have no idea how to just say if not grep, so screw it here's an empty then
                /dev/null
        else
                echo $file
                # -i means overwrite the file rather than printing the result to stdout
                sed -i "s/\(\[remote .origin.\]\)/\1\n$puttyline/" $file
        fi
done

All you need is the first part if you're not using Windows' TortoiseGit, most of the script afterwards is for TortoiseGit users using the default setup (that uses Putty, not OpenSSH).

Then open a Git Bash on MailKit and run:
~/sh/gitsetup.sh

It will get each of your submodules - in this case just MimeKit - but you need to do it again:

cd submodules/MimeKit
~/sh/gitsetup.sh

Now you'll see BouncyCastle and Portable...Text load in.

If you want you can take a final step of fixing the detached heads this will leave (since they'll each point to the exact version the parent repos are pointing at, not HEAD on master) by cd'ing to each submodule's folder and running:

git checkout master

Or you can leave them be, which is advisable if you don't plan on editing these submodules in any way.

**Comment by jstedfast** [comment]
FWIW, you might be able to just get away with using `git submodule update --init --recursive` in a Git Bash shell.

In TortoiseGit on Windows, what I usually do is just `Pull` inside the MailKit directory and click on the `Update Submodules` button a little to the right of the `Pull` button. Then navigate to  `submodules/MimeKit` in Explorer and then right-click on the MimeKit and do the same procedure.

Maybe a feature request to TortoiseGit is in order, where they could change the `Update Submodules` button to recursively update them.

I typically use the command-line, so don't notice these annoyances that often.

**Comment by b9chris** [comment]
Yeah, but TortoiseGit with Putty introduces a second gotcha, at least if
you use both it and command line (like I do): There is a special Putty line
Tortoise needs in .gitconfig to load your putty key, and there's of course
the standard ssh key. Most of that script is ensuring both are present so
you can use TortoiseGit without getting tripped up when switching between
them.

I think most people reading here won't be developing on these underlying
submodules so it isn't essential but hey the script does all the dirty work
for you and it's one less distraction out of the way if you ever do.
