### ISSUE TITLE
Header is null in Fetch results

### ISSUE THREAD

**Issue by siberianguy** [jstedfast/MailKit#790]
I'm observing a confusing behaviour working with Gmail. Here's the steps:
1. I mark a chain of 7 emails as unread and execute  `var uniqueIds = _inbox.Search(SearchQuery.NotSeen);`
2. In response I get just 5 uniqueIds which is concerning
3. Then I Fetch those uniqueIds and get 5 elements. Seems wrong but at least is consistent with the amount of uniqueIds returned by Search
3. Then I mark all those uniqueIds as seen: `_inbox.AddFlags(uniqueIds, MessageFlags.Seen, true);`
4. In Gmail I see the whole chains is now marked as read which is confusing as uniqueIds returned only 5 elements. Anyway, this part works like expected
5. Then the code gets to #1 again. I put a breakpoint and mark the same 7 messages as unread. Search returns 5 uniqueIds again
6. But when I get to Fetch, 7 results are returned. This time the amount of elements is right though it's confusing there were 5 elements during the first iteration and I don't know why there're 5 elements returned by Search in both cases. But the real problem happens why I try to iterate over the 7 Fetched results: the last 2 elements got null instead of a Header.

I'm attaching imap.log and here's the code:

```
            var subjects = new List<string>();
            
            var uniqueIds = _inbox.Search(SearchQuery.NotSeen);
            
            Log.Logger.Verbose("Received {count} emails", uniqueIds.Count);
            
            if (uniqueIds.Count == 0)
            {
                return subjects;
            }

            var headers = new HashSet<HeaderId>(new[] {HeaderId.Subject});
            
            var items = _inbox.Fetch(uniqueIds, MessageSummaryItems.UniqueId, headers);
            
            if (!firstRun) //on the first run we just mark all the signals we've missed as read
            {
                foreach (var item in items)
                {
                    if (_alreadReadUniqueIds.Contains(item.UniqueId)) continue;
    
                    //Exception happens here because 
                    var subject = item.Headers[HeaderId.Subject];
                    
                    subjects.Add(subject);
                }
            }

            foreach (var uniqueId in uniqueIds)
            {
                if (!_alreadReadUniqueIds.Contains(uniqueId)) 
                    _alreadReadUniqueIds.Add(uniqueId);
            }

            _inbox.AddFlags(uniqueIds, MessageFlags.Seen, true);
            
            return subjects;
```

[imap.log](https://github.com/jstedfast/MailKit/files/2691971/imap.log)

**Comment by siberianguy** [comment]
I'm now looking through imap.log and I've noticed there's no Unseen among allowed Flags:

```
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
```

Could it be because I'm working with a folder where messages are automatically archived from inbox?

**Comment by jstedfast** [comment]
Unseen messages just don't have the `\Seen` flag, so that's not the issue.

What is happening is that in your last `Fetch()`, GMail's IMAP server decided to notify you that another client has modified the flags on 2 other messages (UIDs 81 and 84).

That's why their `IMessageSummary.Headers` are `null`, because they are not actually a response to your query, they are just unsolicited `FETCH` responses from the IMAP server.

That's something that IMAP can (and does) do, so you have to be prepared to handle those cases by making sure that the values you requested are non-null.

Typically, when these unsolicited FETCH responses are returned by an IMAP server, they will not include more than the UID, FLAGS and MODSEQ values (but they *could* contain anything that the server decided to give you, just in my experience, I've never seen anything other than those 3 values).

> Could it be because I'm working with a folder where messages are automatically archived from inbox?

Very likely, yes.

**Comment by jstedfast** [comment]
I gotta run out for a few hours, but if you have more questions on this topic, feel free to ask away here (or via email) and I will do my best to answer them.

**Comment by siberianguy** [comment]
Thanks for your response! It makes more sense now but I still feel like there's something wrong.

> What is happening is that in your last Fetch(), GMail's IMAP server decided to notify you that another client has modified the flags on 2 other messages (UIDs 81 and 84).

The thing is there's no other client. What happened (I guess) was that all 7 messages were marked as Seen after the first iteration (that's why I see the whole chain market as read at gmail.com) but somehow I've seen 5 elements returned

**Comment by jstedfast** [comment]
> I still feel like there's something wrong.

I don't think anything is wrong based on the log that you posted.

> The thing is there's no other client.

Not even a web client that might have viewed a message or 2? Could it be a server-side filter?

FWIW, from rfc3501:

```
   Server implementations that offer multiple simultaneous access to the same
   mailbox SHOULD also send appropriate unilateral untagged FETCH and
   EXPUNGE responses if another agent changes the state of any message
   flags or expunges any messages.
```

The IMAP server won't give you flag change notifications for a change made in a previous session and there was never a case where your client session in that log marked 7 messages as Seen or Unseen, so I can say with certainty that that is not the issue.

Normally MailKit will emit the `MessageFlagsChanged` event and the `ModSeqChanged` event for the  cases like (e.g. if these were in a response to a `NOOP` command):

```
S: * 80 FETCH (UID 81 MODSEQ (8126) FLAGS (\Seen))
S: * 83 FETCH (UID 84 MODSEQ (8126) FLAGS (\Seen))
```

But in your particular case, since you issued a `FETCH` request, it is impossible for MailKit to know if these untagged `FETCH` responses belong to the request or are unsolicited, so it just adds them to the list of FETCHed items.

Does that help clarify anything?
