### ISSUE TITLE
Best practice to use QRESYNC and CONDSTORE

### ISSUE THREAD

**Issue by michelevirgilio** [jstedfast/MailKit#805]
Hi,
i'm trying to implement an IMAP client using your awesome library.
Can you please show some pseudo code (steps) on how to use the 2 extensions `QRESYNC `and `CONDSTORE `for a full fetch / refetch? 
I've read about the `MessageFlagsChanged` event and the `MessageExpunged` event, but i cannot have the client connected in background.
Thanks, and keep on with this awesome work.

**Comment by jstedfast** [comment]
You really need to read the specs. I would need to write a book to explain how to use these features. Once you've read the specs, I'll be happy to answer any questions you have.

```csharp
var uidValidity = cache.GetUidValidity ();
var known = cache.GetKnownUids ();
UniqueIdSet missing;

folder.MessageFlagsChanged += OnMessageFlagsChanged;

if (client.Capabilities.HasFlag (ImapCapabilities.QuickResync)) {
    var highestModSeq = cache.GetHighestKnownModSeq ();

    folder.MessagesVanished += OnMessagesVanished;

    // This version of the Open() method will emit MessagesVanished and MessageFlagsChanged
    // for all messages that have been expunged or have changed since the last session.
    folder.Open (FolderAccess.ReadWrite, uidValidity, highestModSeq, known);
} else {
    folder.MessageExpunged += OnMessageExpunged;
    folder.Open (ImapFolder.ReadWrite);

    if (folder.UidValidity != uidValidity) {
        // our cache is no longer valid, we'll need to start over from scratch
        cache.Clear ();

        missing = folder.Search (SearchQuery.All);
    } else {
        var all = folder.Search (SearchQuery.All);

        // purge messages from our cache that have been purged on the remote IMAP server
        foreach (var uid in known) {
            if (!all.Contains (uid))
                cache.Remove (uid);
        }

        // sync flag changes since our last session
        known = cache.GetKnownUids ();
        if (known.Count > 0) {
            IList<IMessageSummary> changed;
            if (client.Capabilities.HasFlag (ImapCapabilities.CondStore)) {
                changed = folder.Fetch (known, highestModSeq, MessageSummaryItems.Flags | MessageSummaryItems.ModSeq  MessageSummaryItems.UniqueId);
            } else {
                changed = folder.Fetch (known, MessageSummaryItems.Flags | MessageSummaryItems.UniqueId);
            }

            foreach (var item in changed) {
                // update the cache for this message
                cache.Update (item);
            }
        }

        // figure out which messages we are missing in our cache
        missing = new UniqueIdSet (SortOrder.Ascending);
        foreach (var uid in all) {
            if (!known.Contains (uid))
                missing.Add (uid);
        }
    }
}

// fetch the summary information for the messages we are missing
var newMessages = folder.Fetch (missing, MessageSummaryItems.Full | MessageSummaryItems.UniqueId);
foreach (var message in newMessages)
    cache.Add (message);
```

And then you'd have these event handlers:

```csharp
void OnMessageFlagsChanged (object sender, MessageFlagsChangedEventArgs e)
{
    cache.Update (e.Index, e.Flags, e.ModSeq);
}

void OnMessageExpunged (object sender, MessageExpungedEventArgs e)
{
    cache.Remove (e.Index);
}

void OnMessagesVanished (object sender, MessagesVanishedEventArgs e)
{
    cache.RemoveRange (e.UniqueIds);
}
```

**Comment by michelevirgilio** [comment]
Thanks, the code is working well!  
Just to know, why you're checking for uidvalidity only in the CONDSTORE case?
`if (folder.UidValidity != uidValidity) {`

**Comment by jstedfast** [comment]
The QRESYNC code-path should also be checking the uidValidity. I've just updated the code snippet.

**Comment by tinmac** [comment]
@jstedfast looking at your code [above](https://github.com/jstedfast/MailKit/issues/805#issuecomment-455674160) what type is `cache`? If its a class can you post it so we can analyse
Thank you

**Comment by jstedfast** [comment]
@tinmac it's a class that doesn't exist. You would have to implement it because it would depend on where you want to cache the information (database, file system, memory, etc).

**Comment by tinmac** [comment]
> @tinmac it's a class that doesn't exist. You would have to implement it because it would depend on where you want to cache the information (database, file system, memory, etc).

Ok I see thanks. 

As we fetch `UidValidity` with `var uidValidity = cache.GetUidValidity()` should we not also be persisting it to the cache if it changes?

**Comment by jstedfast** [comment]
@tinmac 

> As we fetch UidValidity with var uidValidity = cache.GetUidValidity() should we not also be persisting it to the cache if it changes?

Yes.

I found this in my public gists that you could use as a starting point. No idea if it compiles or works, so be warned.

https://gist.github.com/jstedfast/2ba9542bb4b045b5e1e6c4f3f5655620

The main logic to look at is `OpenAndResyncAsync()`

I would caution that the call to folder.OpenAsync() in that code that takes a list of UIDs might not work correctly because it passes an empty `UniqueIdSet` (as seen 1 line above it).

But it might...

What I would probably say is this:

The problem with passing in the non-contiguous list of UIDs that would (likely) get returned by a method like `GetAllUidsAsync()` is that it would cause the `ImapFolder.OpenAsync()` method to generate a massive command to send to the IMAP server.

Instead, what I would try to do is find out your highest known UID and use a `new UniqueIdRange(UniqueId.MinValue, highestKnownUid)` so that the ImapFolder is able to use `1:9999` in the command (assuming 9999 is the highest known UID) as opposed to something like `1:7,9:10,12:5,...,9991:9993,9995,9997:9999` where `...` could be really long.

Hopefully you understand what I'm getting at.

I'd have to re-read the QRESYNC IMAP extension specification to know if an empty `uid-set` would work the way you'd want it to (which, for me at least, would mean that I want VANISHED events for every message that has been purged since the CHANGEDSINCE value).

What *might* be the case in the specification, is that it's possible that the IMAP server will only send VANISHED events for UIDs that are within the `uid-set` that you pass to the OPEN command. If that's the case, then an empty set is not going to produce the results you want.

**Comment by jstedfast** [comment]
I should mention the (hopefully) obvious caveat that my above comment assumes you're going to be trying to cache the entire list of messages that exist on the IMAP server or at least be syncing them in chronological/sequential order.

If you are implementing an IMAP mail client app for a mobile device, for example, you might be trying to cache messages only as the user scrolls through their message-list which might be sorted in some order other than sequential or it might be threaded by conversation (like most mobile IMAP clients I've used).

If that's the case and you are incrementally syncing only the messages that you've displayed in the message-list, that's going to take some ingenuity and modifications to the logic in that MessageCache.cs file I linked to.

**Comment by tinmac** [comment]
Very helpful thank you. The points you make are clear. 

Our app is WinUI3, its email client is aimed squarely at gmail (no other providers only gmail). 

Virtualising the message summaries ObservableCollection was on the cards so I also take note of your last point. 

As Gmail does not support `QRESYNC` im thinking the resync strategy in a Gmail only implementation like ours would be to exclusively use `UidValidity` coupled with `CONDSTORE` for any flag updates. But I see   `DeliveredAfter` is available too and cant help but ask can it be used to provide sync and would it be as effective as `UidValidity` or even bring any advantages? 

Im trying to figure out the path we should take

**Comment by jstedfast** [comment]
Well, UIDVALIDITY is needed to verify that the messages you have cached are still valid.

In rare conditions, a server will change that value (e.g. when a user deletes a folder and recreates it). You need to check that value no matter what because if it changes you need to throw away your entire cache.

**Comment by jstedfast** [comment]
FWIW, if you are building a client exclusively for GMail, I would recommend considering using Google's APIs instead of IMAP because it will probably give you better performance and flexibility.

If you stick with IMAP, I'm not sure if using the DeliveredAfter search is helpful because any UID higher than the last known highest UID is automatically "delivered after" your last session ended.

No matter what you do, you will need to always have the full list of UIDs (even if you don't have summary info for most of those messages) because you need to be able to handle index-based EXPUNGE notifications and that list of UIDs is the easiest way to have an index-to-UID mapping.

I recommend using folder.Search(SearchQuery.All) to get that list.

**Comment by tinmac** [comment]
Thank you for you guidance, very helpful indeed. The gmail api's look interesting.
