### ISSUE TITLE
ImapClient.FolderCreated, IMailFolder.Subscribed, IMailFolder.Unsubscribed not firing

### ISSUE THREAD

**Issue by pm64** [jstedfast/MailKit#816]
Are the above events currently supported? I added handlers for each one to the ImapIdle demo project and tested on several different IMAP servers, but have been unable to get them to fire. No special considerations are mentioned in the documentation. Perhaps support is currently limited?

**Comment by jstedfast** [comment]
They are fully supported as far as the IMAP protocol allows them to be.

In most cases, those events will only fire when a folder is created, subscribed, or unsubscribed using the same MailKit.

If you watch for those events in a MailKit client and create/subscribe/unsubscribe folders in another client, no matter what implementation those other clients used, you will not get the events because the base IMAP protocol does not support this.

Check out the docs on the IMAP NOTIFY extension to see where these events can be emitted when another client makes those state changes on the server.
