### ISSUE TITLE
Recommendations for large amounts of emails

### ISSUE THREAD

**Issue by achobanov** [jstedfast/MailKit#830]
I want to ask you about you recommendations for sending large amounts of mails - e,g, 100 000. 

[Here](https://github.com/jstedfast/MailKit/issues/626) I read your response that it can send parallel emails (with multiple `SmtpClients` created on different threads). I am thinking of creating a simple wrapper, registered as **Transient** in **IoC** container with a single method:
```
public async Task SendEmail(MimeMessage message)
{
    using (var client = new SmtpClient())
    {
        ...
    }
}
```
Then call it like this:
```
Task.WhenAll(emails.Select(this.mailClient.SendMail)
```

Then I read [this](https://www.infoq.com/news/2017/04/MailKit-MimeKit-Official) article from 2017, stating that _MailKit_ is not trully async, but is "simulating it" with thread blocking and so on. 

Thus I decided to create this issue and ask for your recommendation - what would be a good approach to sending multitude of emails safely? 
 
_Finally - great job on the lib. To be officially recommended by the obsolete SmtpClient 
dotnet documentation page is a feat!_

**Comment by jstedfast** [comment]
That article is no longer true (but it was at the time). MailKit has been updated to be truly async since v2.0 (it was actually the main feature for 2.0).

Now to your question...

Keep in mind that most mail servers will likely have anti-abuse features in place that will limit you in the number of connections it will allow from your machine, so if you have 100,000 messages and attempt to spawn 100,000 SmtpClients to send 1 message each, that's not likely to work very well because most of those will be refused a connection or will cause other connections to get dropped, etc.

I would definitely recommend sending multiple messages over the same SmtpClient connection and limiting yourself to only a few connections (you probably aren't likely to be allowed to make more than a handful, but this is just a *guess* because I've never tried it and each server will be different).

Since it sounds like you are sending bulk mail, is there a reason you really need to send 100,000 *unique* messages instead of just sending the same message to multiple recipients?

There's sometimes a limitation for this as well (I think I've seen a limit of around 25-50 recipients for a single message in use by some SMTP servers in the past), but MailKit provides an API for you to Send() to a list of recipients that don't have to be defined in the To/Cc headers.

Another option is to add a bunch of recipients to the Bcc header and use the normal `Send(MimeMessage)` (or SendAsync) method.

If you decide to send the same message to a batch of recipients, you *may* want to set the To header to `undisclosed-recipients:;`. You can do this using the following code snippet:

```csharp
message.To.Add (new GroupAddress ("undisclosed-recipients"));
```

It's important to set that because some mail software will treat messages without a To header (or with an empty To header) as spam.

The name of the GroupAddress doesn't have to be `undisclosed-recipients`, that is just an example that is pretty common. It could be `Valued Customer` or whatever else you want.

No matter what option you choose, you'll likely need to do some experimentation to find out what limitations your SMTP server might have and constrain your client app to those limitations.

Hope that helps.

**Comment by achobanov** [comment]
Thanks @jstedfast for the extensive response. A couple more things, if you don't mind. 
1. We were indeed planning to send email with **BCC** recipients, but it would have to be batched, because it has varying limit as well. From a glance, a hundred seems OK, 
2. About the `Send(message, sender, recipients)` overload - this is handled internally by `MailKit` and has no limit? It would be perfect, if so, but seems a bit good to be true, However docs don't specify anything about limit, so I decided to ask.

**Comment by jstedfast** [comment]
MailKit itself doesn't have a limit and unfortunately has no way to know what kind of a limit the SMTP server may have.

For what it's worth, the Send() method that takes a list of recipients is essentially the core Send method. The other method that just takes a MimeMessage more-or-less just looks at the headers to figure out who the sender is and who the recipients are and then calls the Send method that takes a list of recipients. In other words, the Send(MimeMessage) method is a convenience wrapper fr the other method. The main advantage to using the Send method that takes a list of recipients is that you don't have to add a Bcc header.
