### ISSUE TITLE
Search sends outdated results

### ISSUE THREAD

**Issue by siberianguy** [jstedfast/MailKit#835]
I'm working with Gmail requesting Search in while every second. According to imap.log I'm not banned for frequent requests, so I expect Search to return updated results but when a new email arrives, I still receive outdated results. If before calling Search I put Check or Open, Search returns updated results though it doesn't seem like a good idea. Is it an expected behaviour?

**Comment by jstedfast** [comment]
That sounds like expected behavior.

Depending on the IMAP server implementation, when you open a folder, the server loads a cache. When a new message arrives, it gets added to the folder by another process (i.e. not the same process that the IMAP client is communicating with) and so the process that is reading the folder on behalf of the client will not immediately know about it until something happens that causes it to re-load the cache.

The CHECK command is a way for the client to request that the server re-load the cache. Re-opening the folder has the same effect.

Typically, the server will eventually catch up and notice the new message anyway, but it may not be immediate.

Does that help?
