### ISSUE TITLE
What are recommended production settings for ServerCertificateValidationCallback?

### ISSUE THREAD

**Issue by MrYossu** [jstedfast/MailKit#843]
Hello,

Just found MailKit, and am converting our old code to use it.

The sample code on the main github page includes the following...

    // For demo-purposes, accept all SSL certificates (in case the server supports STARTTLS)
    client.ServerCertificateValidationCallback = (s,c,h,e) => true;

However, I'm having difficulty working out what I **should** be using here in production code. I found [this documentation page](http://www.mimekit.net/docs/html/P_MailKit_MailService_ServerCertificateValidationCallback.htm), but that just uses the same code but without the warning.

Please can you show me where I'd find some explanation of this, and update the main page to include the link.

Thanks

**Comment by jstedfast** [comment]
If you've ever visited a web page in a browser and gotten a prompt to accept an SSL certificate, basically, that's what you need to do in your app.

Then, what you'll do is save that certificate in a database and when the user goes to that site again in the future, you'd load check your database for that certificate (probably doing a lookup by using the certificate Thumbprint property) to see if the user has already accepted it, and, if so, `return true;`, otherwise prompt the user as to what to do.

**Comment by MrYossu** [comment]
@jstedfast Thanks for the reply, but I still don't understand how or when I would need to use this callback.

If I'm connecting to a trusted mail server, such as AmazonSES, do I need to worry about this, or just assume that the certificate is valid?

Thanks again.

**Comment by jstedfast** [comment]
A few things:

If the server has a valid certificate and the Root Certificate Authority that signed said certificate is trusted by your system (all of the big-name Root CA's are trusted by default on Mac and Windows, so those aren't likely to be a big issue), then you will be fine... but if the Root CA isn't trusted by your system or it is unknown to your system, then you'll get an `SslHandshakeException`.

Some servers use a self-signed SSL certificate which means that there is no Root CA that your system already trusts and so you will need to handle that if your app might connect to such a server.

My guess is that AmazonSES is fine and you won't need to set a callback handler.

**Comment by MrYossu** [comment]
OK, thanks
