### ISSUE TITLE
Empty Sender in Envelope object

### ISSUE THREAD

**Issue by SuhovDE** [jstedfast/MailKit#846]
Hi, we have encountered an issue with the reading sender from an envelope in the case when the sender doesn't have a hostname. Sender and From properties are NULL in this case.
Here is an exapmle:
```
C: B00000092 UID FETCH 16855:16880 ENVELOPE
S: * 1 FETCH (ENVELOPE ("Sat, 6 Apr 2019 06:11:46 +0000" "SUBJECT" (("NAME" NIL NIL ".MISSING-HOST-NAME.")) ((NIL NIL "NAME" ".MISSING-HOST-NAME.")) NIL ((NIL NIL "TEST" "TEST.COM")) NIL NIL NIL "<D5EE6C329218A78D@>") UID 16855)
```
Sender and From headers in such emails have the following values

```
Sender: <NAME>
From: NAME
```

**Comment by jstedfast** [comment]
What version are you using? The latest version of MailKit does not set `Envelope.From` or `Envelope.Sender` to `null`.

Instead, the latest version provides the following results which I would argue is correct:

1. `Envelope.Sender` is an `InternetAddressList` with a count of 1, where the 1 address is a `MailboxAddress` with an `Address` value of "NAME" and the `Name` property is `null` because there is no name.
2. `Envelope.From` is an empty list because all MailboxAddresses *MUST* have a valid `Address` property, so there's no way to represent that.

**Comment by SuhovDE** [comment]
Confirmed. Cannot replicate with version 2.1.4.0.
The issue was in version 2.1.2.0. 
Thank you

**Comment by jstedfast** [comment]
Awesome, glad things are working for you now.
