### ISSUE TITLE
Unlimited waiting and other questions

### ISSUE THREAD

**Issue by Miraichi** [jstedfast/MailKit#853]
**1) Unlimited waiting in System.Net.Socket.Socket.Receive**
Tested my application on 80 threads and all threads in one moment stopped working and waiting response from IMAP server. Timeout not helping on that. Need protocol log or its my problem in code?

![alt text](https://image.prntscr.com/image/MI47vZCPTZGf7uCuV3O8Cw.png)

```c#
if (imapClient.IsAuthenticated)
         return imapClient.IsAuthenticated;

//Stopped on imapClient.Connect
if (!imapClient.IsConnected)
         imapClient.Connect(imapServer.Hostname, imapServer.Port, imapServer.SocketType == "SSL", cancel.Token);

if (imapClient.IsConnected)
         imapClient.Authenticate(Login, Password, cancel.Token);

return imapClient.IsAuthenticated;
```

**2) POP3Client.GetMessages is ArgumentOutOfRangeException**
Where i may read how to use GetMessages?
In my attempt is throwing Exception
```c#
var Messages = pop3Client.GetMessages(0, pop3Client.Count, cancel.Token);
```

**3) How to correctly use threads on IMAP/POP3 clients?**
On 80 threads in my attempt cpu is usage by 70-99 percent.
One thread -> One email -> One server:port -> One IMAP/POP3 client of MailKit.
Is there any other method to multithreading my application?

**Comment by jstedfast** [comment]
1) Probably just your connection to the mail server is slow. You can use a cancellation token and timeouts also work in most cases.

2) It's probably throwing an exception because your POP3 mailbox has no messages. Just do this:

if (pop3Client.Count > 0)
    messages = pop3Client.GetMessages (0, pop3Client.Count, cancel.Token);

I would, however, suggest you not use GetMessages() to get *all* of the messages at a time and instead do something smarter like batching a few messages at a time. A POP3 mailbox can be gigabytes of data that you'll end up downloading into memory and that is not good.

Better to download messages 1 at a time. GetMessages() is really only there to facilitate the PIPELINING extension.

3) Try using async instead of threads. Or even if you want to continue using threads, still use async versions of the methods because that will reduce polling sockets for I/O.
