### ISSUE TITLE
POP3/IMAP -> Pop3ProtocolException/ImapProtocolException

### ISSUE THREAD

**Issue by Miraichi** [jstedfast/MailKit#856]
**..has unexpectedly disconnected. But server say login or password is invalid.**
Get Exception when authenticating into IMAP/POP3 servers. Servers say my login and password is invalid in protocol log and is okay, but MailKit send Exception.

**POP3 Protocol Log**
```
[Test] Connecting..
Connected to pop://pop.free.fr:110/?starttls=when-available
S: +OK POP3 ready <1724282838.1557400756@popn2>
C: CAPA
S: +OK Capability list follows
S: TOP
S: USER
S: UIDL
S: SASL EMAIL PLAIN
S: .
[Test] Connected: True
[Test] Authenticating..
C: APOP EMAIL PASSWORD
S: -ERR Invalid login or password
C: AUTH PLAIN
Exception: The POP3 server has unexpectedly disconnected.
```

**IMAP Protocol Log**
```
[Test] Connecting..
Connected to imap://imap.free.fr:143/?starttls=when-available
S: * OK IMAP4 ready
C: A00000000 CAPABILITY
S: * CAPABILITY IMAP4REV1 X-NETSCAPE LOGIN-REFERRALS AUTH=PLAIN
S: A00000000 OK completed
[Test] Connected: True
[Test] Authenticating..
C: A00000001 AUTHENTICATE PLAIN
S: +
C: AHBoaWxpZmxvLmxlZ3JhZXRAZnJlZS5mcgB2b2x2aWM=
S: A00000001 NO Invalid login or password
C: A00000002 LOGIN EMAIL PASSWORD
Exception: The IMAP server has unexpectedly disconnected.
```

**Comment by jstedfast** [comment]
You got the Pop3ProtocolException/ImapProtocolException because your POP3/IMAP server disconnected when you gave it invalid credentials.

This is the expected behavior based on what your server is doing.

*Most* POP3/IMAP servers will not close the connection just because you've sent invalid credentials, most of the time they will allow multiple attempts to authenticate, but yours apparently does not.
