### ISSUE TITLE
MailKit dont understand response of server.

### ISSUE THREAD

**Issue by Miraichi** [jstedfast/MailKit#860]
MailKit dont understand server response and continue send commands. I know about enable IMAP access in settings account, but its not thrown Exception AuthenticationException about this.

```
[Test] Connecting..
Connected to imaps://poczta.interia.pl:993/
S: * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN ID XLIST NAMESPACE IDLE AUTH=PLAIN] IMAP4 ready.
[Test] Connected: True
C: A00000000 ID ("command" "ID" "name" "com.tencent.foxmail" "version" "7.2.9.79" "os" "windows" "os-version" "6.1" "vendor" "tencent limited")
S: * ID NIL
S: A00000000 OK ID completed.
[Test] Authenticating..
C: A00000001 LOGIN xxx@interia.pl yyy
S: A00000001 OK [ALERT] Please enable IMAP access in your account settings first.
C: A00000002 CAPABILITY
S: A00000002 NO [ALERT] Please enable IMAP access in your account settings first.
C: A00000003 NAMESPACE
S: A00000003 NO [ALERT] Please enable IMAP access in your account settings first.
C: A00000004 LIST "" "INBOX"
S: * BAD [ALERT] Please enable IMAP access in your account settings first.
```
..and stop working.

**Comment by jstedfast** [comment]
The problem is that MailKit is still waiting for the tagged response to the LIST command.

You *should* be getting a response like this:

    A00000004 NO [ALERT] Please enable IMAP access in your account settings first.

... but you aren't. That's a bug in the server. I don't think I can work around this particular server bug because I don't think that I can make MailKit just assume that an untagged BAD response (aka `* BAD ...`) can be treated the same as an untagged BYE response (`* BYE ...`) universally.

That said, there's an `Alert` event on ImapClient that you could listen to for this particular issue.
