### ISSUE TITLE
NullReferenceException in ImapClient.Disconnect

### ISSUE THREAD

**Issue by ekalchev** [jstedfast/MailKit#862]
Occurred in master, commit SHA 26818269484b24ed3f629ce55d37f8f42528a67a

Engine.Stream was null. We have this code

```csharp
try {
    imapClient.Connect();
} catch(Exception) {
} finally {
    if (this.IsConnected == true) {
        this.Disconnect(true);
    }
}
```

I suspect Connect failed and Disconnect was called on not connected imapClient and somehow IsConnected was true. 

We observed this problem when we had a bug in our software where incorrect security method was used. Our mail server support only SSL on connect but we used incorrectly StartTLS. I suspect mailkit was connected and tried to call STARTTLS on the connected connection but that failed and left the Engine object in invalid state where Stream was null and IsConnected was true.

![image](https://user-images.githubusercontent.com/10009149/58465008-76f1ed80-813f-11e9-8138-0816ddf68471.png)

**Comment by jstedfast** [comment]
This seems like another case of issue #851

ImapClient.IsConnected is a simple property that returns ImapEngine.IsConnected which, in turn, returns true only if the Stream is non-null and ImapStream.IsConnected also returns true.

As with the case of issue #851, I suspect that the issue is that the server is sending `* BYE`?

Do you happen to have logs? Is that the case?

If you don't have logs, can you replicate the error?

**Comment by ekalchev** [comment]
I don't have logs and it is not reproducible.

**Comment by Miraichi** [comment]
You have name of server maybe?

**Comment by ekalchev** [comment]
> You have name of server maybe?

It is private server - Dovecot.

**Comment by jstedfast** [comment]
I don't think that the scenario that you suspect happened could happen. If your mail server only supports SSL-on-connect, then these are the possible scenarios:

1. You used `Connect (host, port, true)` or you used `Connect (host, port, SecureSocketOptions.SslOnConnect)`. If this is the case, MailKit would not attempt STARTTLS.
2. You used `Connect (host, port, false)` or a non-SslOnConnect SecureSocketOption value in which case MailKit would probably hang because the server, being wrapped in SSL, would be expecting the client to initiate an SSL-handshake while MailKit, expecting the server to send a greeting, would wait for the server to send it a greeting. In other words, both client & server would wait endlessly for the other to send it something.

**Comment by jstedfast** [comment]
The only scenario that I can see happening here is that somehow the `ImapEngine`'s `Stream` property got set to null between the call to `ImapClient.DIsconnect(true)` and the `LOGOUT\r\n` command being run on the `ImapEngine`.

Unless I'm missing something (completely possible), I think that another thread must have been accessing the `ImapClient` and called `Disconnect()` on it or something.

**Comment by ekalchev** [comment]
We have dedicated thread that works with ImapClient. I am sure this was not the case.

**Comment by jstedfast** [comment]
I'm completely out of ideas :-\

**Comment by ekalchev** [comment]
We've got try catch around Disconnect and this is not an big issue for now. I'll let you know if happen again.

**Comment by jstedfast** [comment]
Okay, thanks. If you could confirm that it was a `Connect(...)` that got an exception followed by `Disconnect(true)`, that would be super helpful (or even discover that it was some other sequence of events that led to this).

**Comment by jstedfast** [comment]
I'm just not seeing how this is even hypothetically possible...

Here's the ImapClient Disconnect logic:

```csharp
CheckDisposed ();

if (!engine.IsConnected)
	return;

if (quit) {
	try {
		var ic = engine.QueueCommand (cancellationToken, null, "LOGOUT\r\n");
		await engine.RunAsync (ic, doAsync).ConfigureAwait (false);
	} catch (OperationCanceledException) {
	} catch (ImapProtocolException) {
	} catch (ImapCommandException) {
	} catch (IOException) {
	}
}
```

The `if (!engine.IsConnected)` check expands to `if (engine.Stream == null || !engine.Stream.IsConnected)`

This tells me that `engine.Stream` is not `null` *and* it is still considered to be connected at this stage.

BUT... by the time `await engine.RunAsync (ic, doAsync).ConfigureAwait (false);` is called, `engine.Stream` is null. How could that possibly happen unless another thread disconnected the client? It can't.

**Comment by ekalchev** [comment]
> Okay, thanks. If you could confirm that it was a `Connect(...)` that got an exception followed by `Disconnect(true)`, that would be super helpful (or even discover that it was some other sequence of events that led to this).

I can confirm it was Disconnect(true). It occurred when our application went offline and this is the only overload of Disconnect we use. 

Probably after Connect there was sequence of Imap commands. It wasn't just Connect followed by Disconnect.

**Comment by jstedfast** [comment]
I think I recently made improvements to cancellation that would affect cancelling the Connect[Async] methods.

Is this still an issue in the latest code?

**Comment by ekalchev** [comment]
We had this issue an year ago. I'll test it with latest code

**Comment by ekalchev** [comment]
Cancellation of connect method is not an issue anymore with the latest code

**Comment by jstedfast** [comment]
Awesome :-)
