### ISSUE TITLE
SmtpClient.DataAsync Adds Extra CRLF

### ISSUE THREAD

**Issue by nitinag** [jstedfast/MailKit#895]
SmtpClient currently adds an extra CRLF when sending messages to email servers.

Because of this bug, the delivered message contains an extra CRLF compared to the actual message when you do MimeMessage.WriteToAsync.

As per the RFC:
> The mail data are terminated by a line containing only a period, that
is, the character sequence "\<CRLF>.\<CRLF>", where the first \<CRLF> is
actually the terminator of the previous line (see Section 4.5.2).
This is the end of mail data indication.  **The first \<CRLF> of this
terminating sequence is also the \<CRLF> that ends the final line of
the data (message text) or, if there was no mail data, ends the DATA
command itself** (the "no mail data" case does not conform to this
specification since it would require that neither the trace header
fields required by this specification nor the message header section
required by RFC 5322 [4] be transmitted).
https://tools.ietf.org/html/rfc5321#section-4.1.1.4

The EndData parameter in SmtpClient.cs (https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L77) is currently:
```c#
static readonly byte[] EndData = Encoding.ASCII.GetBytes ("\r\n.\r\n");
```
It should be:
```c#
static readonly byte[] EndData = Encoding.ASCII.GetBytes (".\r\n");
```
The first CLRF should be from the end of the message itself.

**Comment by jstedfast** [comment]
This was a solution to fix messages that do not end with a new-line.

**Comment by nitinag** [comment]
Doesn't `FormatOptions.EnsureNewLine` already exist for that purpose?

**Comment by nitinag** [comment]
FYI, You always currently force `FormatOptions.EnsureNewLine` to `true` regardless of the user value of that setting at https://github.com/jstedfast/MailKit/blob/master/MailKit/Net/Smtp/SmtpClient.cs#L2055.

**Comment by jstedfast** [comment]
Yea, the EnsureNewLine thing on FormatOptions was added later and I didn't update the SmtpClient logic. Not sure if I just forgot or if I just wasn't 100% confident at the time that there weren't any corner cases where it didn't work.

Pretty sure it's a solved problem when you write to a Dos2UnixFilter or a Unix2DosFilter because the Flush() logic tracks what the last character written was. and makes sure to write a new-line sequence when flushed if it hasn't already ended with one.

I can *probably* remove it from SmtpClient, but I need time to verify that it won't break anything.

**Comment by jstedfast** [comment]
Changing EndData to ".\r\n" seems to work based on the unit tests I've got currently but I'm not 100% confident that there are no corner cases where MimeMessage.WriteTo() will not end with a newline sequence (even when FormatOptions.EnsureNewLine is enabled).

**Comment by jstedfast** [comment]
Now that SmtpClient.Send*() will always use the BDAT command if the CHUNKING extension is supported, I've updated the Send*() code to not force-enable EnsureNewLine in that case.

In other words, this is now a non-issue when the SMTP server supports the CHUNKING extension.

**Comment by jstedfast** [comment]
I didn't add this change to the v2.3.0 release that I just made because this change is still somewhat risky but I wanted to get v2.3.0 released with all of the fixes I've done so far over the past 2 months.

The corner cases you found in MimeKit that didn't properly write a newline character have been fixed so I'm guessing it's probably safe now but I gotta see if I can figure out a way to add MimeKit unit tests that cover more potential cases to feel confident enough to make this change.

**Comment by nitinag** [comment]
Makes sense. If you put it into the post-release MyGet builds, I'm comfortable putting it into use and reporting back on any issues as well.

**Comment by jstedfast** [comment]
Not sure why I didn't think of this simple solution yesterday... but the above commit modifies the SmtpDataFilter to ensure that the output ends with a CRLF sequence, and if not, adds it in the Flush().

Now that the SmtpDataFilter *ensures* the data ends with CRLF, we can change EndData from `\r\n.\r\n` to `.\r\n` without any need to worry at all if there are any remaining corner-cases in MimeKit.

**Comment by nitinag** [comment]
That works as well.

Taking a look at the changes, I don't see `SmtpDataFilter` tracking a CR (would need to be tracked across buffers as well in case CR and LF were in two separate buffers). Thus, it does not seem to add the missing CRLF at the end of DATA when the stream ends with just LF (without the CR)? Though, this also shouldn't matter since the forced `FormatOptions.EnsureNewLine` will ensure CRLF is present.

**Comment by nitinag** [comment]
On further review, I notice that since it also runs through Unix2DosFilter filter before hitting `SmtpDataFilter` to ensure all LF are CRLF, it's not needed in `SmtpDataFilter`?

**Comment by jstedfast** [comment]
Correct. No need to track CRLF vs LF in the SmtpDataFilter because all content that reaches the SmtpDataFilter has already been converted to CRLF from LF.
