### ISSUE TITLE
The IMAP server has unexpectedly disconnected. Office365

### ISSUE THREAD

**Issue by J-McElroy** [jstedfast/MailKit#898]
We've been receiving huge number of errors with the following description starting from August 26th:
```
MailKit.Net.Imap.ImapProtocolException: The IMAP server has unexpectedly disconnected.
   at MailKit.Net.Imap.ImapStream.ReadAheadAsync(Int32 atleast, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapStream.ReadTokenAsync(String specials, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Imap.ImapCommand.StepAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.IterateAsync(Boolean doAsync)
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic, Boolean doAsync)
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
```

Examples from protocol log:
1) IMAP Protocol Log:

```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [TABOAFgAUAAyADYANQBDAEEAMAAwADkANQAuAEcAQgBSAFAAMgA2ADUALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: L00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: L00000000 OK CAPABILITY completed.
C: L00000001 AUTHENTICATE PLAIN XXXXX
S: L00000001 NO AUTHENTICATE failed.
C: L00000002 LOGIN "account@domain.com\\mailbox@domain.com" password
```

2)
```
Connected to imaps://outlook.office365.com:993/
S: * OK The Microsoft Exchange IMAP4 service is ready. [TABPADIAUAAyADYANQBDAEEAMAAyADMAOAAuAEcAQgBSAFAAMgA2ADUALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
C: Q00000000 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
S: Q00000000 OK CAPABILITY completed.
C: Q00000001 AUTHENTICATE PLAIN XXXXX
```

Is it somehow related to Mailkit? Or is it the problem on Office365 side?

MailKit version is v2.1.5.1

Thanks,
Alex

**Comment by jstedfast** [comment]
The problem is that you lost your connection to the server because either the server disconnected you or your network connection went down.

I get this question a lot (at least twice a week), so maybe I need to write a FAQ entry about this...

Network connections drop. It's inevitable. They drop all the time for all manner of reasons. They are just not reliable no matter how fast your network connection is, no matter how fast your computer is, no matter what OS and/or other software you are using.

When you are writing software that makes use of internet connections, you need to build robustness into your software to handle unexpected disconnects. You *will* hit them and when you do, you need to reconnect and try again. Some software will employ a "backoff" strategy where it will reconnect immediately after the first unexpected disconnection and then if that retry fails, wait a few seconds before trying again. If that also fails, exponentially increase that delay (until it reaches some reasonable upper threshold) and keep trying in a loop until it is finally successful and/or prompt the user whether it should even bother trying anymore.
