### ISSUE TITLE
How to send appointment email?

### ISSUE THREAD

**Issue by Jasonzhangjs** [jstedfast/MailKit#914]
I want to use mailkit to send an outlook appointment with attachments,
What should I do?

**Comment by jstedfast** [comment]
The first thing I would recommend that you do is to send such a message using Outlook and then look at the raw MIME message that it sends so that you can mimic the structure using MimeKit.

You may find https://github.com/rianjs/ical.net useful for creating the `text/ical` MIME part's content.

Beyond that, I can't help you because I don't know what such an email would look like.
