### ISSUE TITLE
Unable to fetch Text part for email when fetching from Folder other than Inbox

### ISSUE THREAD

**Issue by arunnav** [jstedfast/MailKit#918]
**Describe the bug**
Doing 
`client.Inbox.Fetch() => **Retrieves email with HtmlBody and TextBody**`

Whereas doing -
```
var mailFolder = client.GetFolder("Sent Items");
mailFolder.Open(FolderAccess.ReadOnly);
mailFolder.Fetch() => **Retrieves only HtmlBody**
```

I tried with the same email in both folders. So the email isn't the issue as far as I can see. 

When I tried downloading .eml and .msg files for the email and using another library MSGReader, I am able to read the textbody. Even when using MailKit to read .eml file, I can view the textbody. (However .eml files downloaded using MailKit did not have TextBody)

Further testing revealed that doing `client.GetFolder("Inbox").Fetch(...)` does not retrieve TextBody but by doing `client.Inbox.Fetch(....)`, TextBody is being retrieved.

I tried

```
mailFolder.Fetch(0, -1, MessageSummaryItems.Body | MessageSummaryItems.BodyStructure),
mailFolder.Fetch(0, -1, MessageSummaryItems.All)
```
`mailFolder.GetMessage(<uid>) also returns MimeMessage with no TextPart`

**Expected behavior**
TextBody should also be retrieved when fetching from Folders other than Inbox

**Environment**
 - Windows 10, Azure app service
 - Using dotnet core 2.2 to access outlook.office365.com server using IMAP protocol

**Comment by jstedfast** [comment]
Please provide an IMAP protocol log of the exchange so that I can see what is going on.

**Comment by jstedfast** [comment]
FWIW, `MessageSummaryItems.BodyStructure` supersedes `MessageSummaryItems.Body`, so specifying both is pointless.

And `MessageSummaryItems.All` is a mask that does not container either `Body` nor `BodyStructure`.

I know, it's confusing, but `All`, `Fast` and `Full` are designed to be identical to the IMAP macros: `ALL`, `FAST`, and `FULL`.

**Comment by jstedfast** [comment]
> mailFolder.GetMessage(<uid>) also returns MimeMessage with no TextPart

Do you mean it has no `TextPart` at all? Or that the `TextBody` is null? Those are 2 different things and I want to make sure we're talking about the same thing.

The `TextBody` property is not fool-proof and is only meant to provide an easy way of getting the text/plain body of a message *ASSUMING* that it follows standard conventions for structuring the message contents.

A MimeMessage with no `TextPart`s, on the other hand, means that the raw message has no text/* parts at all and is thus indicates there is no bug in MimeKit/MailKit.

**Comment by arunnav** [comment]
I might be confusing TextPart and TextBody, The TextBody property is always coming in as null. Going through the BodyParts property, I can see that text/plain part is not present. 

I tested by copying the same email which was in my Inbox to a folder "Inbox\Test". This email has no attachments.

I used GetMessage() method to retrieve the same email from both locations. Attached the protocol log - [ProtocolLogger.log](https://github.com/jstedfast/MailKit/files/3660946/ProtocolLogger.log)

**Comment by arunnav** [comment]
The above test was using GetMessage(), I ran one test using Fetch(0,0, MessageSummaryItems.BodyStructure) for both the folders. Attached protocol log -
[ProtocolLogger.log](https://github.com/jstedfast/MailKit/files/3660963/ProtocolLogger.log)

I'm starting to wonder if copy-pasting an email between folders in Outlook windows client could be changing the email and not keeping the text/plain part of it.

**Comment by jstedfast** [comment]
> I'm starting to wonder if copy-pasting an email between folders in Outlook windows client could be changing the email and not keeping the text/plain part of it.

Yep, that's what appears to be happening.

In any case, the IMAP (Exchange) server is returning 2 completely different messages. The message in Inbox\Test is not identical to the one in Inbox.

When you copied the message from the Inbox into Inbox\Test, it also appears to have reformatted some of the headers (check the Message-ID header for example, it has been rewrapped).

The `Date:` headers are different as well:

Date header from Inbox: `Date: Tue, 28 May 2019 09:18:46 +0000`
Date header from Inbox\Test: `Date: Tue, 28 May 2019 14:48:46 +0530`

Both dates *do* correspond to the same date & time when adjusted to the same timezone, but Outlook is clearly modifying the message when you copy it to another folder.

Is your Outlook client connecting to Exchange via the IMAP protocol? Or the Exchange protocol?

My *guess* is that since Outlook is probably configured to show the HTML version of message bodies. When you copied the message over to Inbox\Test, it reconstructed a MIME message based on what it had cached and then appended to that the Inbox\Test folder.

If Outlook connects via the IMAP protocol, though, I would have expected it to use the IMAP COPY command which would have copied the message byte-for-byte to the Inbox\Test folder.

**Comment by arunnav** [comment]
Thanks for the clarification, I'll have to check my outlook settings. And thanks for this great library and all your efforts !

**Comment by ColossusFX** [comment]
I have just come across this issue too.
Copy/move emails into folder using Outlook.

I can get email summaries of all uid's, but those emails in INBOX\Other\Folder, do not get the attachments I need.
