### ISSUE TITLE
kerberose authentication type 

### ISSUE THREAD

**Issue by dayanandm123** [jstedfast/MailKit#930]
I would like to use Kerberose authentication type as for smtp mail communications with ssl and without ssl.
Please let me know same has been supported By mailkit, the MS mail servers configured in windows and Linux machines.

Thanks.
Dayanand M

**Comment by jstedfast** [comment]
What you need to do is subclass `MailKit.Security.SaslMechanism` (e.g. `KerberosSaslMechanism`) and then when you go to authenticate, do this:

```csharp
client.Authenticate (new KerberosSaslMechanism (...));
```

**Comment by dayanandm123** [comment]
Is it require to implement kerberosesaslmechanism with kerberose authentication related logic?
Is it available in hand from mailkit as we use other AUTH types like plan login md5 etc..

**Comment by jstedfast** [comment]
> Is it require to implement kerberosesaslmechanism with kerberose authentication related logic?

No, you can just use a few `i++`'s and maybe some `var x = 5;`'s. That should totally work.

I'm being sarcastic, but I guess I just figured the answer to this question was obvious.

> Is it available in hand from mailkit as we use other AUTH types like plan login md5 etc..

No. If it was, I would have just told you how to use it rather than telling you that you'll need to write your own `KerberosSaslMechanism` class.
