### ISSUE TITLE
Thread safe SmtpClient

### ISSUE THREAD

**Issue by MikeChristensen** [jstedfast/MailKit#936]
**Is your feature request related to a problem? Please describe.**
It would be fantastic to create one instance of SmtpClient and share it across threads.  That way you'd only need to connect and authenticate once, and you could efficiently send many emails across that connection using something like TPL Dataflow.

**Describe the solution you'd like**
The HttpClient would be a good model to copy.  Just create a static instance of the client, and multiple threads could call `Send()`

**Describe alternatives you've considered**
I have a working prototype of sending SMTP email in bulk using multiple threads.  However, each thread has to create its own instance of SmtpClient which is a hassle.

**Additional context**

**Comment by jstedfast** [comment]
I welcome pull requests to add such a feature.

**Comment by coader** [comment]
is it thread safe now? not found description in document and pr

**Comment by jstedfast** [comment]
What are you hoping for with thread safety?

Are you hoping to send multiple messages using the same SmtpClient instance at the exact same time from multiple threads?

If so, do you have any idea how sockets work? How do you think that would work, exactly?

**Comment by jstedfast** [comment]
Why do you need MailKit's SmtpClient to be thread safe?

You guys are being ridiculous.

Is List<T> thread safe?

Did you ever consider just doing your own locking? It's so simple to do:

lock (client.SyncRoot) {
    client.Send (message);
}

Now you have thread safety.

**Comment by lukos** [comment]
The following basically works with `private SemaphoreSlim clientLock = new SemaphoreSlim(1, 1);`

```csharp
await clientLock.WaitAsync(token);
try
{
    await client.SendAsync(message, token, progress);
}
finally
{
    clientLock.Release();
}
```

However, you still need to be careful with any other code that is disconnecting or disposing the client but also avoiding excessive locking. For example, I call `NoOp()` before using the client to ensure it is still connected but if this fails, I disconnect the client so it gets removed and not used any more but of course, various threads could already have got through the `Connected` check and are mid-way through `SendAsync()` when this happens and instead of getting a nice error, we get the random NullReferenceException, understandable but not great.

I need to spend more time carefully locking some more scenarios.
