### ISSUE TITLE
Determine folder message is in

### ISSUE THREAD

**Issue by kkaminker** [jstedfast/MailKit#940]
When I am handling a message, and I decide to add a flag to it, I do not always know which folder it is in, and therefore do not know on which folder to set the flags (MailFolder.AddFlags())

I would like it if there were a way to obtain the knowledge of which folder the message is in, perhaps by:
1. MimeMessage having an IMailFolder property - folder (message.Folder)
2. ImapClient having a function such as GetMessageFolder(UniqueId uid)

Otherwise, I will have to somehow keep track of the current location of the message, which would not be as clean.
Perhaps there is already a way for me to get this information that I do not know of. I would appreciate any guidance on the issue.

Thank you

**Comment by jstedfast** [comment]
You just have to keep track of it yourself.

**Comment by kkaminker** [comment]
Okay, thanks anyway

**Comment by jstedfast** [comment]
There's a whole ton of problem with doing what you are asking for:

1. `ImapClient.GetMessageFolder (UniqueId)` also cannot possibly work because UIDs are only unique *per folder*, not per server. In other words, you can have a message in Inbox that has a UID of 45 and a different message in your Sent folder with a UID of 45.
2. `MimeMessage` lives in MimeKit which knows nothing about MailKit, which is where `IMailFolder` and `UniqueId` live.
3. Even if I merged MimeKit and MailKit so that `MimeMessage` *could* reference an `IMailFolder`, what happens if the `ImapClient` gets disconnected/disposed while you are still using the `MimeMessage` and then you want to add flags to it? Doing things this way opens a MASSIVE can of worms.

**Comment by kkaminker** [comment]
I see, okay thank you
