### ISSUE TITLE
Smtp lifetime

### ISSUE THREAD

**Issue by FIVIL** [jstedfast/MailKit#941]
Hi, I was wondering how should I use `MailKit.Net.Smtp.smptclient` object, and what is the best life-time for `smtpclient` object.
I mean should I use it as a singleton object, or is it ok to use it with c# `using(resource)` pattern?
my main concern here is how `smtpclient`  object handles underlying network connection, and what should I do in order to avoid socket exhaustion.

I am asking this since all the tutorials on the web use `smtpclient` with c# `using(resource)` pattern. However, if `smtpclient` is anything like .net `httpclient` this is going to mess things up in production

**Comment by jstedfast** [comment]
With any of the MailKit Smtp/Pop3/ImapClient classes, a socket is instantiated/connected in the `Connect` method and disconnected/disposed in the `Disconnect` method. The `Dispose` method on each of the Client classes will force a disconnect by calling `Disconnect (false)` but they will just kill the socket rather than sending a "LOGOUT" command, so I would definitely recommend calling `Disconnect (true)` before `Dispose` whether you use the `using(resource)` pattern or not.

The problem people get into with `HttpClient` is that they dispose the client way too aggressively, not giving the OS time to clean up the disconnected socket(s) before instantiating a new HttpClient and making the next request, e.g.:

```csharp
for (int i = 0; i < 1000; i++) {
    using (var new HttpClient ()) {
        // make a request, process it, etc...
    }
}
```

This *can* also be a problem with MailKit. For example, if you have 1000 messages you want to send, I would recommend reusing the same SmtpClient instance like this:

```csharp
using (var client = new SmtpClient ()) {
    client.Connect ("smtp.server.com", 587, SecureSocketOptions.StartTls);
    client.Authenticate ("username", "password");

    for (int i = 0; i < 1000; i++) {
        client.Send (messages[i]);
    }

    client.Disconnect (true);
}
```

**Comment by FIVIL** [comment]
Thank you for your detailed answer, one last thing though.
since I am planning to use this in a web server, which sends emails to users, I was wondering if MailKit Smtp/Pop3/ImapClient classes are thread-safe or should I take care of managing threads and locks??

**Comment by jstedfast** [comment]
They are not thread-safe.
