### ISSUE TITLE
MailKit.Security.SslHandshakeException wrongly returned if host doesn't support any of the proposed SslProtocols

### ISSUE THREAD

**Issue by edisfera** [jstedfast/MailKit#957]
**Describe the bug**
When connecting to a host using SSL but specifing unsupported protocols, MailKit returns SslHandshakeException proposing a variety of solutions none of which is pertinent to the kind of error that has occurred:

"MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions."

**To Reproduce**
Steps to reproduce the behavior: just try a connection to smtps.aruba.it using SmtpClient and leave the defualt SslProtocols (Tls11|Tls12) and you will get a SslHandshakeException becuase the server accepts SSL3.0 and not Tls (SslProtocol = Default).

**Expected behavior**
The exception should return the original exception message (A call to SSPI failed, see inner exception. The inner exception message was about a missing common protocol to be used between the client and the server) that would help to troubleshoot the mentioned problem.

 - Version 2.4.1

Note that to troubleshoot this issue I hade to compile and run the DDL in debug mode. In fact, one of the proposed solutions suggested to enable the ServerCertificateValidationCallback that in the above case would never be fired because the error happens before the certificate is used and the callback is called.

**Comment by jstedfast** [comment]
You probably already know this but:

[Why you should disable SSLv3](https://disablessl3.com/)
[Why you should disable TLSv1](https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions/)
[Deprecating TLS 1.0 & 1.1](https://www.digicert.com/blog/depreciating-tls-1-0-and-1-1/)

**Comment by edisfera** [comment]
Hi jstedfast, I just reported this issue because I spend more than a day to understand why when I was trying to a mail service I don't manage an SslHandshakeException was issued. It would have saved me a lot of time if the real message was proposed in the exception instead of being misled by a certificate issue. Of course, I cannot impose on an external service to disable TLSv1 or SSLv3. When I found out the real message I just tried the Default value for the SslProtocol instead of Tls11|Tls12 (which is the default setting for that field) and magically the connection was established.
I hope this issue can help others to try also with the SslProtocol propties if the ServerCertificateValidationCallback  method is not even invoked.

Thank you

**Comment by jstedfast** [comment]
Of course! I did not mean to suggest that you had control over the server, I just meant for it to be helpful if you didn't already know about these SSL/TLS deprecations (and for anyone else that may find this reported issue due to hitting the same problem).

Hopefully the new text for the SslHandshakeException message provides a better hint that would help in cases like yours which are becoming more common because I recently dropped support for TLS v1.0 by default. I had assumed that by now, servers wouldn't still be using it, but apparently I was wrong.

I've also added text to the FAQ to better reflect the first line of the exception message as well as to explain this potential reason for the SSL handshake failing.

Thanks for reporting this issue - I agree that improving the wording of the exception message is a good idea.

FWIW, the inner exception thrown by Mono is effectively worthless (I tested connecting to your smtp server on MacOS using Mono to see the InnerException), so it seems that different implementation of the SslStream will throw not only different exceptions types (Mono.Security.TlsException or something like that), but have completely different exception text, making it extremely difficult to diagnose (hence why I created SslHandshakeException).
