### ISSUE TITLE
Provide Interface for ImapFolder

### ISSUE THREAD

**Issue by kolletzki** [jstedfast/MailKit#960]
**Is your feature request related to a problem? Please describe.**
When writing tests, It's very hard to mock `ImapFolder`.

I have a method (let's call it `FetchFolders`) that calls `ImapClient.GetFoldersAsync` and calls a second method for each folder. This second method (`FetchMessages`) then takes the `ImapFolder` instance and calls `GetStreamsAsync` on it.

For my `FetchFolders` method, I've created a custom `ImapClient` implementation with a corresponding interface that allows me to properly test this method. For `FetchMessages` though, I'm unable to provide a custom type since `ImapClient.GetFoldersAsync` returns `ImapClient` instances which I'm unable to cast to a derived type.

**Describe the solution you'd like**
I'd like to have an interface `IImapFolder` that defines all `ImapFolder` members. `ImapFolder` should implement this interface. Ideally, all `ImapClient.GetFolders` methods should then return instances of `IImapFolder` instead of `IMailFolder`, however this would not be necessary since one could cast the `ImapFolder` instances to `IImapFolder`.

In addition, an `IImapClient` interface would be handy, so that one does not have to create a custom derived type and interface for testing methods using `ImapClient`.

**Additional context**
Maybe I'm missing some obvious solution, if so, I'm sorry for the trouble. However, if there is any need for a PR, I'd be happy to provide one.

**Comment by jstedfast** [comment]
I think what you are looking for is `IMailFolder` which is the interface that `ImapFolder` implements.

Likewise, `ImapClient` implements `IMailStore` (which implements `IMailService` for Connect, Authenticate, Disconnect, etc).

That said, `IMailFolder` is missing `GetStreams()` and `GetStreamsAsync()` because the callbacks for those are in the `MailKit.Net.Imap` namespace and should eventually get moved down into `MailKit` so that they can be added to `IMailFolder`.

`IMailFolder` is also missing some very low-level `Search()` methods iirc, because they take a `string` argument which needs to be properly formatted for the IMAP SEARCH syntax which isn't going to translate well to a generic interface that would work for all future mail storage protocols/backends (I had plans to eventually implement mbox and Maildir backends and wanted it to be *possible* for someone to implement an Exchange protocol backend as well using the interfaces I've provided).

`IMailStore` is mostly missing IMAP-specific things like `Idle()` and `IdleAsync()`, probably `Notify()` and `NotifyAsync()` as well. And then it's also missing the `Capabilities` property, of course.

**Comment by kolletzki** [comment]
I understand the approach of having all members in the `MailKit` namespace suitable to all protocols/backends, in fact I think it makes a lot of sense for people writing a multi-protocol client.

However, when keeping the `MailKit` namespace free from protocol specific members (e.g. I also use IMAP's `Identify()` method), what would argue against `IImapClient` and `IImapFolder` that define these IMAP specific methods and allow much easier testing? In addition, this would allow future protocol specific extensions.

My current workaround is to take an `IMailFolder` and do some pattern matching to allow it to be mocked, which is not a nice solution IMHO.

```c#
async Task FetchMessages(IMailFolder folder)
{
    Func<int, int, ImapFetchStreamAsyncCallback, CancellationToken, ITransferProgress, Task> getStreamsDelegate = folder switch
    {
        ImapFolder imapFolder => imapFolder.GetStreamsAsync,
        MockImapFolder mockFolder => mockFolder.GetStreamsAsync,
        _ -> throw new ArgumentException("Argument must be of type ImapFolder or MockImapFolder", nameof(folder))
    };

    getStreamsDelegate(/* ... */);
}
```

For `ImapClient`, my workaround is to have a custom interface `IImapClient` which inherits from `IMailStore` and an implementation `DefaultImapClient` that implements `IImapClient` and extends `ImapClient`:

```c#
interface IImapClient : IMailStore
{

    ImapCapabilities Capabilities { get; set; }

    Task<ImapImplementation> IdentifyAsync(ImapImplementation clientImplementation, CancellationToken cancellationToken = default);
}

class DefaultImapClient : ImapClient, IImapClient
{
}
```

These workarounds do their jobs, however I think that not needing them would be even nicer.

**Comment by jstedfast** [comment]
I implemented this yesterday but forgot to commit it.
