### ISSUE TITLE
Implement IAsyncDisposable for SmtpClient 

### ISSUE THREAD

**Issue by MischaVreeburg** [jstedfast/MailKit#964]
For using correctly the dispose pattern in combination with async message sending, I'd like to request the implementation of the new C# 8.0 IAsyncDisposable interface for the EmailClients.

If implemented we can then use the new Await using statement to asynchronologically dispose the email client and not be worried about the  client being disposed before the emails are sent.

**Comment by jstedfast** [comment]
This isn't actually needed. The following `using` pattern is perfectly safe with `async` code:

```csharp
using (var client = new SmtpClient ()) {
    await client.ConnectAsync ("host.com", 587, SecureSocketOptions.StartTls);
    await client.AuthenticateAsync ("username", "password");
    await client.SendAsync (message);
    await client.DIsconnectAsync (true);
}
```

All `IAsyncDisposable` does is allow you to effectively dispose the object in another thread. It isn't about blocking until the previous await calls have finished. The reason that a `DisposeAsync()` is needed is that some objects make use of native resources (such as Sockets) that can take a while to clean up and so calling `Dispose()` in the main thread would block the UI.

This isn't really an issue with MailKit because it offers the `DisconnectAsync(bool, CancellationToken)` method and so as long as you `await client.DisconnectAsync(...)`, then `Dispose()` will not block because the socket will already be closed.

I *may* still implement this, but it's kind of debatable... Currently, if you do not call `Disconnect()` or `DisconnectAsync()`, the `Dispose()` method will automatically call the equivalent of `Disconnect (false)`.

The `bool quit` parameter for `Disconnect()` and `DisconnectAsync()` is to tell the client whether it should send the `QUIT` or `LOGOUT` command to the server. The reason that you should, generally, pass `true` to these methods is that it disconnects from the server cleanly rather than just severing the TCP/IP connection and so it is considered good netiquette. For Pop3Client, it is also the only way to purge the mailbox after issuing `DELE` commands. An unclean disconnect will not purge those messages.

Since developers using MailKit *should* almost-always call `DisconnectAsync(true)` (unless they want the reset the deleted-state of messages on a POP3 server) before calling `Dispose()` (or `DisposeAsync()` if I implement `IAsyncDisposable`), it kinda makes `IAsyncDisposable` pointless.

**Comment by nickolaym** [comment]
Immediately delete this repository! It offences all people who celebrate you know that holiday, and also who celebrates the release of Stalingrad.
