### ISSUE TITLE
Send Message with SmtpClient, Error 550

### ISSUE THREAD

**Issue by danexis-szu** [jstedfast/MailKit#968]
I try to send messages with SmtpClient. At one time it worked, at another time it doesn't. All parameters seem to be the same, same addresses, same message, same credentials.

What is the problem??
[SmtpClientNotWorking.log](https://github.com/jstedfast/MailKit/files/3997734/SmtpClientNotWorking.log)
[SmtpClientWorked.log](https://github.com/jstedfast/MailKit/files/3997735/SmtpClientWorked.log)

I usually got a "MailKit.Net.Smtp.SmtpCommandException" with "RecipientNotAccepted".
Differences in the two log files:
(mrgmx104)               vs                 (mrgmx004)

and the Size of the mail is different

**Comment by jstedfast** [comment]
```
S: 550-Requested action not taken: mailbox unavailable
S: 550 Failure sending mail. Try again later
```

That's the error your SMTP server is returning when MailKit provides the destination email address.

The only way to know *why* the destination email address is being rejected (note: it's not the *message* that is being rejected, it's the recipient) is to contact gmx.de tech support and ask them.

If I were to make a guess, I'd bet that it's because their SMTP server has decided that you are spamming or something.
