### ISSUE TITLE
Inline images from window snipping tool not working

### ISSUE THREAD

**Issue by tbizot-fullstack** [jstedfast/MailKit#973]
Description:
Emails which contain in the html body an image, which is created by the snipping tool of windows, the the image is received incorrectly.
In the html its showing: `<img>`, so the rest is missing. In Outlook the image is showing correctly.

Steps to reproduce:
1. Create an email, and paste in an image in the body which is created by the snipping tool in Windows 10.
2. Send this email.
3. Receive the email with the following code: client.Inbox.GetMessage(MailKit.UniqueId.Parse(0))

Expected behavior
The email show with the image.

Desktop (please complete the following information):
 - OS: windows 10
 - Browser: chrome

**Comment by jstedfast** [comment]
MimeKit/MailKit don't render messages, so this doesn't appear to make sense as a bug filed against them.

What does the raw message look like and why do you think the problem is with MimeKit/MailKit?

Keep in mind, as well, that MimeKit/MailKit don't even touch the HTML content, so it's not possible for them to break the HTML.
