### ISSUE TITLE
find uid of the last letter from a person

### ISSUE THREAD

**Issue by NerzOff** [jstedfast/MailKit#975]
hi, how can I find the uid of the last (new) letter from "sad@sad.com"?

I read the documentation, looked at the examples, but still did not understand how to implement this.
I ask for your help. thanks

**Comment by jstedfast** [comment]
I would suggest using the Search functionality.

```csharp
var uids = folder.Search(SearchQuery.FromContains ("sad@sad.com").And (SearchQuery.New));
if (uids.Count > 0) {
    var last = uids[uids.Count - 1];
}
```

Note: `SearchQuery.New` matches messages with the `\Recent` flag which will only be present in the very first IMAP client session after the message was delivered. If you reconnect later, the `\Recent` flag will be gone.

If you only care about whether the message has been read or not, use `SearchQuery.NotSeen` instead of `SearchQuery.New`.
